In [77]:
import json
import glob
import os
from tqdm import tqdm

import numpy as np
import pandas as pd

# Dataset structure

In [33]:
!ls /vol/isy-rl/dtrofimov/data/aihabitat/hssd-hab/objects

0  1  2  3  4  5  6  7	8  9  a  b  c  d  decomposed  e  f  openings  x

In [43]:
file_paths = []
# Walk through the directory structure
for root, dirs, files in os.walk("/vol/isy-rl/dtrofimov/data/aihabitat/hssd-hab/objects"):
    for file in files:
        # Combine the root directory and file name to get the full file path
        file_paths.append(os.path.join(root, file))
print(len(file_paths))

56088

In [44]:
file_paths[:10]

['/vol/isy-rl/dtrofimov/data/aihabitat/hssd-hab/objects/c/ce35562fcce77597734c4d84aad960884c2be9d1.object_config.json',
 '/vol/isy-rl/dtrofimov/data/aihabitat/hssd-hab/objects/c/cc93f4155757ef3543b782171b136b4ff1b77b6d.glb',
 '/vol/isy-rl/dtrofimov/data/aihabitat/hssd-hab/objects/c/c5046dfe8edc365aa500c43bb357b0a7926dcb48.collider.glb',
 '/vol/isy-rl/dtrofimov/data/aihabitat/hssd-hab/objects/c/c3b9cd7b0b8308c9f750d4ae1f1254cb4cd6b03e.object_config.json',
 '/vol/isy-rl/dtrofimov/data/aihabitat/hssd-hab/objects/c/c9ac589dbef66b3e367d7851638a845e7ddc3600.object_config.json',
 '/vol/isy-rl/dtrofimov/data/aihabitat/hssd-hab/objects/c/cc85c356e547d86975d71f5405415e1019706178.glb',
 '/vol/isy-rl/dtrofimov/data/aihabitat/hssd-hab/objects/c/cb29b76112813f0e04c54b94157c207917dac109.collider.glb',
 '/vol/isy-rl/dtrofimov/data/aihabitat/hssd-hab/objects/c/c2f412d6053a51a162ad0c42eb0116d30cd181be.object_config.json',
 '/vol/isy-rl/dtrofimov/data/aihabitat/hssd-hab/objects/c/cd2e333e291c64ac4acec135ff84956ecabd875d.filteredSupportSurface.glb',
 '/vol/isy-rl/dtrofimov/data/aihabitat/hssd-hab/objects/c/c2f412d6053a51a162ad0c42eb0116d30cd181be.glb']

In [21]:
path = "/vol/isy-rl/dtrofimov/data/aihabitat/hssd-hab/semantics/hssd-hab_semantic_lexicon.json"

In [24]:
with open(path, "r", ) as f:
    semantic_lexicon = json.load(f)

In [26]:
semantic_lexicon

{'classes': [{'name': 'alarm_clock', 'id': 1},
  {'name': 'bed', 'id': 2},
  {'name': 'book', 'id': 3},
  {'name': 'bottle', 'id': 4},
  {'name': 'bowl', 'id': 5},
  {'name': 'chair', 'id': 6},
  {'name': 'chest_of_drawers', 'id': 7},
  {'name': 'couch', 'id': 8},
  {'name': 'cushion', 'id': 9},
  {'name': 'drinkware', 'id': 10},
  {'name': 'fridge', 'id': 11},
  {'name': 'laptop', 'id': 12},
  {'name': 'microwave', 'id': 13},
  {'name': 'picture', 'id': 14},
  {'name': 'plate', 'id': 15},
  {'name': 'potted_plant', 'id': 16},
  {'name': 'shelves', 'id': 17},
  {'name': 'shoes', 'id': 18},
  {'name': 'sink', 'id': 19},
  {'name': 'stool', 'id': 20},
  {'name': 'table', 'id': 21},
  {'name': 'table_lamp', 'id': 22},
  {'name': 'toaster', 'id': 23},
  {'name': 'toilet', 'id': 24},
  {'name': 'trashcan', 'id': 25},
  {'name': 'tv', 'id': 26},
  {'name': 'vase', 'id': 27},
  {'name': 'washer_dryer', 'id': 28}]}

In [27]:
path_obj = "/vol/isy-rl/dtrofimov/data/aihabitat/hssd-hab/semantics/objects.csv"

In [28]:
df_objects = pd.read_csv(path_obj)

In [62]:
df_objects

,id,name,wnsynsetkey,up,front,foundIn,hasMultipleObjects,support,dims,aligned.dims,simClusterIds,floorplanner-category-tags,isArticulatable,main_wnsynsetkey,main_category,super_category
0,0001fb06b075a743e6289236cf049df3ad5dfa9c,Ryde Single Control Exposed Mini Valve with Ad...,showerhead.n.01,"0,0,-1","0,1,0",bathroom,False,vertical,NaN,"0.3956500291824341,1.009962022304535,0.2367790...",NaN,"Shower heads & Hoses,Bathroom,Showers & Shower...",False,NaN,NaN,NaN
1,000bbe302b53fd2904e7ae92e1516a18f29de02d,Antique Style Mirrored and Engraved Indian Tea...,candlestick.n.01,NaN,NaN,living room,False,NaN,NaN,"0.06005765497684479,0.10000018775463104,0.0603...",NaN,"Votives & Tea light holders,Living room,Access...",False,NaN,NaN,NaN
2,0022fa6ee5a44330e765488919803155b1a9e88c,Coppercomb Waste Bin,ashcan.n.01,NaN,NaN,bathroom,False,NaN,NaN,"0.1928401216864586,0.2529520297050505,0.192840...",NaN,"Bathroom bins,Furniture types,Accessories,Bath...",False,ashcan.n.01,trashcan,trashcan
3,0024ddad62413ac3089b4efe58b90b01c41123e8,2 doors 2 drawers Chinese hand-painted chest.,chest_of_drawers.n.01,NaN,NaN,"bedroom,living room",False,NaN,NaN,"0.8000330328941345,0.6000260909171722,0.381983...",NaN,"Trunks & Chests,Bedroom,Living room storage,Be...",True,chest_of_drawers.n.01,chest_of_drawers,storage_furniture
4,00258bed0c6e87a14e33c3eebffc48c898135698,Lismore Table Clock,mantel_clock.n.01,NaN,NaN,living room,False,NaN,NaN,"0.16058842092752457,0.2504031773423776,0.16504...",NaN,"Clocks,Living room,Accessories",False,mantel_clock.n.01,mantel_clock,clock
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17498,xxxxfd0c8cbfx9cbax42e1xbba6x3d56adb64218,"Maja Mosaic Pillows 24""x16"", Set of 2",throw_pillow.n.01,NaN,NaN,NaN,False,NaN,NaN,"0.628338634967804,0.3811854813247919,0.2523412...",NaN,NaN,False,cushion.n.03,cushion,decor
17499,xxxxfd3476fbx13acx48dfx9654x6295bd56e2d7,Oliver Rattan Basket,basket.n.01,NaN,NaN,living room,False,NaN,NaN,"0.4044420123100281,0.40632927417755127,0.40444...",NaN,"Storage baskets,Living room,Furniture types,Ac...",False,NaN,NaN,NaN
17500,xxxxfd360ba4x0b85x456dx9d25x27ce62ee4202,"Palm Trees Road with Black Frame 21.5""x25.5""",wall_art.n.01,"0,0,-1","0,1,0",NaN,False,vertical,NaN,"0.5457419157028198,0.6464591026306152,0.025400...",NaN,"Art,Accessories",False,wall_art.n.01,picture,decor
17501,xxxxfe3da986xd545x4e31xa7e4xa4211117520f,Black Marble Paper Towel Holder,NaN,NaN,NaN,living room,False,NaN,NaN,"0.1766471564769745,0.3442952036857605,0.176647...",NaN,"Storage cupboards & Cabinets,Living room stora...",False,NaN,NaN,NaN
17502,xxxxfec44175x9cb9x4b9cx9eddx518a02594ee4,Gallery Walnut 8x10 Picture Frame,wall_art.n.01,"0,0,-1","0,1,0",NaN,False,vertical,NaN,"0.46969568729400635,0.46969571709632874,0.0317...",NaN,"Art,Accessories",False,wall_art.n.01,picture,decor

In [65]:
df_objects[df_objects["id"] == "000bbe302b53fd2904e7ae92e1516a18f29de02d"].iloc[0].to_dict()

{'id': '000bbe302b53fd2904e7ae92e1516a18f29de02d',
 'name': 'Antique Style Mirrored and Engraved Indian Tea Glass Tealight Holder h 9.5cm',
 'wnsynsetkey': 'candlestick.n.01',
 'up': nan,
 'front': nan,
 'foundIn': 'living room',
 'hasMultipleObjects': False,
 'support': nan,
 'dims': nan,
 'aligned.dims': '0.06005765497684479,0.10000018775463104,0.060357242822647095',
 'simClusterIds': nan,
 'floorplanner-category-tags': 'Votives & Tea light holders,Living room,Accessories,Candles & Candle holders & Home fragrance',
 'isArticulatable': False,
 'main_wnsynsetkey': nan,
 'main_category': nan,
 'super_category': nan}

In [31]:
df_objects.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17503 entries, 0 to 17502
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          17503 non-null  object
 1   name                        15386 non-null  object
 2   wnsynsetkey                 15942 non-null  object
 3   up                          2895 non-null   object
 4   front                       2895 non-null   object
 5   foundIn                     9574 non-null   object
 6   hasMultipleObjects          16003 non-null  object
 7   support                     3321 non-null   object
 8   dims                        0 non-null      float64
 9   aligned.dims                17503 non-null  object
 10  simClusterIds               4415 non-null   object
 11  floorplanner-category-tags  14099 non-null  object
 12  isArticulatable             17503 non-null  bool
 13  main_wnsynsetkey            13562 non-null  object
 14  main_category               13562 non-null  object
 15  super_category              13562 non-null  object
dtypes: bool(1), float64(1), object(14)
memory usage: 2.0+ MB

In [32]:
df_objects["main_category"].value_counts()

main_category
picture         1295
table           1099
chair            977
window           929
carpet           858
                ...
eyeglasses         3
earphone           2
mobile_phone       2
colander           1
mixing_bowl        1
Name: count, Length: 85, dtype: int64

In [46]:
os.path.splitext("cb29b76112813f0e04c54b94157c207917dac109.collider.glb")[0]

'cb29b76112813f0e04c54b94157c207917dac109.collider'

In [48]:
"cb29b76112813f0e04c54b94157c207917dac109.collider.glb".split(".")[0]

'cb29b76112813f0e04c54b94157c207917dac109'

In [67]:
60 / 26 * 18000

41538.46153846153

In [70]:
18000 / (32 / 7) / (60)

65.625

In [72]:
df_objects[df_objects["id"] == "c1023577afa043a9017f38ade9ad7147ea7f0c37"]

,id,name,wnsynsetkey,up,front,foundIn,hasMultipleObjects,support,dims,aligned.dims,simClusterIds,floorplanner-category-tags,isArticulatable,main_wnsynsetkey,main_category,super_category
13324,c1023577afa043a9017f38ade9ad7147ea7f0c37,Titan Bench,bench.n.01,NaN,NaN,"living room,dining room",False,NaN,NaN,"1.879085659980774,0.4572392499578086,0.3807406...",NaN,"Benches,Dining room furniture,Living room,Furn...",False,bench.n.01,bench,seating_furniture

In [73]:
df_objects

,id,name,wnsynsetkey,up,front,foundIn,hasMultipleObjects,support,dims,aligned.dims,simClusterIds,floorplanner-category-tags,isArticulatable,main_wnsynsetkey,main_category,super_category
0,0001fb06b075a743e6289236cf049df3ad5dfa9c,Ryde Single Control Exposed Mini Valve with Ad...,showerhead.n.01,"0,0,-1","0,1,0",bathroom,False,vertical,NaN,"0.3956500291824341,1.009962022304535,0.2367790...",NaN,"Shower heads & Hoses,Bathroom,Showers & Shower...",False,NaN,NaN,NaN
1,000bbe302b53fd2904e7ae92e1516a18f29de02d,Antique Style Mirrored and Engraved Indian Tea...,candlestick.n.01,NaN,NaN,living room,False,NaN,NaN,"0.06005765497684479,0.10000018775463104,0.0603...",NaN,"Votives & Tea light holders,Living room,Access...",False,NaN,NaN,NaN
2,0022fa6ee5a44330e765488919803155b1a9e88c,Coppercomb Waste Bin,ashcan.n.01,NaN,NaN,bathroom,False,NaN,NaN,"0.1928401216864586,0.2529520297050505,0.192840...",NaN,"Bathroom bins,Furniture types,Accessories,Bath...",False,ashcan.n.01,trashcan,trashcan
3,0024ddad62413ac3089b4efe58b90b01c41123e8,2 doors 2 drawers Chinese hand-painted chest.,chest_of_drawers.n.01,NaN,NaN,"bedroom,living room",False,NaN,NaN,"0.8000330328941345,0.6000260909171722,0.381983...",NaN,"Trunks & Chests,Bedroom,Living room storage,Be...",True,chest_of_drawers.n.01,chest_of_drawers,storage_furniture
4,00258bed0c6e87a14e33c3eebffc48c898135698,Lismore Table Clock,mantel_clock.n.01,NaN,NaN,living room,False,NaN,NaN,"0.16058842092752457,0.2504031773423776,0.16504...",NaN,"Clocks,Living room,Accessories",False,mantel_clock.n.01,mantel_clock,clock
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17498,xxxxfd0c8cbfx9cbax42e1xbba6x3d56adb64218,"Maja Mosaic Pillows 24""x16"", Set of 2",throw_pillow.n.01,NaN,NaN,NaN,False,NaN,NaN,"0.628338634967804,0.3811854813247919,0.2523412...",NaN,NaN,False,cushion.n.03,cushion,decor
17499,xxxxfd3476fbx13acx48dfx9654x6295bd56e2d7,Oliver Rattan Basket,basket.n.01,NaN,NaN,living room,False,NaN,NaN,"0.4044420123100281,0.40632927417755127,0.40444...",NaN,"Storage baskets,Living room,Furniture types,Ac...",False,NaN,NaN,NaN
17500,xxxxfd360ba4x0b85x456dx9d25x27ce62ee4202,"Palm Trees Road with Black Frame 21.5""x25.5""",wall_art.n.01,"0,0,-1","0,1,0",NaN,False,vertical,NaN,"0.5457419157028198,0.6464591026306152,0.025400...",NaN,"Art,Accessories",False,wall_art.n.01,picture,decor
17501,xxxxfe3da986xd545x4e31xa7e4xa4211117520f,Black Marble Paper Towel Holder,NaN,NaN,NaN,living room,False,NaN,NaN,"0.1766471564769745,0.3442952036857605,0.176647...",NaN,"Storage cupboards & Cabinets,Living room stora...",False,NaN,NaN,NaN
17502,xxxxfec44175x9cb9x4b9cx9eddx518a02594ee4,Gallery Walnut 8x10 Picture Frame,wall_art.n.01,"0,0,-1","0,1,0",NaN,False,vertical,NaN,"0.46969568729400635,0.46969571709632874,0.0317...",NaN,"Art,Accessories",False,wall_art.n.01,picture,decor

# KHR presence

In [74]:
import json
import struct

def check_basis_universal_in_glb(glb_path):
    """
    Checks if a .glb file uses the KHR_texture_basisu extension for Basis Universal textures.

    Args:
        glb_path (str): Path to the .glb file.

    Returns:
        bool: True if the file uses Basis Universal textures, False otherwise.
    """
    with open(glb_path, "rb") as f:
        # Read the header (12 bytes)
        magic, version, length = struct.unpack("<III", f.read(12))

        # Check if it's a valid GLB file
        if magic != 0x46546C67:  # 'glTF' in ASCII
            raise ValueError("Invalid GLB file.")

        # Iterate through chunks
        while f.tell() < length:
            # Read the chunk header (8 bytes)
            chunk_length, chunk_type = struct.unpack("<II", f.read(8))
            chunk_data = f.read(chunk_length)

            # Check if it's the JSON chunk
            if chunk_type == 0x4E4F534A:  # 'JSON' in ASCII
                # Decode the JSON chunk
                gltf_data = json.loads(chunk_data.decode("utf-8"))

                # Check for extensions
                extensions_used = gltf_data.get("extensionsUsed", [])
                if "KHR_texture_basisu" in extensions_used:
                    return True

        return False

In [85]:
# Example Usage
glb_file_path = "/vol/isy-rl/dtrofimov/data/aihabitat-try"
if check_basis_universal_in_glb(glb_file_path):
    print(f"The file {glb_file_path} uses Basis Universal textures (KHR_texture_basisu).")
else:
    print(f"The file {glb_file_path} does NOT use Basis Universal textures.")

IsADirectoryError: [Errno 21] Is a directory: '/vol/isy-rl/dtrofimov/data/aihabitat-try'

In [76]:
khr = []

for root, dirs, files in os.walk("/vol/isy-rl/dtrofimov/data/aihabitat/hssd-hab/objects"):
    for file in files:
        filepath = os.path.join(root, file)
        if filepath.endswith(".glb"):
            if filepath.endswith(".collider.glb"):
                continue
            khr.append(check_basis_universal_in_glb(filepath))

KeyboardInterrupt:

In [80]:
sum(khr) / len(khr)

0.6204154911515773

# KTX converted

In [86]:
import os
import json
import subprocess

def convert_ktx2_to_png(ktx2_path, output_dir):
    """
    Converts a .ktx2 file to .png using ktx2ktx2.
    Args:
        ktx2_path (str): Path to the .ktx2 file.
        output_dir (str): Directory to save the converted .png file.
    Returns:
        str: Path to the converted .png file.
    """
    png_path = os.path.join(output_dir, os.path.basename(ktx2_path).replace(".ktx2", ".png"))
    subprocess.run(["ktx2ktx2", "--decode", ktx2_path, "-o", png_path], check=True)
    return png_path

def update_gltf_references(gltf_path, output_dir):
    """
    Updates the .gltf file to replace .ktx2 references with .png.
    Args:
        gltf_path (str): Path to the .gltf file.
        output_dir (str): Directory containing the converted .png files.
    Returns:
        str: Path to the updated .gltf file.
    """
    # Load the GLTF file
    with open(gltf_path, "r", encoding="utf-8") as f:
        gltf_data = json.load(f)
    
    # Update the image references
    for image in gltf_data.get("images", []):
        if image.get("uri", "").endswith(".ktx2"):
            png_name = os.path.basename(image["uri"]).replace(".ktx2", ".png")
            image["uri"] = png_name  # Update to .png reference

    # Save the updated GLTF file
    updated_gltf_path = os.path.join(output_dir, os.path.basename(gltf_path))
    with open(updated_gltf_path, "w", encoding="utf-8") as f:
        json.dump(gltf_data, f, indent=2)
    
    return updated_gltf_path

def process_gltf(glb_path, output_dir):
    """
    Processes a .glb file by converting .ktx2 textures to .png and updating references in the .gltf file.
    Args:
        glb_path (str): Path to the .glb file.
        output_dir (str): Directory to save the processed files.
    """
    # Extract the .glb file
    gltf_pipeline_command = ["gltf-pipeline", "-i", glb_path, "-o", os.path.join(output_dir, "output.gltf"), "--separate"]
    subprocess.run(gltf_pipeline_command, check=True)

    # Identify extracted files
    extracted_files = os.listdir(output_dir)
    ktx2_files = [f for f in extracted_files if f.endswith(".ktx2")]
    gltf_file = [f for f in extracted_files if f.endswith(".gltf")][0]

    # Convert all .ktx2 files to .png
    for ktx2_file in ktx2_files:
        convert_ktx2_to_png(os.path.join(output_dir, ktx2_file), output_dir)
    
    # Update the .gltf file references
    updated_gltf_path = update_gltf_references(os.path.join(output_dir, gltf_file), output_dir)

    # Optionally repackage into a .glb file
    final_glb_path = os.path.join(output_dir, "final_output.glb")
    subprocess.run(["gltf-pipeline", "-i", updated_gltf_path, "-o", final_glb_path], check=True)

    print(f"Processed GLB file saved at: {final_glb_path}")

In [87]:
# Example Usage
input_glb = "/vol/isy-rl/dtrofimov/data/aihabitat-try/0001fb06b075a743e6289236cf049df3ad5dfa9c.glb"
output_dir = "/vol/isy-rl/dtrofimov/data/aihabitat-try-render/"
os.makedirs(output_dir, exist_ok=True)
process_gltf(input_glb, output_dir)

FileNotFoundError: [Errno 2] No such file or directory: 'gltf-pipeline'

In [89]:
!gltf-pipeline --help

/bin/bash: line 1: gltf-pipeline: command not found