In [1]:
import objaverse
import objaverse.xl as oxl

import pandas as pd
import numpy as np
import random

# Meshes

In [2]:
obj_path = "/vol/isy-rl/dtrofimov/data/objaverse"

In [3]:
annotations = oxl.get_annotations(
    download_dir=obj_path
)

In [4]:
annotations["metadata"] = annotations["metadata"].apply(eval)

In [5]:
annotations[annotations["metadata"].apply(lambda x: len(x) > 0)]

,fileIdentifier,source,license,fileType,sha256,metadata
5236361,https://thingiverse.com/thing:2609614/files?fi...,thingiverse,Creative Commons - Attribution - Non-Commercial,stl,82e4d7eb817c1a352d7a12def0b78b66991fb71efdfa08...,{'filename': 'Roof_bottom.stl'}
5236362,https://thingiverse.com/thing:2609614/files?fi...,thingiverse,Creative Commons - Attribution - Non-Commercial,stl,fd389685afabfdbfaf3486c34ea73d1363c7ce7acac9df...,{'filename': 'Stable_base.stl'}
5236363,https://thingiverse.com/thing:2609614/files?fi...,thingiverse,Creative Commons - Attribution - Non-Commercial,stl,6dabb0fbf32d6093207cf6f128b659c817882f43ab3f4c...,{'filename': 'Roof_left.stl'}
5236364,https://thingiverse.com/thing:2609614/files?fi...,thingiverse,Creative Commons - Attribution - Non-Commercial,stl,147f69858bee722bb96a4094c28da5f5f6c0924f023939...,{'filename': 'Roof_right.stl'}
5236365,https://thingiverse.com/thing:3522959/files?fi...,thingiverse,Creative Commons - Attribution - Non-Commercial,stl,0fd4c8e534d12cb484694f8c5f91043fcef845809d7f8c...,{'filename': 'Pictureframe_Wallmount.stl'}
...,...,...,...,...,...,...
8970975,https://3d-api.si.edu/content/document/3d_pack...,smithsonian,Creative Commons Zero v1.0 Universal,glb,4b6b07001626cfc280249df36590047c3364e7a779c7f1...,{'title': 'Prototype of a digital heart rhythm...
8970976,https://3d-api.si.edu/content/document/3d_pack...,smithsonian,Creative Commons Zero v1.0 Universal,glb,2c9fbe4e671def77f08c50b64b5668e41e00a6f7d54397...,{'title': 'Red Starfleet uniform worn by Niche...
8970977,https://3d-api.si.edu/content/document/3d_pack...,smithsonian,Creative Commons Zero v1.0 Universal,glb,0547338bfa42ad3fa4b7668ae88c468653a91de7b8bc56...,{'title': 'Flight suit worn by Charles F. Bold...
8970978,https://3d-api.si.edu/content/document/3d_pack...,smithsonian,Creative Commons Zero v1.0 Universal,glb,f69b62bb07a464ee4bbdfaa8f66bfd7ff4d2281d7f9bc6...,{'title': 'Costume worn by Nona Hendryx of Lab...
8970979,https://3d-api.si.edu/content/document/3d_pack...,smithsonian,Creative Commons Zero v1.0 Universal,glb,afe61716ac7d091817e95a576f460aa10f95c5b6a0911c...,{'title': 'George Washington'}

In [6]:
annotations["keys"] = annotations["metadata"].apply(lambda info: list(info.keys()))

In [7]:
annotations[["keys"]].explode("keys")["keys"].unique()

array([nan, 'filename', 'title'], dtype=object)

In [8]:
uids = objaverse.load_uids()

In [9]:
len(uids)

798759

In [ ]:
#It breaks since it tries to download everything into home dir
objaverse.load_annotations()

# Loading into another dir

In [10]:
import glob
import gzip
import json
import multiprocessing
import os
import urllib.request
import warnings
from typing import Any, Dict, List, Optional, Tuple

from tqdm import tqdm

BASE_PATH = "/vol/isy-rl/dtrofimov/data/objaverse"#os.path.join(os.path.expanduser("~"), ".objaverse")

__version__ = "<REPLACE_WITH_VERSION>"
_VERSIONED_PATH = os.path.join(BASE_PATH, "hf-objaverse-v1")


def load_annotations(uids: Optional[List[str]] = None) -> Dict[str, Any]:
    """Load the full metadata of all objects in the dataset.

    Args:
        uids: A list of uids with which to load metadata. If None, it loads
        the metadata for all uids.

    Returns:
        A dictionary mapping the uid to the metadata.
    """
    metadata_path = os.path.join(_VERSIONED_PATH, "metadata")
    object_paths = _load_object_paths()
    dir_ids = (
        set(object_paths[uid].split("/")[1] for uid in uids)
        if uids is not None
        else [f"{i // 1000:03d}-{i % 1000:03d}" for i in range(160)]
    )
    if len(dir_ids) > 10:
        dir_ids = tqdm(dir_ids)
    out = {}
    for i_id in dir_ids:
        json_file = f"{i_id}.json.gz"
        local_path = os.path.join(metadata_path, json_file)
        if not os.path.exists(local_path):
            hf_url = f"https://huggingface.co/datasets/allenai/objaverse/resolve/main/metadata/{i_id}.json.gz"
            # wget the file and put it in local_path
            os.makedirs(os.path.dirname(local_path), exist_ok=True)
            urllib.request.urlretrieve(hf_url, local_path)
        with gzip.open(local_path, "rb") as f:
            data = json.load(f)
        if uids is not None:
            data = {uid: data[uid] for uid in uids if uid in data}
        out.update(data)
        if uids is not None and len(out) == len(uids):
            break
    return out

def _load_object_paths() -> Dict[str, str]:
    """Load the object paths from the dataset.

    The object paths specify the location of where the object is located
    in the Hugging Face repo.

    Returns:
        A dictionary mapping the uid to the object path.
    """
    object_paths_file = "object-paths.json.gz"
    local_path = os.path.join(_VERSIONED_PATH, object_paths_file)
    if not os.path.exists(local_path):
        hf_url = f"https://huggingface.co/datasets/allenai/objaverse/resolve/main/{object_paths_file}"
        # wget the file and put it in local_path
        os.makedirs(os.path.dirname(local_path), exist_ok=True)
        urllib.request.urlretrieve(hf_url, local_path)
    with gzip.open(local_path, "rb") as f:
        object_paths = json.load(f)
    return object_paths

In [11]:
all_annotations = load_annotations(uids)

 99%|██████████████████████████████████████████████████████████▋| 159/160 [01:21<00:00,  1.95it/s]

In [12]:
categories = list(map(lambda v: list(map(lambda x: x["name"], v[1]["categories"])), all_annotations.items()))

In [13]:
len(categories)

798759

In [14]:
categories

[['electronics-gadgets'],
 [],
 [],
 [],
 ['characters-creatures', 'science-technology'],
 ['characters-creatures', 'people'],
 [],
 ['cultural-heritage-history', 'science-technology'],
 [],
 ['characters-creatures'],
 [],
 [],
 [],
 ['animals-pets', 'cars-vehicles'],
 ['nature-plants'],
 [],
 ['electronics-gadgets'],
 [],
 [],
 ['furniture-home'],
 ['cultural-heritage-history', 'nature-plants'],
 ['architecture'],
 ['characters-creatures'],
 ['weapons-military'],
 [],
 ['cultural-heritage-history'],
 [],
 ['cultural-heritage-history', 'weapons-military'],
 [],
 [],
 ['art-abstract', 'furniture-home'],
 [],
 [],
 ['art-abstract', 'characters-creatures'],
 ['electronics-gadgets', 'science-technology'],
 [],
 ['cultural-heritage-history'],
 [],
 [],
 [],
 ['architecture'],
 [],
 ['nature-plants'],
 ['architecture'],
 [],
 ['architecture'],
 ['furniture-home'],
 [],
 ['characters-creatures'],
 [],
 [],
 ['cultural-heritage-history', 'furniture-home'],
 ['architecture', 'news-politics'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['art-abstract', 'nature-plants'],
 [],
 ['cars-vehicles'],
 ['animals-pets', 'characters-creatures'],
 ['animals-pets', 'furniture-home'],
 [],
 ['cultural-heritage-history'],
 [],
 ['animals-pets', 'science-technology'],
 [],
 [],
 [],
 [],
 ['animals-pets'],
 ['animals-pets', 'characters-creatures'],
 [],
 [],
 ['architecture', 'art-abstract'],
 [],
 ['furniture-home', 'weapons-military'],
 [],
 ['places-travel'],
 [],
 ['architecture'],
 [],
 [],
 [],
 ['art-abstract', 'furniture-home'],
 [],
 [],
 ['art-abstract'],
 [],
 ['places-travel'],
 ['art-abstract', 'weapons-military'],
 [],
 [],
 [],
 [],
 [],
 ['characters-creatures', 'weapons-military'],
 [],
 [],
 ['cars-vehicles', 'nature-plants'],
 ['people'],
 ['architecture'],
 [],
 [],
 [],
 [],
 ['art-abstract'],
 ['furniture-home'],
 [],
 [],
 [],
 ['cultural-heritage-history', 'science-technology'],
 [],
 ['cultural-heritage-history'],
 [],
 ['art-abstract', 'cultural-heritage-history'],
 ['electronics-gadgets', 'science-technology'],
 ['characters-creatures'],
 [],
 [],
 ['nature-plants', 'science-technology'],
 ['architecture', 'nature-plants'],
 ['art-abstract'],
 ['architecture', 'furniture-home'],
 [],
 ['electronics-gadgets', 'sports-fitness'],
 ['architecture', 'places-travel'],
 [],
 [],
 ['cultural-heritage-history'],
 ['art-abstract'],
 [],
 [],
 ['characters-creatures'],
 [],
 [],
 ['animals-pets', 'science-technology'],
 ['art-abstract', 'characters-creatures'],
 [],
 ['animals-pets', 'characters-creatures'],
 ['weapons-military'],
 ['architecture', 'furniture-home'],
 [],
 ['architecture', 'science-technology'],
 ['furniture-home'],
 ['architecture', 'furniture-home'],
 ['art-abstract', 'characters-creatures'],
 ['electronics-gadgets', 'science-technology'],
 [],
 ['animals-pets', 'characters-creatures'],
 ['science-technology'],
 [],
 [],
 [],
 [],
 ['nature-plants'],
 ['science-technology'],
 ['architecture', 'people'],
 [],
 [],
 ['characters-creatures'],
 ['art-abstract', 'furniture-home'],
 [],
 ['furniture-home'],
 ['nature-plants', 'science-technology'],
 ['characters-creatures'],
 [],
 [],
 [],
 [],
 ['art-abstract', 'characters-creatures'],
 [],
 ['characters-creatures'],
 [],
 ['architecture', 'nature-plants'],
 [],
 ['food-drink', 'nature-plants'],
 ['art-abstract', 'nature-plants'],
 [],
 [],
 [],
 [],
 ['art-abstract', 'characters-creatures'],
 ['characters-creatures', 'science-technology'],
 [],
 [],
 ['furniture-home'],
 [],
 ['characters-creatures'],
 ['furniture-home'],
 [],
 [],
 [],
 [],
 [],
 ['architecture', 'cultural-heritage-history'],
 ['electronics-gadgets'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['nature-plants'],
 [],
 ['architecture'],
 [],
 [],
 ['architecture', 'furniture-home'],
 ['cars-vehicles', 'characters-creatures'],
 [],
 [],
 [],
 ['fashion-style'],
 [],
 ['cultural-heritage-history'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['science-technology'],
 [],
 ['art-abstract', 'cars-vehicles'],
 ['art-abstract', 'cars-vehicles'],
 ['art-abstract'],
 [],
 ['cars-vehicles', 'science-technology'],
 [],
 ['cars-vehicles'],
 ['cultural-heritage-history', 'science-technology'],
 ['characters-creatures'],
 [],
 ['electronics-gadgets', 'science-technology'],
 ['architecture'],
 ['science-technology'],
 [],
 [],
 [],
 [],
 [],
 ['architecture', 'cultural-heritage-history'],
 [],
 ['architecture', 'nature-plants'],
 [],
 ['cars-vehicles'],
 [],
 ['animals-pets', 'art-abstract'],
 [],
 [],
 ['people', 'weapons-military'],
 ['architecture', 'furniture-home'],
 [],
 [],
 [],
 [],
 ['architecture'],
 ['science-technology'],
 [],
 [],
 ['cultural-heritage-history'],
 ['architecture', 'cultural-heritage-history'],
 ['furniture-home'],
 ['architecture'],
 [],
 [],
 ['weapons-military'],
 [],
 ['architecture'],
 [],
 [],
 ['cultural-heritage-history', 'places-travel'],
 [],
 [],
 ['architecture'],
 [],
 [],
 [],
 ['characters-creatures', 'science-technology'],
 [],
 ['cultural-heritage-history', 'electronics-gadgets'],
 ['electronics-gadgets', 'science-technology'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['architecture'],
 ['architecture'],
 [],
 [],
 ['cultural-heritage-history'],
 ['people', 'sports-fitness'],
 ['art-abstract', 'weapons-military'],
 ['cars-vehicles'],
 ['furniture-home'],
 ['architecture', 'places-travel'],
 [],
 [],
 [],
 ['art-abstract', 'music'],
 [],
 [],
 ['characters-creatures', 'people'],
 ['art-abstract', 'furniture-home'],
 [],
 [],
 [],
 ['sports-fitness'],
 ['architecture'],
 [],
 ['nature-plants'],
 [],
 ['art-abstract', 'cars-vehicles'],
 [],
 ['art-abstract', 'cars-vehicles'],
 ['animals-pets', 'characters-creatures'],
 ['electronics-gadgets'],
 ['architecture'],
 [],
 ['characters-creatures', 'people'],
 [],
 ['nature-plants'],
 ['art-abstract', 'characters-creatures'],
 ['art-abstract'],
 [],
 ['characters-creatures', 'electronics-gadgets'],
 ['furniture-home'],
 [],
 [],
 [],
 [],
 ['cultural-heritage-history', 'people'],
 ['architecture'],
 ['cultural-heritage-history'],
 ['science-technology'],
 ['characters-creatures', 'places-travel'],
 [],
 ['architecture', 'cultural-heritage-history'],
 ['animals-pets', 'art-abstract'],
 ['characters-creatures', 'people'],
 [],
 ['characters-creatures'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['art-abstract'],
 ['cultural-heritage-history'],
 ['characters-creatures', 'electronics-gadgets'],
 [],
 [],
 [],
 [],
 [],
 ['nature-plants'],
 [],
 [],
 ['nature-plants', 'science-technology'],
 [],
 ['architecture', 'art-abstract'],
 ['science-technology', 'weapons-military'],
 ['electronics-gadgets', 'food-drink'],
 ['architecture'],
 ['architecture'],
 [],
 ['characters-creatures'],
 [],
 ['art-abstract'],
 [],
 [],
 ['animals-pets', 'characters-creatures'],
 [],
 ['weapons-military'],
 [],
 [],
 ['architecture'],
 ['architecture'],
 ['architecture', 'cultural-heritage-history'],
 ['art-abstract', 'characters-creatures'],
 [],
 ['cultural-heritage-history', 'people'],
 ['furniture-home'],
 ['characters-creatures', 'fashion-style'],
 [],
 ['people'],
 [],
 ['electronics-gadgets'],
 [],
 ['cultural-heritage-history'],
 ['architecture', 'art-abstract'],
 [],
 [],
 [],
 ['art-abstract', 'cultural-heritage-history'],
 ['cars-vehicles'],
 [],
 [],
 [],
 ['animals-pets', 'nature-plants'],
 ['cars-vehicles'],
 ['architecture', 'furniture-home'],
 [],
 [],
 [],
 ['art-abstract', 'cultural-heritage-history'],
 [],
 ['architecture'],
 [],
 ['art-abstract'],
 [],
 ['art-abstract', 'cultural-heritage-history'],
 [],
 ['art-abstract', 'nature-plants'],
 ['cultural-heritage-history'],
 ['weapons-military'],
 [],
 ['characters-creatures'],
 [],
 ['architecture'],
 [],
 ['cars-vehicles'],
 ['cultural-heritage-history', 'weapons-military'],
 ['nature-plants', 'places-travel'],
 [],
 ['cars-vehicles', 'cultural-heritage-history'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['art-abstract'],
 [],
 ['cultural-heritage-history'],
 ['cars-vehicles'],
 [],
 [],
 [],
 ['architecture', 'furniture-home'],
 [],
 [],
 ['nature-plants', 'places-travel'],
 ['places-travel', 'sports-fitness'],
 [],
 ['weapons-military'],
 [],
 ['weapons-military'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['art-abstract'],
 [],
 [],
 ['art-abstract'],
 ['art-abstract', 'science-technology'],
 ['cars-vehicles'],
 ['weapons-military'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['cultural-heritage-history', 'furniture-home'],
 ['cultural-heritage-history', 'weapons-military'],
 ['art-abstract', 'furniture-home'],
 ['art-abstract'],
 [],
 ['weapons-military'],
 [],
 [],
 ['characters-creatures'],
 [],
 [],
 [],
 [],
 [],
 ['architecture'],
 [],
 ['art-abstract', 'nature-plants'],
 ['people'],
 [],
 ['nature-plants', 'science-technology'],
 [],
 ['furniture-home'],
 ['architecture', 'cultural-heritage-history'],
 [],
 ['cars-vehicles'],
 ['architecture', 'art-abstract'],
 ['architecture'],
 [],
 ['architecture', 'art-abstract'],
 ['architecture', 'art-abstract'],
 ['characters-creatures'],
 ['cars-vehicles'],
 [],
 ['characters-creatures', 'electronics-gadgets'],
 ['cultural-heritage-history', 'science-technology'],
 [],
 [],
 [],
 [],
 ['animals-pets', 'science-technology'],
 ['art-abstract', 'characters-creatures'],
 ['cultural-heritage-history'],
 ['architecture', 'furniture-home'],
 [],
 [],
 ['cultural-heritage-history'],
 ['characters-creatures', 'furniture-home'],
 ['cultural-heritage-history'],
 [],
 [],
 ['furniture-home'],
 [],
 ['architecture', 'science-technology'],
 ['weapons-military'],
 ['architecture'],
 ['characters-creatures'],
 [],
 [],
 ['characters-creatures', 'weapons-military'],
 ['characters-creatures', 'people'],
 [],
 [],
 [],
 [],
 [],
 ['electronics-gadgets', 'places-travel'],
 [],
 ['cultural-heritage-history', 'places-travel'],
 ['cultural-heritage-history'],
 [],
 ['electronics-gadgets', 'furniture-home'],
 ['cars-vehicles', 'cultural-heritage-history'],
 ['furniture-home'],
 [],
 [],
 [],
 [],
 ['architecture'],
 ['art-abstract'],
 [],
 [],
 [],
 ['art-abstract', 'characters-creatures'],
 [],
 [],
 ['cultural-heritage-history'],
 [],
 [],
 [],
 ['cultural-heritage-history', 'people'],
 ['people'],
 ['nature-plants', 'science-technology'],
 ['food-drink', 'nature-plants'],
 [],
 ['electronics-gadgets', 'science-technology'],
 ['art-abstract'],
 ['cars-vehicles', 'science-technology'],
 ['fashion-style'],
 [],
 [],
 [],
 ['architecture', 'furniture-home'],
 [],
 ['architecture', 'cultural-heritage-history'],
 ['people'],
 ['art-abstract'],
 ['cars-vehicles'],
 [],
 ['furniture-home'],
 [],
 ['furniture-home'],
 ['nature-plants'],
 [],
 [],
 ['art-abstract'],
 [],
 ['nature-plants'],
 ['furniture-home'],
 ['art-abstract'],
 [],
 ['art-abstract', 'cultural-heritage-history'],
 [],
 ['nature-plants'],
 [],
 [],
 [],
 ['characters-creatures'],
 ['food-drink', 'nature-plants'],
 [],
 [],
 [],
 ['art-abstract', 'nature-plants'],
 [],
 ['fashion-style', 'sports-fitness'],
 [],
 [],
 ['characters-creatures', 'weapons-military'],
 ['animals-pets', 'art-abstract'],
 ['characters-creatures'],
 [],
 ['architecture', 'cultural-heritage-history'],
 [],
 [],
 [],
 ['weapons-military'],
 ['architecture', 'furniture-home'],
 [],
 ['cultural-heritage-history'],
 [],
 ['cars-vehicles'],
 [],
 [],
 [],
 [],
 [],
 ['cultural-heritage-history', 'science-technology'],
 ['architecture', 'weapons-military'],
 ['furniture-home'],
 ['weapons-military'],
 ['cultural-heritage-history', 'science-technology'],
 ['cars-vehicles'],
 [],
 [],
 [],
 [],
 ['cultural-heritage-history'],
 [],
 ['characters-creatures', 'people'],
 [],
 [],
 ['characters-creatures'],
 ['nature-plants', 'science-technology'],
 [],
 ['characters-creatures'],
 ['cars-vehicles'],
 [],
 [],
 [],
 [],
 ['electronics-gadgets'],
 [],
 [],
 ['characters-creatures'],
 [],
 [],
 ['furniture-home', 'nature-plants'],
 ['art-abstract'],
 ['cars-vehicles', 'electronics-gadgets'],
 ['science-technology'],
 [],
 ['architecture'],
 [],
 ['food-drink'],
 ['cars-vehicles', 'cultural-heritage-history'],
 ['characters-creatures', 'weapons-military'],
 ['weapons-military'],
 [],
 ['characters-creatures', 'weapons-military'],
 [],
 [],
 [],
 ['cultural-heritage-history', 'places-travel'],
 ['places-travel', 'science-technology'],
 [],
 ['architecture', 'furniture-home'],
 [],
 ['furniture-home'],
 [],
 [],
 ['animals-pets', 'characters-creatures'],
 ['nature-plants'],
 [],
 ['science-technology'],
 [],
 [],
 ['furniture-home'],
 [],
 [],
 [],
 ['architecture', 'weapons-military'],
 [],
 [],
 [],
 [],
 ['characters-creatures'],
 ['electronics-gadgets', 'science-technology'],
 ['weapons-military'],
 ['art-abstract', 'fashion-style'],
 ['architecture', 'art-abstract'],
 [],
 [],
 ['cultural-heritage-history'],
 [],
 [],
 ['architecture', 'places-travel'],
 ['architecture', 'science-technology'],
 ['music', 'people'],
 ['characters-creatures'],
 [],
 ['furniture-home'],
 ['art-abstract'],
 ['animals-pets', 'characters-creatures'],
 ['weapons-military'],
 ['characters-creatures', 'weapons-military'],
 ['architecture', 'cultural-heritage-history'],
 [],
 [],
 ['characters-creatures'],
 ['architecture'],
 [],
 ['cultural-heritage-history', 'furniture-home'],
 ['cultural-heritage-history', 'science-technology'],
 [],
 ['electronics-gadgets', 'music'],
 ['characters-creatures'],
 ['characters-creatures'],
 [],
 [],
 [],
 ['weapons-military'],
 ['architecture', 'cars-vehicles'],
 [],
 ['cars-vehicles', 'weapons-military'],
 ['art-abstract', 'science-technology'],
 [],
 ['characters-creatures'],
 [],
 [],
 ['architecture'],
 ['art-abstract', 'food-drink'],
 ['architecture'],
 ['animals-pets', 'art-abstract'],
 [],
 [],
 [],
 [],
 [],
 ['architecture'],
 [],
 [],
 [],
 [],
 ['animals-pets', 'art-abstract'],
 [],
 ['architecture', 'places-travel'],
 [],
 [],
 [],
 ['architecture', 'cultural-heritage-history'],
 ['science-technology'],
 [],
 [],
 ['weapons-military'],
 ['architecture', 'cultural-heritage-history'],
 ['cultural-heritage-history'],
 [],
 ['nature-plants', 'places-travel'],
 ['cultural-heritage-history', 'weapons-military'],
 [],
 ['animals-pets'],
 [],
 [],
 [],
 ['architecture'],
 [],
 ['food-drink'],
 ['furniture-home'],
 [],
 [],
 [],
 [],
 ['architecture'],
 ['cars-vehicles'],
 [],
 ['architecture', 'furniture-home'],
 ['weapons-military'],
 [],
 ['architecture'],
 [],
 [],
 [],
 [],
 ['architecture'],
 ['science-technology'],
 [],
 ['architecture', 'art-abstract'],
 [],
 [],
 [],
 ['nature-plants', 'science-technology'],
 ['cultural-heritage-history'],
 ['animals-pets', 'nature-plants'],
 [],
 ['art-abstract', 'science-technology'],
 ['architecture', 'cultural-heritage-history'],
 [],
 ['cultural-heritage-history'],
 [],
 [],
 [],
 ['weapons-military'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['animals-pets', 'art-abstract'],
 [],
 ['furniture-home'],
 [],
 [],
 [],
 [],
 [],
 ['science-technology'],
 ['characters-creatures', 'science-technology'],
 ['animals-pets'],
 ['nature-plants'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['cultural-heritage-history'],
 [],
 ['characters-creatures', 'weapons-military'],
 ['art-abstract', 'places-travel'],
 [],
 ['animals-pets'],
 [],
 ['architecture', 'cultural-heritage-history'],
 [],
 ['art-abstract'],
 [],
 [],
 [],
 ['art-abstract', 'cultural-heritage-history'],
 ['art-abstract'],
 [],
 [],
 ['architecture'],
 [],
 ['cars-vehicles'],
 [],
 [],
 ['characters-creatures'],
 ['architecture'],
 [],
 ['art-abstract', 'characters-creatures'],
 [],
 ['cultural-heritage-history'],
 ['electronics-gadgets', 'weapons-military'],
 [],
 ['electronics-gadgets', 'furniture-home'],
 ['art-abstract'],
 [],
 [],
 ['furniture-home', 'people'],
 ['fashion-style'],
 ['characters-creatures'],
 [],
 [],
 ['art-abstract', 'people'],
 ['furniture-home'],
 ['cultural-heritage-history'],
 [],
 ['animals-pets', 'nature-plants'],
 ['places-travel', 'science-technology'],
 ['characters-creatures'],
 ['weapons-military'],
 ['weapons-military'],
 [],
 ['science-technology'],
 [],
 ['cars-vehicles', 'weapons-military'],
 ['electronics-gadgets'],
 [],
 [],
 ['architecture', 'places-travel'],
 [],
 [],
 ['furniture-home'],
 [],
 ['characters-creatures'],
 [],
 ['animals-pets', 'characters-creatures'],
 ['animals-pets'],
 ['characters-creatures'],
 ['weapons-military'],
 [],
 ['architecture'],
 ['furniture-home', 'people'],
 ['furniture-home', 'weapons-military'],
 [],
 [],
 [],
 [],
 ['furniture-home'],
 ['cultural-heritage-history', 'weapons-military'],
 [],
 [],
 [],
 ['electronics-gadgets'],
 [],
 ['characters-creatures'],
 ['architecture', 'art-abstract'],
 ['art-abstract', 'cultural-heritage-history'],
 ['electronics-gadgets', 'music'],
 [],
 ['electronics-gadgets', 'weapons-military'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['characters-creatures'],
 ['architecture', 'furniture-home'],
 [],
 [],
 ['architecture', 'furniture-home'],
 ['art-abstract', 'places-travel'],
 [],
 ['animals-pets', 'characters-creatures'],
 [],
 [],
 [],
 [],
 ['architecture'],
 [],
 ['nature-plants'],
 [],
 [],
 [],
 [],
 ['architecture', 'art-abstract'],
 ['characters-creatures'],
 ['cars-vehicles'],
 [],
 ['furniture-home'],
 ['art-abstract', 'weapons-military'],
 [],
 ['furniture-home'],
 [],
 ['music'],
 ['art-abstract', 'cultural-heritage-history'],
 ['animals-pets', 'nature-plants'],
 [],
 ['characters-creatures', 'people'],
 [],
 ['architecture'],
 ['characters-creatures'],
 ['furniture-home'],
 [],
 ['nature-plants', 'places-travel'],
 [],
 [],
 [],
 ['art-abstract'],
 ['architecture'],
 [],
 ['cars-vehicles'],
 [],
 ['characters-creatures'],
 [],
 [],
 [],
 [],
 ['nature-plants'],
 [],
 ['art-abstract', 'weapons-military'],
 ['architecture', 'cultural-heritage-history'],
 ...]

In [15]:
from itertools import chain

In [16]:
categories = list(chain(*categories))

In [17]:
df_categ = pd.DataFrame({"categories": categories})

In [18]:
df_categ.groupby("categories", as_index=False).count()

                   categories
0                animals-pets
1                architecture
2                art-abstract
3               cars-vehicles
4        characters-creatures
5   cultural-heritage-history
6         electronics-gadgets
7               fashion-style
8                  food-drink
9              furniture-home
10                      music
11              nature-plants
12              news-politics
13                     people
14              places-travel
15         science-technology
16             sports-fitness
17           weapons-military

In [38]:
all_annotations.popitem()

('a7ba6418fee74f83b7bb72d09a3763ff',
 {'uri': 'https://api.sketchfab.com/v3/models/a7ba6418fee74f83b7bb72d09a3763ff',
  'uid': 'a7ba6418fee74f83b7bb72d09a3763ff',
  'name': 'Elote',
  'staffpickedAt': None,
  'viewCount': 115,
  'likeCount': 1,
  'animationCount': 0,
  'viewerUrl': 'https://sketchfab.com/3d-models/a7ba6418fee74f83b7bb72d09a3763ff',
  'embedUrl': 'https://sketchfab.com/models/a7ba6418fee74f83b7bb72d09a3763ff/embed',
  'commentCount': 0,
  'isDownloadable': True,
  'publishedAt': '2019-03-22T08:01:28.076422',
  'tags': [],
  'categories': [{'name': 'characters-creatures'}, {'name': 'nature-plants'}],
  'thumbnails': {'images': [{'uid': 'e229970d3df34cfcb13f6f06e083b1ea',
     'size': 16549,
     'width': 720,
     'url': 'https://media.sketchfab.com/models/a7ba6418fee74f83b7bb72d09a3763ff/thumbnails/eb7ef8aedef248458caf19b2d18746c1/0074ca69629e4fbdae103ecde0c6edc6.jpeg',
     'height': 405},
    {'uid': 'f664d67c21204ca7bb26d3271ad493ee',
     'size': 65460,
     'width': 1920,
     'url': 'https://media.sketchfab.com/models/a7ba6418fee74f83b7bb72d09a3763ff/thumbnails/eb7ef8aedef248458caf19b2d18746c1/7e748dcd993a49fb84b33f07485542e3.jpeg',
     'height': 1080},
    {'uid': 'f2311f547ae8400ba748f7a42f0ddcbf',
     'size': 26237,
     'width': 1024,
     'url': 'https://media.sketchfab.com/models/a7ba6418fee74f83b7bb72d09a3763ff/thumbnails/eb7ef8aedef248458caf19b2d18746c1/1be93c1f1106447d99bf8315a333a27d.jpeg',
     'height': 576},
    {'uid': '5170aa8b56cf4420a8991ef76b38593b',
     'size': 4189,
     'width': 256,
     'url': 'https://media.sketchfab.com/models/a7ba6418fee74f83b7bb72d09a3763ff/thumbnails/eb7ef8aedef248458caf19b2d18746c1/4e9265c6ca8d4b6b994acae888f72144.jpeg',
     'height': 144},
    {'uid': '4e88ebe3774f461ca237c2f593db5c2d',
     'size': 825,
     'width': 64,
     'url': 'https://media.sketchfab.com/models/a7ba6418fee74f83b7bb72d09a3763ff/thumbnails/eb7ef8aedef248458caf19b2d18746c1/0177a47df9164edbb99afa3484c8c8e1.jpeg',
     'height': 36}]},
  'user': {'uid': '70974b0842a846a38f8084f923e99305',
   'username': 'Elbolilloduro',
   'displayName': 'Elbolillo',
   'profileUrl': 'https://sketchfab.com/Elbolilloduro',
   'account': 'basic',
   'avatar': {'uri': 'https://api.sketchfab.com/v3/avatars/e48b274ec13245d3ab9d93f98be23857',
    'images': [{'size': 1624,
      'width': 32,
      'url': 'https://media.sketchfab.com/avatars/e48b274ec13245d3ab9d93f98be23857/31e3d0bffb7b4b06a7aed9368111611c.png',
      'height': 32},
     {'size': 2870,
      'width': 48,
      'url': 'https://media.sketchfab.com/avatars/e48b274ec13245d3ab9d93f98be23857/42403094edb040ccaa4e8af969392421.png',
      'height': 48},
     {'size': 7347,
      'width': 90,
      'url': 'https://media.sketchfab.com/avatars/e48b274ec13245d3ab9d93f98be23857/f51b725efa56431a82b44afcf6600b1e.png',
      'height': 90},
     {'size': 8498,
      'width': 100,
      'url': 'https://media.sketchfab.com/avatars/e48b274ec13245d3ab9d93f98be23857/d286d5e24775430ea365fe7a035d091b.png',
      'height': 100}]},
   'uri': 'https://api.sketchfab.com/v3/users/70974b0842a846a38f8084f923e99305'},
  'description': '',
  'faceCount': 1442,
  'createdAt': '2019-03-22T07:52:09.313290',
  'vertexCount': 731,
  'isAgeRestricted': False,
  'archives': {'glb': {'textureCount': 0,
    'size': 127040,
    'type': 'glb',
    'textureMaxResolution': 0,
    'faceCount': 1442,
    'vertexCount': 4220},
   'gltf': {'textureCount': 0,
    'size': 37166,
    'type': 'gltf',
    'textureMaxResolution': 0,
    'faceCount': 1442,
    'vertexCount': 4220},
   'source': {'textureCount': None,
    'size': 115680,
    'type': 'source',
    'textureMaxResolution': None,
    'faceCount': None,
    'vertexCount': None},
   'usdz': {'textureCount': None,
    'size': 111856,
    'type': 'usdz',
    'textureMaxResolution': None,
    'faceCount': None,
    'vertexCount': None}},
  'license': 'by'})

In [43]:
annotations[annotations["fileIdentifier"] == "https://sketchfab.com/3d-models/a7ba6418fee74f83b7bb72d09a3763ff"]

,fileIdentifier,source,license,fileType,sha256,metadata
9454162,https://sketchfab.com/3d-models/a7ba6418fee74f...,sketchfab,Creative Commons - Attribution,glb,882f8fcf9b4fd3949a34e371a84efa311809fd98d6bd8c...,{}

In [19]:
def filter_ann(annotations: dict, name: str) -> dict:
    return dict(filter(lambda item: name in item[1]["name"].lower(), annotations.items()))

In [20]:
teapots_ann = filter_ann(all_annotations, "teapot")

In [21]:
teapots_ann.popitem()

('af9aa36d163d4b3b895696a0e930095e',
 {'uri': 'https://api.sketchfab.com/v3/models/af9aa36d163d4b3b895696a0e930095e',
  'uid': 'af9aa36d163d4b3b895696a0e930095e',
  'name': 'Tetera de plata / Silver teapot',
  'staffpickedAt': None,
  'viewCount': 35,
  'likeCount': 0,
  'animationCount': 0,
  'viewerUrl': 'https://sketchfab.com/3d-models/af9aa36d163d4b3b895696a0e930095e',
  'embedUrl': 'https://sketchfab.com/models/af9aa36d163d4b3b895696a0e930095e/embed',
  'commentCount': 0,
  'isDownloadable': True,
  'publishedAt': '2021-06-17T03:06:24.786168',
  'tags': [{'name': 'teapot',
    'slug': 'teapot',
    'uri': 'https://api.sketchfab.com/v3/tags/teapot'},
   {'name': 'tete',
    'slug': 'tete',
    'uri': 'https://api.sketchfab.com/v3/tags/tete'},
   {'name': 'silver',
    'slug': 'silver',
    'uri': 'https://api.sketchfab.com/v3/tags/silver'},
   {'name': 'plata',
    'slug': 'plata',
    'uri': 'https://api.sketchfab.com/v3/tags/plata'},
   {'name': 'sterling',
    'slug': 'sterling',
    'uri': 'https://api.sketchfab.com/v3/tags/sterling'},
   {'name': 'metashape',
    'slug': 'metashape',
    'uri': 'https://api.sketchfab.com/v3/tags/metashape'},
   {'name': 'photogrammetry',
    'slug': 'photogrammetry',
    'uri': 'https://api.sketchfab.com/v3/tags/photogrammetry'}],
  'categories': [{'name': 'art-abstract'},
   {'name': 'cultural-heritage-history'}],
  'thumbnails': {'images': [{'uid': '527b10ba334d4015b061a655a4667695',
     'size': 396814,
     'width': 1920,
     'url': 'https://media.sketchfab.com/models/af9aa36d163d4b3b895696a0e930095e/thumbnails/1641dd960429412f989dd70a786d1d78/ec61b8a360224ce8b3089af9de1f4fa7.jpeg',
     'height': 1080},
    {'uid': '8755b2e9147a431a89ec6c6ea1b3cbf2',
     'size': 55368,
     'width': 1024,
     'url': 'https://media.sketchfab.com/models/af9aa36d163d4b3b895696a0e930095e/thumbnails/1641dd960429412f989dd70a786d1d78/bc6f481c444e45b6bfee6bc0185adc25.jpeg',
     'height': 576},
    {'uid': 'cf60802bb69847c2be997acfe99e7354',
     'size': 23786,
     'width': 720,
     'url': 'https://media.sketchfab.com/models/af9aa36d163d4b3b895696a0e930095e/thumbnails/1641dd960429412f989dd70a786d1d78/d2075b3451fe488ab2b59212a4657249.jpeg',
     'height': 405},
    {'uid': '65c6f74b24f34e1a800f7a8b1ef80459',
     'size': 3838,
     'width': 256,
     'url': 'https://media.sketchfab.com/models/af9aa36d163d4b3b895696a0e930095e/thumbnails/1641dd960429412f989dd70a786d1d78/f956829b009b437cbd6d3d351f45347f.jpeg',
     'height': 144},
    {'uid': 'b12329cdeddd4a768a07393513995d5b',
     'size': 1048,
     'width': 64,
     'url': 'https://media.sketchfab.com/models/af9aa36d163d4b3b895696a0e930095e/thumbnails/1641dd960429412f989dd70a786d1d78/c595359fc5f34940aa9e0f158913b661.jpeg',
     'height': 36}]},
  'user': {'uid': '52fe2279f2a849a2907319b7c7423602',
   'username': 'SergioSan',
   'displayName': 'Museum_Thievery',
   'profileUrl': 'https://sketchfab.com/SergioSan',
   'account': 'basic',
   'avatar': {'uri': 'https://api.sketchfab.com/v3/avatars/6e33be29a2704a349ce09fe5bcc0b3b5',
    'images': [{'size': 3677,
      'width': 100,
      'url': 'https://media.sketchfab.com/avatars/6e33be29a2704a349ce09fe5bcc0b3b5/36bddcb3d9be42619f69ab4fd82b97d4.jpeg',
      'height': 100},
     {'size': 3078,
      'width': 90,
      'url': 'https://media.sketchfab.com/avatars/6e33be29a2704a349ce09fe5bcc0b3b5/b99d5d3aff3944b885ed628d3579e196.jpeg',
      'height': 90},
     {'size': 1237,
      'width': 48,
      'url': 'https://media.sketchfab.com/avatars/6e33be29a2704a349ce09fe5bcc0b3b5/10e337e38013446abcccf1bd90cc5f1f.jpeg',
      'height': 48},
     {'size': 777,
      'width': 32,
      'url': 'https://media.sketchfab.com/avatars/6e33be29a2704a349ce09fe5bcc0b3b5/029391a7d72d48e2a8955143248f5d2f.jpeg',
      'height': 32}]},
   'uri': 'https://api.sketchfab.com/v3/users/52fe2279f2a849a2907319b7c7423602'},
  'description': 'Tetera de plata antigua\n\nFotografías tomadas por Roxy Ríos',
  'faceCount': 10000,
  'createdAt': '2021-06-17T02:02:06.455667',
  'vertexCount': 5002,
  'isAgeRestricted': False,
  'archives': {'glb': {'textureCount': 3,
    'size': 31960232,
    'type': 'glb',
    'textureMaxResolution': 4096,
    'faceCount': 9996,
    'vertexCount': 5679},
   'gltf': {'textureCount': 3,
    'size': 31758618,
    'type': 'gltf',
    'textureMaxResolution': 4096,
    'faceCount': 9996,
    'vertexCount': 5679},
   'source': {'textureCount': None,
    'size': 62758684,
    'type': 'source',
    'textureMaxResolution': None,
    'faceCount': None,
    'vertexCount': None},
   'usdz': {'textureCount': None,
    'size': 2998802,
    'type': 'usdz',
    'textureMaxResolution': None,
    'faceCount': None,
    'vertexCount': None}},
  'license': 'by'})

In [22]:
# for the scenes
# TODO add more scenes with easily discovered objects like teapot
objects_to_filter = {
    "poster": ["chair", "poster", "frame", "artwork"],
    "kitchen": ["monitor", "piano", "bulb", "lamp", "table", "toaster", "oven", "fridge", "sink", "plate", "spoon"],
    "stump": ["head", "monitor", "chair", "log", "branch", "bench"],
    "others": ["bookshelf", "bottle", "bowl", "cup", "desk", "door", "keyboard", "lamp", "laptop", "stool",
              "teapot", "microwave", "bed", "sofa", "wardrobe", "rug", "curtains", "mirror", "clock"]
}

In [23]:
def filter_many(annotations: dict, names: list) -> dict:
    result = {}
    for name in names:
        result.update(filter_ann(annotations, name))
    return result

In [24]:
filtered_objects = filter_many(all_annotations, list(chain(*list(objects_to_filter.values()))))

In [85]:
filtered_objects.popitem()

('5af99db17fb645bba7e55ace9e7b6b34',
 {'uri': 'https://api.sketchfab.com/v3/models/5af99db17fb645bba7e55ace9e7b6b34',
  'uid': '5af99db17fb645bba7e55ace9e7b6b34',
  'name': 'Microwave Oven',
  'staffpickedAt': None,
  'viewCount': 3134,
  'likeCount': 69,
  'animationCount': 0,
  'viewerUrl': 'https://sketchfab.com/3d-models/5af99db17fb645bba7e55ace9e7b6b34',
  'embedUrl': 'https://sketchfab.com/models/5af99db17fb645bba7e55ace9e7b6b34/embed',
  'commentCount': 2,
  'isDownloadable': True,
  'publishedAt': '2020-03-26T15:00:11.735732',
  'tags': [{'name': 'microwave',
    'slug': 'microwave',
    'uri': 'https://api.sketchfab.com/v3/tags/microwave'},
   {'name': 'dirty',
    'slug': 'dirty',
    'uri': 'https://api.sketchfab.com/v3/tags/dirty'},
   {'name': 'appliance',
    'slug': 'appliance',
    'uri': 'https://api.sketchfab.com/v3/tags/appliance'},
   {'name': 'old',
    'slug': 'old',
    'uri': 'https://api.sketchfab.com/v3/tags/old'},
   {'name': 'microwave-oven',
    'slug': 'microwave-oven',
    'uri': 'https://api.sketchfab.com/v3/tags/microwave-oven'},
   {'name': 'substancepainter',
    'slug': 'substancepainter',
    'uri': 'https://api.sketchfab.com/v3/tags/substancepainter'},
   {'name': 'substance',
    'slug': 'substance',
    'uri': 'https://api.sketchfab.com/v3/tags/substance'},
   {'name': 'free',
    'slug': 'free',
    'uri': 'https://api.sketchfab.com/v3/tags/free'}],
  'categories': [{'name': 'electronics-gadgets'}],
  'thumbnails': {'images': [{'uid': '83edb1984002492f8645a953791bacf2',
     'size': 197770,
     'width': 1920,
     'url': 'https://media.sketchfab.com/models/5af99db17fb645bba7e55ace9e7b6b34/thumbnails/2e2aa869a9bb47aeaea3c4ff11003b3c/e5bab5fc907c4f8bb470e1a50a1f926f.jpeg',
     'height': 1080},
    {'uid': '7d1a7c0d70be4d9d8d7cbbf802c05497',
     'size': 31636,
     'width': 1024,
     'url': 'https://media.sketchfab.com/models/5af99db17fb645bba7e55ace9e7b6b34/thumbnails/2e2aa869a9bb47aeaea3c4ff11003b3c/59c2cf0413dc45feae3d68e7bcb60eaf.jpeg',
     'height': 576},
    {'uid': 'ecae6c120f2246e6b37989677eb9fec2',
     'size': 18682,
     'width': 720,
     'url': 'https://media.sketchfab.com/models/5af99db17fb645bba7e55ace9e7b6b34/thumbnails/2e2aa869a9bb47aeaea3c4ff11003b3c/97af88aeded34100829277962d0c3b2b.jpeg',
     'height': 405},
    {'uid': 'e1e6026e0f0f4f15ae22c24e99d87a75',
     'size': 4299,
     'width': 256,
     'url': 'https://media.sketchfab.com/models/5af99db17fb645bba7e55ace9e7b6b34/thumbnails/2e2aa869a9bb47aeaea3c4ff11003b3c/0e246aef875f4322a59eb4248c0e6e3d.jpeg',
     'height': 144},
    {'uid': '60ca29ac8ea24cf6b3dd5dc8b2d770c5',
     'size': 873,
     'width': 64,
     'url': 'https://media.sketchfab.com/models/5af99db17fb645bba7e55ace9e7b6b34/thumbnails/2e2aa869a9bb47aeaea3c4ff11003b3c/967c52d0a8174993a5f3d8a94f03c083.jpeg',
     'height': 36}]},
  'user': {'uid': '42eeacfc200a45e389abe45963de196e',
   'username': 'aqpetteri',
   'displayName': 'aqpetteri',
   'profileUrl': 'https://sketchfab.com/aqpetteri',
   'account': 'basic',
   'avatar': {'uri': 'https://api.sketchfab.com/v3/avatars/ff9cb6343d2b4ec5b389fca3cefd126a',
    'images': [{'size': 667,
      'width': 32,
      'url': 'https://media.sketchfab.com/avatars/ff9cb6343d2b4ec5b389fca3cefd126a/62fb098a9d944ec1984587a3662dd651.jpeg',
      'height': 32},
     {'size': 952,
      'width': 48,
      'url': 'https://media.sketchfab.com/avatars/ff9cb6343d2b4ec5b389fca3cefd126a/f6daef9d7e9a4de79446a401b11a38c1.jpeg',
      'height': 48},
     {'size': 1928,
      'width': 90,
      'url': 'https://media.sketchfab.com/avatars/ff9cb6343d2b4ec5b389fca3cefd126a/c901c837ea994373912ceebcec225cba.jpeg',
      'height': 90},
     {'size': 2156,
      'width': 100,
      'url': 'https://media.sketchfab.com/avatars/ff9cb6343d2b4ec5b389fca3cefd126a/449e63f5fada451abe4822c9c12f1bc4.jpeg',
      'height': 100}]},
   'uri': 'https://api.sketchfab.com/v3/users/42eeacfc200a45e389abe45963de196e'},
  'description': 'Simple lowpoly microwave oven asset with 4K PBR textures from an old project. I wanted to give this away for free if someone has use for it.',
  'faceCount': 1335,
  'createdAt': '2020-03-26T14:32:06.065632',
  'vertexCount': 757,
  'isAgeRestricted': False,
  'archives': {'glb': {'textureCount': 4,
    'size': 25107524,
    'type': 'glb',
    'textureMaxResolution': 4096,
    'faceCount': 1335,
    'vertexCount': 1420},
   'gltf': {'textureCount': 4,
    'size': 24770499,
    'type': 'gltf',
    'textureMaxResolution': 4096,
    'faceCount': 1335,
    'vertexCount': 1420},
   'source': {'textureCount': None,
    'size': 33898914,
    'type': 'source',
    'textureMaxResolution': None,
    'faceCount': None,
    'vertexCount': None},
   'usdz': {'textureCount': None,
    'size': 3510793,
    'type': 'usdz',
    'textureMaxResolution': None,
    'faceCount': None,
    'vertexCount': None}},
  'license': 'by'})

In [89]:
1000 * 10 / 1024

9.765625

In [28]:
filtered_objects['fe07d29f80cf4985a7e0c3e49bcc638c']

{'uri': 'https://api.sketchfab.com/v3/models/fe07d29f80cf4985a7e0c3e49bcc638c',
 'uid': 'fe07d29f80cf4985a7e0c3e49bcc638c',
 'name': 'FNAF Chair',
 'staffpickedAt': None,
 'viewCount': 277,
 'likeCount': 3,
 'animationCount': 0,
 'viewerUrl': 'https://sketchfab.com/3d-models/fe07d29f80cf4985a7e0c3e49bcc638c',
 'embedUrl': 'https://sketchfab.com/models/fe07d29f80cf4985a7e0c3e49bcc638c/embed',
 'commentCount': 0,
 'isDownloadable': True,
 'publishedAt': '2019-05-27T02:17:26.384858',
 'tags': [{'name': 'chairs',
   'slug': 'chairs',
   'uri': 'https://api.sketchfab.com/v3/tags/chairs'},
  {'name': 'fnaf',
   'slug': 'fnaf',
   'uri': 'https://api.sketchfab.com/v3/tags/fnaf'},
  {'name': 'pizzeria',
   'slug': 'pizzeria',
   'uri': 'https://api.sketchfab.com/v3/tags/pizzeria'},
  {'name': 'fnaf1',
   'slug': 'fnaf1',
   'uri': 'https://api.sketchfab.com/v3/tags/fnaf1'},
  {'name': 'fnafmodels',
   'slug': 'fnafmodels',
   'uri': 'https://api.sketchfab.com/v3/tags/fnafmodels'}],
 'categories': [{'name': 'furniture-home'}],
 'thumbnails': {'images': [{'uid': 'b934954ef8204e758b3044277505c7d8',
    'size': 46702,
    'width': 1920,
    'url': 'https://media.sketchfab.com/models/fe07d29f80cf4985a7e0c3e49bcc638c/thumbnails/04d64f587a0b4bbd905d09c7b13c6a77/e8aefbfe1c0c4ea9b7266db30c1231fa.jpeg',
    'height': 1080},
   {'uid': '763e8432f5ee441395ab9de4397c188e',
    'size': 18558,
    'width': 1024,
    'url': 'https://media.sketchfab.com/models/fe07d29f80cf4985a7e0c3e49bcc638c/thumbnails/04d64f587a0b4bbd905d09c7b13c6a77/af13cc8892c04f97bc13b14e8367d903.jpeg',
    'height': 576},
   {'uid': 'e6b8d2fa4dc74b67a46f287cbbba1cad',
    'size': 11710,
    'width': 720,
    'url': 'https://media.sketchfab.com/models/fe07d29f80cf4985a7e0c3e49bcc638c/thumbnails/04d64f587a0b4bbd905d09c7b13c6a77/bd9b7ce42fab44838f7ac5dcc03d691c.jpeg',
    'height': 405},
   {'uid': '7eb152203866453fa4cc16bb3424f176',
    'size': 3057,
    'width': 256,
    'url': 'https://media.sketchfab.com/models/fe07d29f80cf4985a7e0c3e49bcc638c/thumbnails/04d64f587a0b4bbd905d09c7b13c6a77/e90d70897bb44081b41355dedc8cc536.jpeg',
    'height': 144},
   {'uid': '876e61bab365419b8fabdb3cd13a87e4',
    'size': 730,
    'width': 64,
    'url': 'https://media.sketchfab.com/models/fe07d29f80cf4985a7e0c3e49bcc638c/thumbnails/04d64f587a0b4bbd905d09c7b13c6a77/edb897d6669c4dd18ce4d97b610d4db4.jpeg',
    'height': 36}]},
 'user': {'uid': '240b3f14fbfc435a8f129591aa44ea19',
  'username': 'FascinationKR7X',
  'displayName': 'FascinationKR7X',
  'profileUrl': 'https://sketchfab.com/FascinationKR7X',
  'account': 'basic',
  'avatar': {'uri': 'https://api.sketchfab.com/v3/avatars/724fc390a589435aa3b63ba0bc5178e2',
   'images': [{'size': 681,
     'width': 32,
     'url': 'https://media.sketchfab.com/avatars/724fc390a589435aa3b63ba0bc5178e2/022a84f05e324cbe88c135344e7d1308.jpeg',
     'height': 32},
    {'size': 1080,
     'width': 48,
     'url': 'https://media.sketchfab.com/avatars/724fc390a589435aa3b63ba0bc5178e2/1d282b4d35474f48b873f8bf0f51361d.jpeg',
     'height': 48},
    {'size': 2974,
     'width': 90,
     'url': 'https://media.sketchfab.com/avatars/724fc390a589435aa3b63ba0bc5178e2/3ca4125672d84a568bb09da60e7fa41f.jpeg',
     'height': 90},
    {'size': 3546,
     'width': 100,
     'url': 'https://media.sketchfab.com/avatars/724fc390a589435aa3b63ba0bc5178e2/802ad1e6b0244425807fb9506d2842a4.jpeg',
     'height': 100}]},
  'uri': 'https://api.sketchfab.com/v3/users/240b3f14fbfc435a8f129591aa44ea19'},
 'description': "I did it in five seconds ok, it's definetly not accurate.",
 'faceCount': 3488,
 'createdAt': '2019-05-27T02:15:38.664769',
 'vertexCount': 1748,
 'isAgeRestricted': False,
 'archives': {'glb': {'textureCount': 0,
   'size': 158396,
   'type': 'glb',
   'textureMaxResolution': 0,
   'faceCount': 3488,
   'vertexCount': 4787},
  'gltf': {'textureCount': 0,
   'size': 35975,
   'type': 'gltf',
   'textureMaxResolution': 0,
   'faceCount': 3488,
   'vertexCount': 4787},
  'source': {'textureCount': None,
   'size': 475558,
   'type': 'source',
   'textureMaxResolution': None,
   'faceCount': None,
   'vertexCount': None},
  'usdz': {'textureCount': None,
   'size': 124851,
   'type': 'usdz',
   'textureMaxResolution': None,
   'faceCount': None,
   'vertexCount': None}},
 'license': 'by'}

In [38]:
len(filtered_objects)

44478

In [39]:
sampled_objects = np.random.choice(list(map(lambda x: x[1]["viewerUrl"], filtered_objects.items())), 44478, False).tolist()

In [40]:
sampled_objects = {url: True for url in sampled_objects}

In [41]:
sampled_json = dict(filter(lambda item: item[1]["viewerUrl"] in sampled_objects, filtered_objects.items()))

In [42]:
def filter_many_classes(annotations: dict, names: list) -> dict:
    result = {}
    stats = {}
    for name in names:
        filtered = filter_ann(annotations, name)
        result.update(filtered)
        stats[name] = len(filtered)
    return result, stats

In [43]:
r, stats = filter_many_classes(sampled_json, list(chain(*list(objects_to_filter.values()))))

In [46]:
stats

{'chair': 4709,
 'poster': 203,
 'frame': 1305,
 'artwork': 44,
 'monitor': 400,
 'piano': 318,
 'bulb': 273,
 'lamp': 3163,
 'table': 5264,
 'toaster': 97,
 'oven': 360,
 'fridge': 207,
 'sink': 407,
 'plate': 1046,
 'spoon': 182,
 'head': 5563,
 'log': 5304,
 'branch': 146,
 'bench': 1083,
 'bookshelf': 203,
 'bottle': 1648,
 'bowl': 1063,
 'cup': 2187,
 'desk': 1429,
 'door': 2393,
 'keyboard': 327,
 'laptop': 272,
 'stool': 526,
 'teapot': 299,
 'microwave': 90,
 'bed': 2409,
 'sofa': 1276,
 'wardrobe': 174,
 'rug': 435,
 'curtains': 42,
 'mirror': 332,
 'clock': 785}

In [47]:
len(sampled_json)

44478

In [48]:
annotations_sampled = annotations[annotations["fileIdentifier"].isin(sampled_objects)]

In [49]:
annotations_sampled

,fileIdentifier,source,license,fileType,sha256,metadata,keys
8971022,https://sketchfab.com/3d-models/524c5ae4075a4a...,sketchfab,Creative Commons - Attribution,glb,25ada8ac68d82791526979bc062d90ed920882948660df...,{},[]
8971029,https://sketchfab.com/3d-models/6e7fb4a4787241...,sketchfab,Creative Commons - Attribution,glb,5354c846cf5a7f4d900ced80419e3c8311cf72622d697d...,{},[]
8971059,https://sketchfab.com/3d-models/a5d06450f38b43...,sketchfab,Creative Commons - Attribution,glb,19260f69de00dd60836be1f09c511aec16e7a4c93a3126...,{},[]
8971068,https://sketchfab.com/3d-models/96a55276db4b4d...,sketchfab,Creative Commons - Attribution,glb,37609fb61aeb53169cdd917ff86300e045a10b59d2cf3a...,{},[]
8971090,https://sketchfab.com/3d-models/145061eedca04a...,sketchfab,Creative Commons - Attribution,glb,e13c58107fe8d9659704718f74a6a8c86aa95296f3f99f...,{},[]
...,...,...,...,...,...,...,...
9766787,https://sketchfab.com/3d-models/3ea030c2fc5944...,sketchfab,Creative Commons - Attribution,glb,885de304dc9deea850dbd92e2d4b78894c085c0455836f...,{},[]
9766828,https://sketchfab.com/3d-models/117ff7a0393049...,sketchfab,Creative Commons - Attribution,glb,f27c9b92125025d4c9b0bb54c0c7d0d2035f233da570e9...,{},[]
9766873,https://sketchfab.com/3d-models/c1340596c55a45...,sketchfab,Creative Commons - Attribution,glb,e40b7579eb9356f97053631ced8dd4b960edc30fa03709...,{},[]
9766914,https://sketchfab.com/3d-models/808e3269d21446...,sketchfab,Creative Commons - Attribution,glb,97bd5afd4c0d4491d047c78694e60fe25484f7818d812a...,{},[]
9766932,https://sketchfab.com/3d-models/c67f61fa444044...,sketchfab,Creative Commons - Attribution,glb,3e34a60944ed89f3eb0e0a62b4663d843e9256290aab7f...,{},[]

In [50]:
objects_to_download = annotations_sampled[["sha256", "fileIdentifier", "source"]].to_dict("records")

In [51]:
import json

In [52]:
with open("object_download_january.json", "w") as f:
    json.dump(objects_to_download, f)

In [124]:
objects_to_download

[{'sha256': '079c1fbedddddc5b9462a22ec9e043e808aac72c0b138b2173b4f191971135c6',
  'fileIdentifier': 'https://sketchfab.com/3d-models/bc0fd04422374b3987162a6c499280d8',
  'source': 'sketchfab'},
 {'sha256': '8a784c4a068239e24666b84acd05083ea7cb5092e3c0bc7550c2e13e5798786f',
  'fileIdentifier': 'https://sketchfab.com/3d-models/2c3379f8126743c0b6e564c70ff859bc',
  'source': 'sketchfab'},
 {'sha256': '4e41726df0b2eb46fa66be100b6c9389c2fb215fa87e17fc818cbea1d920c34d',
  'fileIdentifier': 'https://sketchfab.com/3d-models/007ab9e6f1c047b287bc0f09188de0c4',
  'source': 'sketchfab'},
 {'sha256': '39ccad9118884c8e416005646d85d1f668c91c944adbc6187262a829ab2d14e3',
  'fileIdentifier': 'https://sketchfab.com/3d-models/70583f5df06448c1bba076df3afcdbbb',
  'source': 'sketchfab'},
 {'sha256': 'f28847e18692b047fc15047749257a770b2f1b7e03124eaf4912d7cbdf796316',
  'fileIdentifier': 'https://sketchfab.com/3d-models/44be138ae8e2409bbbca44a96fc67d45',
  'source': 'sketchfab'},
 {'sha256': '396405650da99fd6e17a889de7b691df5984a567ae3e0f9f26726e9d8855f1aa',
  'fileIdentifier': 'https://sketchfab.com/3d-models/4d2b0f61b72e433492237d96d780f3f8',
  'source': 'sketchfab'},
 {'sha256': '0639c87f94d133e6c88abdbca3f9f984702c420866f1fd5d8dbe25b27001110a',
  'fileIdentifier': 'https://sketchfab.com/3d-models/d892ccd7e7404801885a9db3dfe8becd',
  'source': 'sketchfab'},
 {'sha256': '36492f183f0090a77849438f3de16003b3ffffa4436f90571d8df9a32095be2e',
  'fileIdentifier': 'https://sketchfab.com/3d-models/72d672aa4d434e47a82b8488092a8ee6',
  'source': 'sketchfab'},
 {'sha256': 'f919c7fd7c5a9ec81543e6a9ccfa9c7ef4ae07de62a1eef899fda37ba88e0b07',
  'fileIdentifier': 'https://sketchfab.com/3d-models/b4623f4127c143928b75ab839442f070',
  'source': 'sketchfab'},
 {'sha256': '74fdddef3dcce21c7dfb6f5bf4bfdcec470994646451652863b97ff1115cd2c9',
  'fileIdentifier': 'https://sketchfab.com/3d-models/d055777ad2e9460b8bc11cd62a454bdf',
  'source': 'sketchfab'},
 {'sha256': '02d365346e71ff6dd47c6bb02adca0d45b5b592659b02f27359ea21bc87834c4',
  'fileIdentifier': 'https://sketchfab.com/3d-models/f9b15ae605e047b498f7c0b2858a865d',
  'source': 'sketchfab'},
 {'sha256': 'ad7b42e4e597f1b713c5b876136369ca9053f742cbe360a87c790333a15580a2',
  'fileIdentifier': 'https://sketchfab.com/3d-models/cd0e50d2386849a8924f21dd16fc3280',
  'source': 'sketchfab'},
 {'sha256': '8df516a58790ee6458c8a077a8e5f348f45b9eee434076aac67bb267e07ce66c',
  'fileIdentifier': 'https://sketchfab.com/3d-models/07b07f7292ed41019a8b6aebd98a5c29',
  'source': 'sketchfab'},
 {'sha256': '81a8ca5899c7cfedab55bc6233c3e6a361a75471a520018c482f4a4dc160e74b',
  'fileIdentifier': 'https://sketchfab.com/3d-models/0abcc9938f94440cb8c0a7d29d4c52ee',
  'source': 'sketchfab'},
 {'sha256': '95b70604177995a7441deeb09c62e55d85e8564eca9cff91972960226dc5f104',
  'fileIdentifier': 'https://sketchfab.com/3d-models/dbf5eb754bed4d269047bc67f08d4701',
  'source': 'sketchfab'},
 {'sha256': '23e542470166f55d9b04e6a1964c56532cdae177e6ef1899018c89bb7c7c72a1',
  'fileIdentifier': 'https://sketchfab.com/3d-models/7eece8d7b74e41cf94c4d01cfeb2c968',
  'source': 'sketchfab'},
 {'sha256': 'b2f28c1703da9ce04b07245ed6944373afda518ebb18dfd77cdd90d5f6494764',
  'fileIdentifier': 'https://sketchfab.com/3d-models/65c234a5320644be9aabb6dbcf2e2dfc',
  'source': 'sketchfab'},
 {'sha256': 'd4c0087eef898b869101beb62f1636dc68329564251d91f48c16704da3f65c06',
  'fileIdentifier': 'https://sketchfab.com/3d-models/7d68c90551144cdb81d9223b8ead8cda',
  'source': 'sketchfab'},
 {'sha256': '31470d1c3dc6ccccc2bb6f8ead48ef5189e3d2173043283f93ce8a55ba1e98eb',
  'fileIdentifier': 'https://sketchfab.com/3d-models/01ac564cf0d24007a0a9965048124a04',
  'source': 'sketchfab'},
 {'sha256': 'e8b0159f9880fe27936f8043fd609b49a7af6264426ee5ae6d73b9e1c3954e4d',
  'fileIdentifier': 'https://sketchfab.com/3d-models/2672abb9518c4367abc46c7804ae44d2',
  'source': 'sketchfab'},
 {'sha256': 'cf26d741ac4c9cd8129a261b40ba6fc0c9941a70ba0525ca10902a441c16c6fe',
  'fileIdentifier': 'https://sketchfab.com/3d-models/2a02794be3c44a9c845159164e320d34',
  'source': 'sketchfab'},
 {'sha256': '88a1ff5cee5d00afbd071797b1195e65dd2c050b05a114e6731767f224381b4a',
  'fileIdentifier': 'https://sketchfab.com/3d-models/96b938e88ac942209fcf403b00a7297b',
  'source': 'sketchfab'},
 {'sha256': '44d1fe642d44d9023fc722f776a3da1283a80358d6b070267dad8c50133fbdf4',
  'fileIdentifier': 'https://sketchfab.com/3d-models/bae31e4c68b443468c1c6a3ced6eb289',
  'source': 'sketchfab'},
 {'sha256': '78968f324f5ccc758ca23fb78c08636fb76e74af0da056f25960df9c38ceda74',
  'fileIdentifier': 'https://sketchfab.com/3d-models/483ac8fb734b45e39bb03ddd58906a3c',
  'source': 'sketchfab'},
 {'sha256': '1cba99e2a53a64c81f4a20b0d53fe03a21784d6f2c950e65c1c0832b787e367a',
  'fileIdentifier': 'https://sketchfab.com/3d-models/5c11613bd0ef4e1cba02961b7552a37f',
  'source': 'sketchfab'},
 {'sha256': '08b5beae466625a4685166654341ca753543824209dc2baebff2384ada76710e',
  'fileIdentifier': 'https://sketchfab.com/3d-models/19da225fca2b4527ba03ba5d2f540200',
  'source': 'sketchfab'},
 {'sha256': 'f717ce41f123b1e13c19d80d8eaa3cb9d5e3cc651feec7675984562ac6b2cd4b',
  'fileIdentifier': 'https://sketchfab.com/3d-models/5cc2bb8c64cd401c8b7c0c0625ab6ae7',
  'source': 'sketchfab'},
 {'sha256': 'd61252fff641700da8030f55f53a5fc0fc4c134c92bae27373ce3c0fd1192dc7',
  'fileIdentifier': 'https://sketchfab.com/3d-models/7111485f9c4848079954df9c3feab365',
  'source': 'sketchfab'},
 {'sha256': '10cd1e865ba7e852d155fcad4017620549935ab02db9257ff0b930e444d60168',
  'fileIdentifier': 'https://sketchfab.com/3d-models/8b4cf46b346c4342bbc5ce574f7bd8f1',
  'source': 'sketchfab'},
 {'sha256': 'cb40d98eb56d21d0e6375f0e3b29fa2b2ea0586d38bea650e959660321f5462b',
  'fileIdentifier': 'https://sketchfab.com/3d-models/1c98dea5fe1d40079a7806a6f94067f9',
  'source': 'sketchfab'},
 {'sha256': 'd25dbd875457add4abc2e85a926582b6c6fa5b460be864f3159c5906dc5a27d8',
  'fileIdentifier': 'https://sketchfab.com/3d-models/6a7cc74278a8442bb9efca045d9d9234',
  'source': 'sketchfab'},
 {'sha256': 'ce329fd1f8092daa6065d42899b41dc19c27c522574ed12ef04269d20f0ab2a0',
  'fileIdentifier': 'https://sketchfab.com/3d-models/c434f22ec51846cc8142e95f7f2495eb',
  'source': 'sketchfab'},
 {'sha256': '2cb0543fe2b3be085d2e7ebc9d42cb9972b7d668027ad31ca6dc67c4b9764601',
  'fileIdentifier': 'https://sketchfab.com/3d-models/bf6970e526854fd8beb1201183de1bdf',
  'source': 'sketchfab'},
 {'sha256': '19d8e46c436a20ebcc1eb068c1a99c71036bf3fa09059dc26d6b61c29f8ecafa',
  'fileIdentifier': 'https://sketchfab.com/3d-models/25f130c40c8948c2be8f4d34fb7e903c',
  'source': 'sketchfab'},
 {'sha256': '9467dcdb121f752c70220878d9291be5eae133f35a41ece931e4143a841a8e8e',
  'fileIdentifier': 'https://sketchfab.com/3d-models/fb807fdf2bfa433192e434a5a04e017d',
  'source': 'sketchfab'},
 {'sha256': '576f3eb0151cf9c4f15a3627ccd76dced5cd4a2f0c2cbcfaa986697cc95e879e',
  'fileIdentifier': 'https://sketchfab.com/3d-models/6c1b44e0848347299aa3676d1de38a2d',
  'source': 'sketchfab'},
 {'sha256': '7819617c8198aa1fa197fda61ad0899ee1194a4fd9f4205711e19c4ee51563d5',
  'fileIdentifier': 'https://sketchfab.com/3d-models/9869ead903f84a37a9aa61b6c60c3a93',
  'source': 'sketchfab'},
 {'sha256': '5082735dbc259ad991d5db0a09127782bbb4d776393b2b3d0da74172045efedd',
  'fileIdentifier': 'https://sketchfab.com/3d-models/4491c046bbe849c58fc52408c57f3549',
  'source': 'sketchfab'},
 {'sha256': 'e55fc359787976ab8b3c995666764a3120f43c93480feccf086e8524414a64b5',
  'fileIdentifier': 'https://sketchfab.com/3d-models/4d8d446e4d0149feb2b84127cc106df7',
  'source': 'sketchfab'},
 {'sha256': 'a31bce03891218441ec396a8f8a6ea80faa719a12da5e6dda9ab2c91970da892',
  'fileIdentifier': 'https://sketchfab.com/3d-models/22929fd1943945118562ff2e6fd2f35d',
  'source': 'sketchfab'},
 {'sha256': 'edd8de5485160a19bc5e0de55278e055089cb96209bd9517801410a83326bd4b',
  'fileIdentifier': 'https://sketchfab.com/3d-models/0859bd17564f4747b87ecec7d6c57b22',
  'source': 'sketchfab'},
 {'sha256': '536db46e67d566cc5228a79b2d8c1d7ca76aabf83e6cac9ad29d7b529fa7bece',
  'fileIdentifier': 'https://sketchfab.com/3d-models/fe96368b814e4a54b41cedfcbe8b970a',
  'source': 'sketchfab'},
 {'sha256': '191f5a7557fff13ca2067115b91771b73202688dac64ef7ccf905ead139607ab',
  'fileIdentifier': 'https://sketchfab.com/3d-models/ab3e5682eeeb4dc2b176d47160242839',
  'source': 'sketchfab'},
 {'sha256': '1d6734b6cf9695c90bd9e078f3ca0c29125b2711e69b5c6b5d8dbeb925ad4413',
  'fileIdentifier': 'https://sketchfab.com/3d-models/bb571a973e494c899dd9b153489aae0a',
  'source': 'sketchfab'},
 {'sha256': '955225ae96bcae623de678c19c74bdfa792057d1cd434ce56e1c4e738ef3ce68',
  'fileIdentifier': 'https://sketchfab.com/3d-models/d65a36094248427aacd138fde3a7cb9f',
  'source': 'sketchfab'},
 {'sha256': 'fd939e60ab67edc335c0019e5699fd564fa425e8846238587d90ca6b8ce36d52',
  'fileIdentifier': 'https://sketchfab.com/3d-models/92e9c5d41cf6422e84bc2e81d8a6a4d1',
  'source': 'sketchfab'},
 {'sha256': '22204b62acc0a30b05b5475d18699fd0139ff9456ef16330efdb0b3db88d0cd2',
  'fileIdentifier': 'https://sketchfab.com/3d-models/ac71a0a0c5154f95845f16cfefdb6e18',
  'source': 'sketchfab'},
 {'sha256': '4606b94036a0dfdb64144db929eb0f3d21e9328076c9b2f77c82d0bf67a9f480',
  'fileIdentifier': 'https://sketchfab.com/3d-models/92dd6344744e4ddd89dd554cefec9057',
  'source': 'sketchfab'},
 {'sha256': 'f74df73c53e7f2c5b86373e668e41ca0152434cb51bda9ace5b14c7463bbff92',
  'fileIdentifier': 'https://sketchfab.com/3d-models/a2efbf1d6be848b984fd9bedffc549a5',
  'source': 'sketchfab'},
 {'sha256': '5e991a5b840a8b418e1b6f659641429803f50538cae546fb5ef53f659b5db048',
  'fileIdentifier': 'https://sketchfab.com/3d-models/18797382d5d048df9babfb57809cefd6',
  'source': 'sketchfab'},
 {'sha256': 'd261a3ebe1597682293fafcabdbbeb7c7df4f9a94716eb7b1c15f86e52934a65',
  'fileIdentifier': 'https://sketchfab.com/3d-models/4f63ec1d217845b994a627d4053bc7a2',
  'source': 'sketchfab'},
 {'sha256': 'a3e867e3fdf04fe7634ad76a69a040a6866410b6e2492a8e52faad23776e5b1f',
  'fileIdentifier': 'https://sketchfab.com/3d-models/8668a2b3e5e743248b3fd64fb6246a0a',
  'source': 'sketchfab'},
 {'sha256': '4277b6ef3aa1f0c10b0c6d892e40fe314b6aa06a1c5950397896e3bf53e97e64',
  'fileIdentifier': 'https://sketchfab.com/3d-models/c665d3c997e64828b24e5dddeabced8e',
  'source': 'sketchfab'},
 {'sha256': '86a841c02e65bfd114a6a7e62c5d8c84b58e1a7913ff9f28c5b2fa101c67c1da',
  'fileIdentifier': 'https://sketchfab.com/3d-models/6ffd7a7a5da647ed8508fae3b6f4d812',
  'source': 'sketchfab'},
 {'sha256': '14e5e1f8eaa96ed9dcd5d2aed3216871d909706f8000b62524e30343f5344b9e',
  'fileIdentifier': 'https://sketchfab.com/3d-models/2645585305c24a30bfaa63a63450b084',
  'source': 'sketchfab'},
 {'sha256': '0696cf73cc248196d53cd69a7d6c01c3fc196ee576f49eabacd6508339f33514',
  'fileIdentifier': 'https://sketchfab.com/3d-models/f7799baf56fb46918fde5553da579a81',
  'source': 'sketchfab'},
 {'sha256': '13998a6fde83d6442f59474ea7f5f8d15ebc644e6a729bf8b0271ef59b886101',
  'fileIdentifier': 'https://sketchfab.com/3d-models/33ba9101817a4ed5827ea906766c02b7',
  'source': 'sketchfab'},
 {'sha256': '0a77ecabaed83a091c3510d59d29c6ba74c3fe637b6c45dd235e8f6ba6cb7b53',
  'fileIdentifier': 'https://sketchfab.com/3d-models/edad0f3225364ea896dbe2d8519e6981',
  'source': 'sketchfab'},
 {'sha256': '412f9ec5d45d5e9ca3df35e52a4fd233f55c013ee0a3ba59ccb649a5dcd706c6',
  'fileIdentifier': 'https://sketchfab.com/3d-models/9ad672c7b3ae4723a465873ce8a7b79f',
  'source': 'sketchfab'},
 {'sha256': '426ba20cbfbf8f2056320ade48619ca89f4821c2c1f1eb134682d7d6d1e4b184',
  'fileIdentifier': 'https://sketchfab.com/3d-models/fc97aebb2342487dbc3b1c4445f54155',
  'source': 'sketchfab'},
 {'sha256': '7ee4b3dc0504a7fa9c1c24266a602f76100903c0b0c64ff003a6278bc0978a7a',
  'fileIdentifier': 'https://sketchfab.com/3d-models/7755623b72f3455886912ef1f31f1ca4',
  'source': 'sketchfab'},
 {'sha256': 'f4041e326051ec4f227b47317bf3d19c1c92f825dbf4c0f147b5fa64b6e3f794',
  'fileIdentifier': 'https://sketchfab.com/3d-models/8c0be01b915a4bf7975404094c41ef1d',
  'source': 'sketchfab'},
 {'sha256': '8616d5163d53cd5315ae6eaf4b8c8b3240f6561fbb7d999586222b2bc4677b5a',
  'fileIdentifier': 'https://sketchfab.com/3d-models/284abe54a4464b6ab99c93d4be3c2c6b',
  'source': 'sketchfab'},
 {'sha256': '21bfd79d2d560b80d468255ae2133aff433002af2a088fa796d7ed74a2fbcc09',
  'fileIdentifier': 'https://sketchfab.com/3d-models/a6c5247ee6cf46e7b6f32a4df9d3ca24',
  'source': 'sketchfab'},
 {'sha256': '09e8bc9d26d1e6e5bcc3544b10474cf627692d5a11c6d2c59c9f2df994dcd62e',
  'fileIdentifier': 'https://sketchfab.com/3d-models/eea22935209d4a9f8fb61092f91b36d0',
  'source': 'sketchfab'},
 {'sha256': '27e4e4103ab8628dc894898420dd2e28b1c90ee7769bd27a44947691c0678e65',
  'fileIdentifier': 'https://sketchfab.com/3d-models/f4f04b082af5442f914fd4a72640a76e',
  'source': 'sketchfab'},
 {'sha256': 'c1c0aec8386758b0204d4d61904295376a85640018a6c5e8d953a0d83d11010d',
  'fileIdentifier': 'https://sketchfab.com/3d-models/7515263af5474063b0b538a6f1b55dc9',
  'source': 'sketchfab'},
 {'sha256': '4b03f2ff19d3790dbbc93c2bd9982df3ded572facd94c80af8992fd5c134e570',
  'fileIdentifier': 'https://sketchfab.com/3d-models/ecdb7e9060ca45a3921c7c43b4084153',
  'source': 'sketchfab'},
 {'sha256': '36b2eedc120b333c83de5c52d7b2547cacf4ebd53d0bfaf2b002c464364bced4',
  'fileIdentifier': 'https://sketchfab.com/3d-models/cc1f88455e2e44ce882cfb88886c0db7',
  'source': 'sketchfab'},
 {'sha256': 'cc368a8f5d95da248d1506c0b2f890f6617c9d2a33f56cc5c15494d64e11274b',
  'fileIdentifier': 'https://sketchfab.com/3d-models/9e8eac6922ee4b02bc8446fb41d3e8f4',
  'source': 'sketchfab'},
 {'sha256': 'd79e428e440b914ea004220f165e9377fa7d9be7a6a3978012ebceb278cea5a0',
  'fileIdentifier': 'https://sketchfab.com/3d-models/ab75b36b814540edafbe636c6fd3f3ae',
  'source': 'sketchfab'},
 {'sha256': '1805e3e155bdc0b163f783b7ff4b7138dfe64191b8c213b943681669cceebf31',
  'fileIdentifier': 'https://sketchfab.com/3d-models/a153134ea8cd4a2fb01da79595a892e4',
  'source': 'sketchfab'},
 {'sha256': '3838707203a821a9bf90403b23d8f448391ebe6fc8bfa4f398689ae071e6970f',
  'fileIdentifier': 'https://sketchfab.com/3d-models/65dcebe837d34f13ae6c7dc2fa3b79fc',
  'source': 'sketchfab'},
 {'sha256': 'e163b0132b208b3fbf250d70e32d411b69f0370443c298f0ac8f1d61af8d9869',
  'fileIdentifier': 'https://sketchfab.com/3d-models/75bdec09d9ce4651b2773ee48fe13a08',
  'source': 'sketchfab'},
 {'sha256': '90e0f661a4a49b8a3e086c24296ca74bfcb80decd6de8ebe9670ccbd08fd1ed7',
  'fileIdentifier': 'https://sketchfab.com/3d-models/46066ddab8db4729921a5260a0f84ecf',
  'source': 'sketchfab'},
 {'sha256': 'ff444740f6c92e969377c43e48e0875f94526b75b1d46514a7a3ccb82477c4bd',
  'fileIdentifier': 'https://sketchfab.com/3d-models/69cf9bd15acf44f590b65b21e07a2d63',
  'source': 'sketchfab'},
 {'sha256': 'f0081bd5d029336fd5bc9fe6e6b17873e8c928d14cf0079545752ffe4c2b518f',
  'fileIdentifier': 'https://sketchfab.com/3d-models/a4d838e8fa224fdba861b07de0127e97',
  'source': 'sketchfab'},
 {'sha256': '6f8fedd739ab178fe1d01525cfe10b58f594f580255ce34b577fb1152716e01a',
  'fileIdentifier': 'https://sketchfab.com/3d-models/dafcc83828814524b88751266f353b24',
  'source': 'sketchfab'},
 {'sha256': '57c71a396b27d9e9cee5ddf59e9c088de64c925405f33e42cb7151fa1f90f0a0',
  'fileIdentifier': 'https://sketchfab.com/3d-models/4ecbb77898d1437ca54d99bb74572686',
  'source': 'sketchfab'},
 {'sha256': '1dba1fa3319c45220b8cde2b84b8b9eb7135c2470bfb3d3209a578b79e43addf',
  'fileIdentifier': 'https://sketchfab.com/3d-models/f30d8ab84cb948709710fa7d0e1495f8',
  'source': 'sketchfab'},
 {'sha256': 'a7c38293f02c6884df5f8f59d3e312e024dd094c9bbd0a46aaa29a11ac571220',
  'fileIdentifier': 'https://sketchfab.com/3d-models/cc9d3e0368124bf8a339d4f1fc85743f',
  'source': 'sketchfab'},
 {'sha256': '73c7186e6f33687cad0385e00bf39fc922a3ae1bfd802fa4ce1e7447d43a2822',
  'fileIdentifier': 'https://sketchfab.com/3d-models/da3765e522a44c7a963078d904454056',
  'source': 'sketchfab'},
 {'sha256': 'b5699e8baadcf6a9b85025ec751da20edf7e5fd84afcae2b3d2606c08ed65251',
  'fileIdentifier': 'https://sketchfab.com/3d-models/baed2b671fc64bc3a74d9fcc4033e2e9',
  'source': 'sketchfab'},
 {'sha256': '974eed3743d38235064f81df9d1ef2fa4ea60c17122782d2a36e3c369eb582a4',
  'fileIdentifier': 'https://sketchfab.com/3d-models/f6a3560135cb4c31bc3bfb1476d86ed8',
  'source': 'sketchfab'},
 {'sha256': '9d17066cafc2a9743d58de8d52a2fabb96d4d8919cf9a8c2f2b006eb0a1289be',
  'fileIdentifier': 'https://sketchfab.com/3d-models/2e0c23f32db249bdab3be206b75df0bc',
  'source': 'sketchfab'},
 {'sha256': 'aaae333fd5426fd366007c4172bdb7e85422e11d1f28fd8160b0d1e36ec26724',
  'fileIdentifier': 'https://sketchfab.com/3d-models/e1748cef902849909bbacbe3dae266ae',
  'source': 'sketchfab'},
 {'sha256': 'dafaa8bacc7f908bef0fe9733d3321ec2018df0bbef67da92a38e00348493a10',
  'fileIdentifier': 'https://sketchfab.com/3d-models/b9b62de756a447f8b11353e368920091',
  'source': 'sketchfab'},
 {'sha256': '07fcbd000c2aa4cb92c0df29eb9438a90b123627bad0a8b5634f7bb407c4c582',
  'fileIdentifier': 'https://sketchfab.com/3d-models/8611d3ff27054e33b4a34e434448447c',
  'source': 'sketchfab'},
 {'sha256': '81bebf09f9efb8e0becb0692ace5d1a62f5a41d94901b87ce74aecc318ba749a',
  'fileIdentifier': 'https://sketchfab.com/3d-models/a582b56dfa2c4fdca77ca493ad38620d',
  'source': 'sketchfab'},
 {'sha256': 'df5dac701a10873af08b23eb1f1f7dbfa098a9c3ccc62015b1b885a7ae28c936',
  'fileIdentifier': 'https://sketchfab.com/3d-models/c313236be20b4cdcb707badbbbe2c910',
  'source': 'sketchfab'},
 {'sha256': 'a68a0238fdd650ce161e50f261b22057461f4a3091ce1ef90560cad167e06aa3',
  'fileIdentifier': 'https://sketchfab.com/3d-models/b8f10b3e408245acaf035c529dfe39f2',
  'source': 'sketchfab'},
 {'sha256': 'c074baf45fdcf75d3dcc7cb57460b4fa8740e1c3d23008e2a7a6b106e1a92098',
  'fileIdentifier': 'https://sketchfab.com/3d-models/4bb7c6bf189a499783f3c769a3508823',
  'source': 'sketchfab'},
 {'sha256': '253bfa383067e6de1c8b1c37df28b3f521f4c9322f20b9ce59a5fc309a7d5ed1',
  'fileIdentifier': 'https://sketchfab.com/3d-models/62d716606a6d4220886b91664b67abff',
  'source': 'sketchfab'},
 {'sha256': 'db4167c67db3ba0e623d11ea381bd7e92b568449276d9c818114d07c481bb796',
  'fileIdentifier': 'https://sketchfab.com/3d-models/805e1351548b47f090529d1192bd1f8e',
  'source': 'sketchfab'},
 {'sha256': '676b66c1ec2c2280a85109ca56f1c74d5dbd6a0d8a302c5b15ecf1ddcf32af80',
  'fileIdentifier': 'https://sketchfab.com/3d-models/4bc23ae1953c48e3b56cdcc60d6be110',
  'source': 'sketchfab'},
 {'sha256': '347b7615aab1079b7230d27e98153f1c9649d0a7c4cde6d14d27bab64b4d61ba',
  'fileIdentifier': 'https://sketchfab.com/3d-models/2c890c6acd754ca1b0abf11b7f7ffa3e',
  'source': 'sketchfab'},
 {'sha256': '2624783fa5caa5c3c3dbf2062b519de43648fab10946e62e8d21e8aca86c81cd',
  'fileIdentifier': 'https://sketchfab.com/3d-models/2bf17251cd6b4635a83445dc79186322',
  'source': 'sketchfab'},
 {'sha256': '44a1dfb860ff098bbdc3af4145b8a19e7d6fd6db7ebdfcc7c18a13304aa67bd8',
  'fileIdentifier': 'https://sketchfab.com/3d-models/7dad1ab4c66949578f436543bd2419c8',
  'source': 'sketchfab'},
 {'sha256': 'd8d5947d8f14ba758bcb1c0ac7dcba093eda0a904dca1e2153e245ad87df2e82',
  'fileIdentifier': 'https://sketchfab.com/3d-models/a745fdd7c808472a8f70342cc6d5a4d7',
  'source': 'sketchfab'},
 {'sha256': '775de5e9f9187e283ba54bc428164d1633153a401e91d2726e20c1dc969c62dc',
  'fileIdentifier': 'https://sketchfab.com/3d-models/a98372bdac824a91aaf6dbd4984640e1',
  'source': 'sketchfab'},
 {'sha256': 'ea61d61d6f7797d6e1d5a9bd7bcada92f0ddcaeb8acd4e5c8f2c5fb064940bae',
  'fileIdentifier': 'https://sketchfab.com/3d-models/4b1269cba4d04486acebe11bf052180a',
  'source': 'sketchfab'},
 {'sha256': 'fd3ea6beda844f508bd6fdd7c9a7d6c232a50a6f84cf9d915c528620863feb1d',
  'fileIdentifier': 'https://sketchfab.com/3d-models/4dbe0be014d14c27a262e81a5e0046fb',
  'source': 'sketchfab'},
 {'sha256': '338ece50b36e8bcc249bb1cfd250f1ade5126698c23c7c5c60d92945c8e0d728',
  'fileIdentifier': 'https://sketchfab.com/3d-models/ce286225d5fd436d927099bcbca8ac40',
  'source': 'sketchfab'},

In [127]:
import multiprocessing

In [128]:
multiprocessing.cpu_count()

16

In [ ]:
!htop

2486999 dtrofimov 1144M  318M  97527  0.5  0:01.18 python3 main.pyon3 main.p[1;1Hsystemd/sM 93208 22004 S 1  0:06.61 /usr/bin/python46336.3G 13.7G 7399221.5  1:04.20 /vol/isy-rl/dtr46496.3G 13.7G 73992135 /vol/isy-rl/dtr23654699944M  312M  97521.1612634256  4744  3628 R 016 htoppy0   0  4816  1232   900 S  0.0  0.0  0:00.00 /usr/sbin/rpc.s920 _rpc       20   0  8100  1308   876 S  0.0  0.0  0:02.59 /sbin/rpcbind -921 systemd-o  20   0 14828  1664   864 S  0.0  0.0 28:40.43 /lib/systemd/sy931 root       20   0  313M  5032  3356 S  0.0  0.0  0:12.05 /usr/sbin/rpc.g932 root       20   0  313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g1145 root       20   0  2808    92     0 S  0.0  0.0  0:00.25 /usr/sbin/acpid1148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --1154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.55 /usr/sbin/irqba1158 root       20   0  258M  8100  4544 S  0.0  0.0  0:02.83 /usr/libexec/poF1Help  F2Setup F3SearchF4FilterF5Tree  F6SortByF7Nice -F8Nice +F9Kill  F10Quit|4.5|5.4|1.3|1.3||2.7||1.3|7|2||1.3|7||3.971569931065M  304M  9752 S  2.7  0.561 python3 main.py2487001 dtrofimov 1065M  304M  9752 S  2.7  0.5  0:00.57 python3 main.p1.31.3|0.7 0.0 | 0.7 0 0  0.0 02.077000546990D  2.04945M  304M  9752 S  1.36861.375699852 S  1.362490.70:00.34 /vol/isy-rl/dtr50.779144M  3080.71.1470010.7587004688 S  0.70.51700524 S  0.75812634256  4744  3628 R  0.7  0.015 htop2.6|3 01.3 0|7|73.319 3.03869963.380S  2.753700107003127M  309M  97365870049M  308M  968853331:04.17 /vol/isy-rl/dtr18M  307M  9736382065M  304M  97360.526993D 626995M  304M  97526969952469991144M  310M  9752 S 5  0:01.15 python3 main.py2487002 dtrofimov 1065M  304M  9728 D  0.7  0.5  0:00.54 python3 main.p 0.0 2.7|3||1.32.720700228 S  2.75870052462D  2.034636.3G 13.7G 7399221.5  1:04.19 /vol/isy-rl/dtr69935M  304M  9752 D 645.4|7  0.0 0.72.0 001699052769918M  307M  9736436996S  2.785699065M  304M  9752 S  2.0  0.5  0:00.67 python3 main.py7001S  2.06|71.3|1.3|7||1.3 0 0| 9.61 3.03 1.06 3700106935M  304M  9752 D  1.36979M  3081.31.04700524 S  1.3446336.3G 13.7G 73992 S  0.7 21.5  1:04.21 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 2136 /vol/isy-rl/dtr69901065M  304M  97525  0:00.58 python3 main.py6991068M  307M  9736 0.5  0:00.44 python3 main.py6992065M  304M  9736 D  0.7  055 python3 main.py452716065M  3040.869981065M  304M  9752 D 563 python3 main.py2487003 dtrofimov 1127M  314M  97367  0.5  0:00.60 python3 main.p|2.72.6  0.0|7|7|7|1.3||3.346995D  1.350700228025M  304M  9736 D  0.70.56699352 D  0.7706997069M  308M  975 0.5  0:01.05 python3 main.py699144M  315M  975 01.17 python3 main.py700D 57003127M  3166170049M  308M  9688 S 7 1.3  0.0|2|7||7 0|2.00.72.7670049M  308M  9688 S  2.76169979M  308M  9752 S  2.01.0846336.3G 13.7G 73992 S  1.3 21.5  1:04.23 /vol/isy-rl/dtr1.3285M  304D  1.30.67000065M  304D  1.30.5228 D  1.36246496.3G 13.7G 739922137 /vol/isy-rl/dtr69905M  304M  975292.6||1.3|1.34||1.31.3||7 0.7| 040 3.10 1.10769918M  307M  9736 D4835M  30470.767004069M  308M  9688 D  2.0  0.5  0:00.64 python3 main.py236 S 594S 7469952699652 S 896998065M  304M  9752 S  1.3  067 python3 main.py70011.3717003127M  3201.36346336.3G 13.7G 739921.5  1:04.24 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 2138 /vol/isy-rl/dtr0065M  304D 0.60

  4445446264  1916   808 S  0.7  0.0  0:07.37 /usr/bin/pipewi0169M  3210.76969918M  307M  9736 S  0.753/dtr6990169M  307M  9752 S  0.746995065M  304M  9752 D  0.7  0.5  0:00.55 python3 main.py6997069M  308M  9752 D  0.7  01.13 python3 main.py06049M  308M  9689R 66700528670D  0.716993D  0.776997069M  308M  9752 S  0.71.097000065M  304M  9752 D  0.7  0.5  0:00.59 python3 main.py7001065M  304M  975 072 python3 main.py7002283|||3.3|7| 0.7|7|2.7||7 0|7|2.0||3.9|1.3130D  2.057069M  308D  2.0120D 635S 54699944M  330M  97521.2D 8D 946336.3G 13.7G 73992 S  0.7 21.5  1:04.25 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 2139 /vol/isy-rl/dtr70015M  304D 0.73228643127M  329M  973666  0.0 ||1.3 0| 0 0||7| 0.7| 3  0.0377 3.28 1.1627003127M  3336 S  2.77025M  304M  9736 D  1.30.619144M  336S 1.27700228 D 660.7|7| 0 0|7|7 0||2.034040169M  312M  9752 S 641946336.3G 13.7G 73992 S  0.7 21.5  1:04.27 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 210.40 /vol/isy-rl/dtr6998712634256  4744  3628 R 019 htop1695 root       20   0 32872  4400  2168 S  0.0  0.0  0:03.26 /lib/systemd/sy889 root       20   0  4816  1232   900 S  0.0  0.0  0:00.00 /usr/sbin/rpc.s920 _rpc       20   0  8100  1308   876 S  0.0  0.0  0:02.59 /sbin/rpcbind -921 systemd-o  20   0 14828  1664   864 S  0.0  0.0 28:40.43 /lib/systemd/syM1.3 0  0.0 0||7 0 0||1.3 0825699944M  349M  975201.32700327M  344M  9736 S  2.0773065M  304D 0.76972321M  356M 63196 0.6  0:02.49 python3 main.py6990169M  316M  975 067 python3 main.py4860041069M  308M  9688 D 570 python3 main.py2487006 dtrofimov  20   0 1321M  356M 63196 S  0.7  0.6  0:00.02 python3 main.py||1.36.0|7||1.3||3.3||8.6|1.3||2.6 0.7|7| 6361068M  307M  973670.56995065M  3052 D  2.7596S  2.79597069M  308M  9752 S  25  0:01.177005065M  304M  9728 D  273236 S  2.0646995M  304M  9752 S  2.0896999144 9752 S  2.01.35 python3 main.py2487001 dtrofimov 1065M  304M  9752 S  25  0:00.76 python3 main.p 0.74 03  0.06.0 0.0 0 0.7|71.3|2.6||5.2255 3.34 1.20835M  304M  97520844092506265M  30400.982S  2.017005287646336.3G 13.7G 73992 S  1.3 21.5  1:04.30 /vol/isy-rl/dtr7001065M  3041.3  0.5  0:00.7849M  308M  9692 S  1.35 03.4|7 1 2 0 1.33.997818M  307M  9736 S 56479570049M  308M  9697573969952 S  1.3646996065M  304M  975 0.5  0:01.00 python3 main.pyD 80461 260M 93208 22004 S  0.7  0.1  0:06.62 /usr/bin/python2484633 dtrofimov 16.3G 13.7G 7399221.5  1:04.31 /vol/isy-rl/dtr248464916.3G 13.7G 7399221.5  0:00.42 /vol/isy-rl/dtr700065M  304D 470025M  304M  972872|3 0|0.70.7 0|0.7| 2.04170049M  308M  9692[19556715M  304M  9752 S  1.3823127M  351M  9736 S  1.38146336.3G 13.7G 73992 S  0.7 21.5  1:04.32 /vol/isy-rl/dtr0169M  3250.70.7699236 D  0.76669931065M  304M  97525  0:00.89 python3 main.py6994067M  304M  975 0.5  0:00.96 python3 main.py6998065M  304M  975 073 python3 main.py512634256  4744  3628 R 021 htop

      1 root       164M  9544  41440  0.0  0:39.97 /lib/systemd/s1;1H2487004 dtrofimov 1069M  308M  96927  0.5  0:00.92 python3 main.py2487126 dtrofimov 34256  4744  3628 R  0.7 0:00.24 htop  164M  9544  414439.97 /lib/systemd/sy1;1H4;45HD  2.01.032065M  3042 S  2.0757004069M  308M  962.0  0.5  0:00.85 python3 main.py61.32852 D  1.3757000D  1.36770057328 S  1.38146336.3G 13.7G 739921.5  1:04.33 /vol/isy-rl/dtr69918M  307M  9736 S 069971069M  308M  9752 S 5  0:01.18 python3 main.py|74  0.0  0.0 0|1.3 0|3.3|7| 0246992065M  30457370005277188S  1.351.371.3746336.3G 13.7G 73992 S  0.7 21.5  1:04.34 /vol/isy-rl/dtr4646.3G 13.7G 73992 S  0.7 2110 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 2143 /vol/isy-rl/dtr6990169M  328M  9752 S  0.773699065M  304M  975 0.5  0:00.90 python3 main.py47M  304M  97529755M  3040.71 00.7||2|1.3||1.3|0.7  0.0 0625700208049M  308M  9692 S  1.38946336.3G 13.7G 73992 S  0.7 21.5  1:04.35 /vol/isy-rl/dtr18M  307M  9736 D  0.70.616996 S  0.7469935M  304M  9752 S  0.7916994067M  304M  975 0.5  0:00.98 python3 main.py6995065M  304M  975 072 python3 main.py6997069M  308M  975 01.19 python3 main.py8065M  304D 97000D 72712634256  4744  3628 R 022 htop|74.0| 1.3|2.0  0.01.3|74.518.37 3.30 1.2070577669985M  304M  9752 S  2.027002065M  304M  9732 S  2.0  0.5  0:00.83 python3 main.py1.33700152 S  1.381.30.7||2.0 1.3 0.0 0||2.64969918M  307M  9736 D  1.365471.31.0046336.3G 13.7G 73992 S  0.7 21.5  1:04.36 /vol/isy-rl/dtr0169M  331M  9752 S  0.774699236 D  0.775 0.0|2.6|7  0 0.0|7|7||1.3| 3.325046496.3G 13.7G 73992 S2146 /vol/isy-rl/dtr35D 0.947002065M  304M  9732 D  1.3  0.5  0:00.86 python3 main.py46336.3G 13.7G 739921.5  1:04.37 /vol/isy-rl/dtr4752 S 1.019144M  366S 6  0:01.397001D 86700327M  358M  9736687005073M  304M  97285  0:00.83 1.3 0||2|1.3 0|||9426993065M  304M  9756 D  2.0  097 python3 main.py79M  3081.213127M  3606 S 690[18[125065M  3045  0:00.746999144M  368S 6  0:01.400065M  304M  9752577469M  308M  969290|7 0.0|0.7 0| 0.7|7| 2.024 3.37 1.2434636.3G 13.7G 73992 S  0.7 21.5  1:04.39 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 210.47 /vol/isy-rl/dtr6996065M  304M  9752 S  0.7  0.5  0:01.076997069M  308M  9752 D  0.7  0.5  0:01.22 python3 main.py7003127M  362M  97366  0:00.9170049M  308M  96991 0||2.7||1.3  0||3.3||2| 07356995065M  304M  9752 D  2.0  0.5  0:00.77 python3 main.py7002065M  304M  9732 D  2.0  089 python3 main.py18M  307M  9736 D  1.30.625M  304M  9736 D  1.30.77699065M  304M  9756 D  1.3  0.5915M  304M  9752 D  1.3885.3  0.0|7|7 2.7| 0.7 0||5.29566S1.10[92S 9356 S 1.017000S 74614 260M 93208 22004 S  0.7  0.1  0:06.63 /usr/bin/python46336.3G 13.7G 73992 S  0.7 21.5  1:04.41 /vol/isy-rl/dtr490:00.48 /vol/isy-rl/dtr72321M  356M 631966  0:02.510137S 0.7569925M  304M  97367869971069M  308M  9752 S 5  0:01.24 python3 main.py2486999 dtrofimov 1144M  373M  97527  0.6  0:01.41 python3 main.p  0.0 0|7.3 0|7| 2.08427.9258700336 D  5.30699652 R  3.31.1570049M  308M  9692 D  2.09552 D 0.7946336.3G 13.7G 73992 S  0.7 21.5  1:04.42 /vol/isy-rl/dtr69911068M  307M  97365  0:00.70 python3 main.py699065M  304M  9756 0.5  0:01.02 python3 main.py6994067M  304M  975 01.04 python3 main.py98149M  313M  97525  0:00.84944M  3746  0:01.42700058070015M  304D 0.90

2484633 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  1:04.46 /vol/isy-rl/dtr46496.3G 13.7G 739922150 /vol/isy-rl/dtr7  0.0 0  0.0||2.7 09752 D  2.0718M  307M  9736 S  10.7269935M  304M  9756 D  1.31.04[816996065M  304M  9752 D  1.3  0.5  0:01.17 python3 main.py70025M  3042 S  1.39470049M  308M  9692 D  1.30.9770057328 S  1.30.8946336.3G 13.7G 739921.5  1:04.43 /vol/isy-rl/dtr4646.3G 13.7G 739921.5  0:00.49 /vol/isy-rl/dtr699236 D 7906 S 8147:0170035M  304M  9736 D  1.3246336.3G 13.7G 73992 S  0.7 21.5  1:04.44 /vol/isy-rl/dtr0169M  3422 S  0.70.7618M  307M  9736 D  0.7738149M  317S  0.70.856999144M  379M  9752 S  0.7  0.6  0:01.4305M  304M  9756 S  0.78260.790712634256  4744  3628 R  0.7  0.0  0:00.26 htop|1.3||3.3||1.3|| 0| 228.16 3.50 1.302699952 R  4.0496998149M  321M  9752 S  2.0  0.5  0:00.88 python3 main.py7004008M  9692 D  1.39946336.3G 13.7G 73992 S  0.7 21.5  1:04.45 /vol/isy-rl/dtr069M  346777000065M  30465  0:00.8920 _rpc       20   0  8100  1308   876 S  0.0  0.0  0:02.59 /sbin/rpcbind -921 systemd-o  20   0 14828  1664   864 S  0.0  0.0 28:40.44 /lib/systemd/sy931 root       20   0  313M  5032  3356 S  0.0  0.0  0:12.05 /usr/sbin/rpc.gM 0.05|   0.0|7||2||514D  2.7537005073M  312M  9728 D  2.7946990152M  9752 S 676998149M  326M  9752 S  1.3  0.5  0:00.90 python3 main.py700065M  3046 D  1.385  0.0||2.7|7 0  0  0.050169M  360S  2.0  0.6  0:00.826998149M  334M  9752 S  1.32331:04.47 /vol/isy-rl/dtr931 root       20   0  313M  5032  3356 S  0.0  0.0  0:12.05 /usr/sbin/rpc.g932 root       20   0  313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g1145 root       20   0  2808    92     0 S  0.0  0.0  0:00.25 /usr/sbin/acpid1148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --|7|70||1.3|7|7|7|1.437849M  3437  0.596069M  3682.0  0.6857001065M  304M  9752 D  2.0  0.5  0:00.94 python3 main.py2487002 dtrofimov  20   0 1065M  304M  9732 D  1.3  0.5  0:00.96 python3 main.py2484649 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  0:00.51 /vol/isy-rl/dtr2487000 dtrofimov  20   0 1065M  304M  9756 D  0.7  0.5  0:00.86 python3 main.py2487126 dtrofimov  20   0 34256  4744  3628 R  0.7  0.0  0:00.27 htop
2486999 dtrofimov  20   0 1065M  304M  9752 D  2.0  0.5  0:01.56 python3 main.py2486993 dtrofimov  20   0 1065M  304M  9756 D  1.3  0.5  0:01.06 python3 main.py2486998 dtrofimov  20   0 1149M  359M  9752 S  1.3  0.6  0:00.99 python3 main.py261695 gdm        20   0 37164  1916   820 S  0.7  0.0  0:06.33 /usr/bin/pipewi96065M  304D 5  0:01.1970025M  304M  9732 S 0.97700336037004069M  308M  9695  0:01.003356 S  0.0  0.0  0:12.05 /usr/sbin/rpc.g|7||3.3||1.3||2|2.0||2||1.3|7|72.79100182S  2.7  0.6  0:00.90
2484614 dtrofimov  20   0  260M 93196 21992 S  0.7  0.1  0:06.64 /usr/bin/python2464916.3G 13.7G 73992 S  0.7 21.553 /vol/isy-rl/dtr92112634256  4744  3628 R 0  0:00.28 htop889 root       20   0  4816  1232   900 S  0.0  0.0  0:00.00 /usr/sbin/rpc.s 0||1.3||2|7 0|7| 0.7[29.30 3.89 1.463972.08722.0746336.3G 13.7G 73992 S  0.7 21.5  1:04.51 /vol/isy-rl/dtr9920 _rpc       20   0  8100  1308   876 S  0.0  0.0  0:02.59 /sbin/rpcbind -921 systemd-o  20   0 14828  1664   864 S  0.0  0.0 28:40.45 /lib/systemd/sy931 root       20   0  313M  5032  3356 S  0.0  0.0  0:12.05 /usr/sbin/rpc.g932 root       20   0  313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g1145 root       20   0  2808    92     0 S  0.0  0.0  0:00.25 /usr/sbin/acpidM2.0 0.7 0 0|7 0 0440571.02801.39
    889 root       4816  1232   900 S  0.0  0.000 /usr/sbin/rpc.s    920 _rpc       8100  1308   8760  0.0  0:02.59 /sbin/rpcbind -    921 systemd-o 14828  1664   8640  0.0 28:40.45 /lib/systemd/sy    931 root       313M  5032  3356 S  0.0  0.0  0:12.05 /usr/sbin/rpc.g932313M  5032  335602.20 /usr/sbin/rpc.g114520   0  2808    92     0 0  0:00.25 /usr/sbin/acpid1148 messagebu7920  3992  125.98 @dbus-daemon --;1H30m1.3|7|7|7 0|7360 4.04 1.527236 S  1.30.81 0.0 0.0 0|2.0 0.0| 0|7 0|7 02946336.3G 13.7G 7399221.5  1:04.55 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 2155 /vol/isy-rl/dtr69965M  304M  975282921 systemd-o  20   0 14828  1664   864 S  0.0  0.0 28:40.45 /lib/systemd/sy931 root       20   0  313M  5032  3356 S  0.0  0.0  0:12.05 /usr/sbin/rpc.g932 root       20   0  313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g1145 root       20   0  2808    92     0 S  0.0  0.0  0:00.25 /usr/sbin/acpid1148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --  0 032207005073M  312M  9728 D  0.7  0.5  0:00.96 python3 main.py712634256  4744  3628 R  0.7  0.031 htop726334536  5012  3616 R 001 htop|7|2.6|1.3|1.3|7||2.7|7|7|1.3|742699065M  304M  9752 D  21.1869931065M  304M  9756 S  2.0  0.5  0:01.09 python3 main.py69961065M  304M  9752 D  2.0  0.5  0:01.22 python3 main.py2486998 dtrofimov 1065M  304M  9752 D  25  0:01.25 python3 main.p 0|0.7 0.0|7|0.7 0 0 0 0 0.0 0610.19 4.26 1.60 336 D  1.317874044812  9412  6744 S  0.7  0.0  0:00.92 sshd: dtrofimov46336.3G 13.7G 73992 S  0.7 21.5  1:04.57 /vol/isy-rl/dtr      1 root       164M  9544  4144 S  00  0:39.97 /lib/systemd/s
 0 0| 0 054636.3G 13.7G 73992 S  0.7 21.5  1:04.58 /vol/isy-rl/dtr8712634256  4744  3628 R 32 htop1154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.55 /usr/sbin/irqba
2487126 dtrofimov  20   0 34256  4744  3628 R  0.7  0.0  0:00.34 htop726334536  5012  3616 R  0.7  0.004 htop[m 0.7  0.0  0:00.33 htop324r|7|7|7|7|7 0|790 4.50 1.78331:04.59 0| 0 0 0960|7 0 031[1[191148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --1154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.55 /usr/sbin/irqbaM||1.3|7|71.55 4.74 1.792[2  0.0 0 0414 260M 93196 21 0.1  0:06.66 /usr/bin/python463316.3G 13.7G 73992 S  0.7 21.5  1:04.63 /vol/isy-rl/dtr464916.3G 13.7G 73992 S  0.7 21.560 /vol/isy-rl/dtr

2484633 dtrofimov 16.3G 13.7G 7399221.5  1:04.73 /vol/isy-rl/dtr490:00.65 /vol/isy-rl/dtr8D 99299101321M  356M 63196 S  0.7  0.6  0:02.52 python3 main.pm1065M  304M  9752 D  25  0:00.97 python3 main.py2487002 dtrofimov 1065M  304M  9732 D  25  0:01.01 python3 main.py[2;45H|2|7|1.3|7.3|7|1.3||1.3|7|1.3||1.3||3.3|1.3||3.33406995098M  307M  9756 S  4.0  0.5  0:00.89 python3 main.py69901065M  304M  9752 D  3.3  0.5  0:01.23 python3 main.py2487004 dtrofimov 1069M  308M  9692 D  3.3  0.5  0:01.06 python3 main.p|0.74.00.70.730.7  0.0 0.0| 0.7  0.00.7| 2.7|7211636 S  2136 S  2.01569905M  304M  9752 S  125699265M  304M  9736 S  10.884112M  312S  1.31512 S  1.3970035M  304S  1.31.1246336.3G 13.7G 73992 S  0.7 21.5  1:04.67 /vol/isy-rl/dtr6097M  3116 S  0.72579M  3080.733S  0.71232 S  0.71.02573M  312M  9728 S  0.72 0 1.4 0 0 0|1 0 0| 0 0|| 01.33 4.933700573M  312M  97281.0502 S  1.32718M  307M  97360.8379M  308M  9752 D 1.357000065M  3046 D 0.93231.044636.3G 13.7G 73992 S  0.7 21.5  1:04.68 /vol/isy-rl/dtr490:00.63 /vol/isy-rl/dtr700165M  30420070035M  304M  9736170049M  308M  96907|7|3.9 3.4||1.3|7||1.3|7| 3.98447979M  3082.03870005M  304M  9756 D  2.09605M  304296993S 1.17699697M  3156276998065M  304M  9752 S  1.3  0.5  0:01.30 python3 main.py699065M  304M  9752 S  1.3  01.63 python3 main.py232 D  1.3649M  308M  9692 S  1.309|6.53|7||3.3|6.0| 0.7 0|2.0 0||3|7336165M  304M  9756 R  3.36742S  2.71.00700232 S  2.71070036 S  2.7700573M  312M  9728 S  2.01246336.3G 13.7G 739921.5  1:04.71 /vol/isy-rl/dtr0D 3169918M  3076 S 0.869985M  304M  975323.24.0|7 0.72 0||7 7|72.7 0210.90 4.95 1.91769982 S  4.03805M  30435109573M  312M  9728 D  2.056992D  1.30.90699769M  308M  9752 D  1.3446999065M  304M  975 0.5  0:01.65 python3 main.py    921 systemd-o 14828  1664   864 S  0.7  0.0 28:40.46 /lib/systemd/s46336.3G 13.7G 73992 S  0.7 21.5  1:04.72 /vol/isy-rl/dtr18M  307M  9736 S  0.70.876993065M  304M  9756 01.18 python3 main.py5098M  31760.91699697M  317M  975628| 0.72.7 0||2.02.0 1.3||1.3|7 0.0 0| |79028D  2.041699236 S  1.30.92699769M  308M  9752 D  1.346700051.0370046913700573M  312M  972817 00 1.30.7|51.3 0.0 0 05018M  307M  97360.91236 S 0.95356 S  2.01.24112M  319S  2.019699697M  320S  2.03269905M  304M  9752 S 40699769M  308M  9752486998065M  304M  9752 D  1.3  0.5  0:01.43 python3 main.py7000065M  304M  9756 S  1.3  01.05 python3 main.py70049M  308M  9692 D  1.31.154636.3G 13.7G 73992 S  0.7 21.5  1:04.74 /vol/isy-rl/dtr700265M  304M  97321.1700365M  304M  9736 D 18|2.66|0.7|1.3 4.0|[|1.3|1.3||02[479M  308M  97521.5192 D 69700345M  305M  974021265M  304M  9736 S  1.30.9736 D 24598M  32260.94[15D 7S 77005073M  312M  9728 D  1.3  0.5  0:01.19 python3 main.py46336.3G 13.7G 739921.5  1:04.75 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 210.66 /vol/isy-rl/dtr

   2055 rtkit      RT   1  150M   224     0 0.0  0:19.49 /usr/libexec/rt46336.3G 13.7G 739921.5  1:04.86 /vol/isy-rl/dtr4635 260M 93196 219921  0:00.12 /usr/bin/python4646.3G 13.7G 7399210.72 /vol/isy-rl/dtr699123M  3072 S 59699068M  307M  9736 D 169925M  304M  9740 D 099;29H73M  312M  9728 S 21461 260M 93196 2190.7  0.1  0:06.67 /usr/bin/python46336.3G 13.7G 73992 S  0.7 21.5  1:04.76 /vol/isy-rl/dtr6991068M  307M  9736 0.5  0:00.95 python3 main.py6994112M  322M  975 01.21 python3 main.py 2.7  0.0||2|74 0 0.0 0.0 02.0 0570015718699327700232 S  2.017065M  30421.44D 9S 349M  308M  9692 D 21|7|5.3| 0.7 0|2.7||70366998537002327149M  308M  96972518M  307M  9736 D  2.00.9870016 S  2.02104669925M  304M  9740 S 021.3  0.0 0|7|7  0| 3.33814 4.98 1.9587001D  2.0240469905M  304M  9752 S  1.348S  1.31.00699697M  3281.33770049M  308M  9692746496.3G 13.7G 73992 S  0.7 210.68 /vol/isy-rl/dtr6995098M  328M  9756 0.5  0:00.99 python3 main.py9065M  3047570073M  312M  97281.24|||7||2.0|70.7 0||1.3|7|2.09232 S  3.39699697M  329M  975674146336.3G 13.7G 739921.5  1:04.80 /vol/isy-rl/dtr05M  304M  9752 D 5168M  307M  9730215M  304M  9756 D 6[19265M  304M  97401.034112M  3272469998M  330M  975600| 0.7||7.9| 0.7|1.32.0  0.0||7 0 0||1.38:01699052 S  2.754865M  304587000065M  304M  9756 S  2.7  0.5  0:01.14 python3 main.py700232 S  2.032697M  331M  97543S 87004069M  308M  9692 D  1.3  01.29 python3 main.py700573M  312M  9728 S  1.326 0 2.0||2.0 0.0 0|7| 0|22.0[29.32 4.90 1.94 218M  307M  9736006116M  306061699697M  3311.3451.34700469M  308M  96923146496.3G 13.7G 73992 S  0.7 210.70 /vol/isy-rl/dtr699112M  330M  9752 S  0.7569998M  3356 S  0.701|7|1.3| ||2|7 0|1.30.7| 3.394697M  332M  9754894065M  304256[1646336.3G 13.7G 7390.7 21.5  1:04.82 /vol/isy-rl/dtr6991068M  307M  9736 01.07 python3 main.py2065M  304M  97400365M  304297000065M  30415D 30764069M  308M  96925  0:01.32 python3 main.py0051073M  312M  9728 S 5  0:01.27 python3 main.py2.7|7|| 1.4 0| 0.7|7||2.65365M  304D3270011M  3043346336.3G 13.7G 739921.5  1:04.84 /vol/isy-rl/dtr69901235586991068M  307M  9736 S  1.3  0.5  0:01.09 python3 main.py7126M  321M  9756 S  1.3598116M  311M  9756 S  1.36692 D  1.37746496.3G 13.7G 73992210.71 /vol/isy-rl/dtr23275073M  312M  97288 0 0 01.32.0 01.3| 3.3718M  307M  9736 S  2.713699206540 D 08699065M  304M  9756 D  2.0  0.5  0:01.35 python3 main.py5098M  3356037126M  322M  975617002065M  304M  9732346336.3G 13.7G 73992 S  0.7 21.5  1:04.85 /vol/isy-rl/dtr4112M  33S  0.7266998116M  312M  9756 01.67 python3 main.py699952 S 78065M  304M  9756 D 16|62.0|7|4.6| 0.01.4408.986865M  304M  9756 D52952782700232 S  2.7438116M  314697000065M  304D 183145M  319M  974028

      1 root       164M  9544  4144 S  0.0  0.0  0:39.97 /lib/systemd/s[36m065M  304M  9740 0.5  0:01.10 python3 main.py69931065M  304M  9756 D 5  0:01.36 python3 main.py6997126M  325M  9756 01.63 python3 main.py700111M  30863570049M  308M  9692 S 35m2 S  2.030S 20699023M  310M  9752 S  0.760
    931 root       313M  5032  330  0.0  0:12.05 /usr/sbin/rpc.g    932 root       313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g 920 _rpc       8100  1308   876 S  0.0  0.0  0:02.59 /sbin/rpcbind -    921 systemd-o 14828  1664   864 S  0.0  0.0 28:40.47 /lib/systemd/s23;61H2.20 /usr/sbin/rpc.g/vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 210.73 /vol/isy-rl/dtr214112M  340M  9752 S 318116M  319M  97567700345M  324M  974034069692612634256  4744  3628 R 0  0:00.43 htop657 root       19  -1  252M  181M  179M S  0.0  0.3  1:09.35 /lib/systemd/sy 0 1.4|7 0| 0.729.14 5.00 2.00346336.3G 13.7G 73992 S  0.7 21.5  1:04.88 /vol/isy-rl/dtr699023M  3142 S  0.76269911068M  307M  9736 R 5  0:01.16 python3 main.py699065M  304M  9756 0.5  0:01.37 python3 main.py6994112M  344M  975 01.32 python3 main.py76M  3296486M  3216770011M  3133864[17353536  4956  3556 S 01|1.3||7|2.0|7|7 0147896049180 13800  6816 0.0  0:00.81 sshd: dtrofimov46336.3G 13.7G 739921.5  1:04.89 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 210.74 /vol/isy-rl/dtr240 D 13726M  332665700111M  316397004069M  308M  9692380.7|7|| 0 0 0 06869941112M  348M  9752 S  1.3  0.5  0:01.34 python3 main.py6998116M  325M  9756 S  1.3  0.5  0:01.73 python3 main.py331:04.90 /vol/isy-rl/dtr0123M  318M  9752 S 65065M  304D 096996065M  304D 536997126M  335M  975666 0 03.3|7221 5.09 2.05746496.3G 13.7G 73992 S  0.7 210.75 /vol/isy-rl/dtr42M  3512 R  0.7357001111M  320M  9756 0.5  0:01.40 python3 main.py700345M  333M  974036735334536  4956  3556 S 0  0:00.02 htop||6.12.0||2.7|7|7||3.340196994067M  306M  9752 D  4.0  01.41 python3 main.py700345M  336M  9740 S  2406995065M  304D  1.311699726M  340M  9756 S  1.3680021065M  304M  9732 S  1.3  0.5  0:01.45 python3 main.py2487004 dtrofimov 1069M  308M  9692 D  1.3  0.5  0:01.41 python3 main.p921 systemd-o  20   0 14828  1664   864 S  0.7  0.0 28:40.47  0.0| 0.7| 0|7||1.3 0 04.01207003145M  338M  9740 S  694636.3G 13.7G 73992 S  0.7 21.5  1:04.92 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 210.76 /vol/isy-rl/dtr03M  3262 S  0.751111M  327M  9756 S  0.72
2486997 dtrofimov 1126M  352M  977  0.6  0:01.70 python3 main.py2486999 dtrofimov 1065M  304M  9752 D  0.7  0.5  0:01.84 python3 main.py2487002 dtrofimov 1065M  304M  9732 D  0.7  0.5  0:01.46 python3 main.py0:01.18 python3 main.py2486995 dtrofimov 1065M  304M  9756 D  0.7  0.5  0:01.12 python3 main.pm7||1.3|3.3|7|23959 5.24 2.11393.3826990123M  331M  9752 S  2.0  0.5  0:01.68 python3 main.py6065M  304D  1.3560065M  304D  1.322 0| 0.72.7|7||2|7 0 0|77854067M  3062 S  2.0443065M  3046 D  1.3407003145M  347M  9740 S 349M  308M  9692 S 445073M  312M  9728 D 364636.3G 13.7G 73992 S  0.7 21.5  1:04.95 /vol/isy-rl/dtr490:00.78 /vol/isy-rl/dtr6972321M  356M 63196 0.6  0:02.54 python3 main.py0123M  334M  9752 S 6997S 36065M  3045577126M  3566 S 6716999585|7 4 0|1.3|7|4 0 0.71.3|2 0| 3.3618M  307M  973672247M  3062 S  2.784614 260M 93196 21992 S  2.0  0.1  0:06.71 /usr/bin/python69925M  304M  9740 S  2.017699365M  304M  9756 S  2.0437004069M  308M  962.0  0.5  0:01.47 python3 main.py6996065M  304M  9756 S  1.3  01.59 python3 main.py99065M  304M  9752 S  1.3  0.5  0:01.87700065M  306 S  1.32546336.3G 13.7G 7399221.5  1:04.96 /vol/isy-rl/dtr0123M  335270828116M  346 S 3 02 06 0| 0||1.3||2.06.028.98 5.182825M  304M  974017009M  308M  9695169971126M  359M  97566  0:01.75 python3 main.py952 D 907000D 2825M  304M  9732 D 51700573M  312M  9728 S  2.0400123M  3377269947M  3062 D 506995097M  306M  9756 S  1.3  0.5  0:01.15 python3 main.py46336.3G 13.7G 739921.5  1:04.97 /vol/isy-rl/dtr46496.3G 13.7G 7399221.5  0:00.79 /vol/isy-rl/dtr3065M  3044||1.3|6.0||1.3| 0.72.0|7 2.0|7|7 0.73.3|791918M  307M  9736669925M  304M  9740 D  2.0249065M  304259336 D  1.34669947M  3062 D  1.3526998116M  347M  9756 S  1.385065M  304M  9756 D  1.33700111M  34165070025M  304M  9733700469M  308M  9692 D 537005073M  312M  9728 D  1.3  0.5  0:01.42 python3 main.py7008321M  356M 63196 S  1.3  0.602 python3 main.py4636.3G 13.7G 7399221.5  1:04.98 /vol/isy-rl/dtr| 2  0.0 0 3.3|7 01.3 0|72.01.3| 0.7 083195M  304M  975297700056 S 33240 S  1.32647M  3062 S 5465M  3046 S 670011M  34252232 S 55345M  355M  97406849M  308M  9695573M  312M  9728 S 4446336.3G 13.7G 73992 S  0.7 21.5  1:04.99 /vol/isy-rl/dtr6990123M  340M  9752 S  0.7  0.5  0:01.74 python3 main.py699065M  304M  9756 D  0.7  0.5  0:01.47 python3 main.py|0.7 7|7|7|2.0 0 0.0 01.3 0.0||3.3926 5.09 2.10218M  307M  9736 D307770049M  308M  9692 S  2.75946336.3G 13.7G 739921.5  1:05.01 /vol/isy-rl/dtr240 D 286993065M  304496999599111M  343M  97565425M  304M  9732 S 73145M  357M  9740660490:00.81 /vol/isy-rl/dtr4067M  306558116M  350S 86 05.4|1.3|||1.3 0.0|7| 184S  2.03699240 D  2.0169995M  304M  97502.026994067M  306M  9752 D  1.3  0.5  0:01.57 python3 main.py597M  313M  9756 S 178116M  3518870006 D 32065M  304M  973294614 260M 93196 21992 S  0.7  0.1  0:06.72 /usr/bin/python4636.3G 13.7G 73992 S  0.7 21.5  1:05.02 /vol/isy-rl/dtr6993065M  304M  9756 01.50 python3 main.py7001111M  3456700345M  359M  9740661    931 root       313M  5032  3356 S  0.0  0.0  0:12.05 /usr/sbin/rpc.g932313M  5032  335602.20 /usr/sbin/rpc.g114520   0  2808    92     0 0  0:00.25 /usr/sbin/acpid1148 messagebu7920  3992  125.98 @dbus-daemon --115482808  1192   8121:18.55irqba1158 root258M  8100  454483 /usr/libexec/poroot       20   0  4816  1232   900 S  0.0  0.0  0:00.00 /usr/sbin/rpc.s;4H69921065M  304M  97405  0:01.32 python3 main.py699065M  304M  9756 0.5  0:01.51 python3 main.py7001111M  34662065M  304M  973260602 0| 2.0 0| | 1 0  0|7| 2.06.0970123M  3462 S  1.37679M  3086 D  1.31.869992 D  1.32.07||6.7||2.6 0 0.0|7 0||3.35.9434 5.14 2.1388065M  3046 D  4.09470015M  3044.063700232 S  2.01.64|7 0 0|7|7| 2.64400123M  3532 S  1.3  0.680232 S  1.3646336.3G 13.7G 73992 S  0.7 21.5  1:05.06 /vol/isy-rl/dtr3065M  3046 S  0.753597M  322M  9756 S  0.72112634256  4744  3628 R 0  0:00.50 htop889 root       20   0  4816  1232   900 S  0.0  0.0  0:00.00 /usr/sbin/rpc.s920 _rpc       20   0  8100  1308   876 S  0.0  0.0  0:02.59 /sbin/rpcbind -921 systemd-o  20   0 14828  1664   864 S  0.0  0.0 28:40.47 /lib/systemd/sy931 root       20   0  313M  5032  3356 S  0.0  0.0  0:12.05 /usr/sbin/rpc.g 0|1.3| 0.7|2.7|7|2.60|7381700345M  371M  9740 S  571699597M  326M  9756 S  4.7286994067M  306M  9820 S  1.3  0.5  0:01.61 python3 main.py61.364769M  3081.3870041069M  308M  9692 S  1.3  0.5  0:01.64 python3 main.py2486990 dtrofimov 1123M  357M  97527  0.6  0:01.81 python3 main.p|1.3 0|7|0.7 0||7 04038 5.22 2.1736995097M  330M  9756 S  3533965M  3042 S  22.1135M  304M  9756 D 566.71.40.7 0 0| 1.3834065M  3042 D  4.78956 D  4.01.39700345M  3840 S  27646336.3G 13.7G 73992 S  0.7 21.5  1:05.08 /vol/isy-rl/dtr1065M  304M  9756 D 565920 _rpc       20   0  8100  1308   876 S  0.0  0.0  0:02.59 /sbin/rpcbind -921 systemd-o  20   0 14828  1664   864 S  0.0  0.0 28:40.47 /lib/systemd/sy931 root       20   0  313M  5032  3356 S  0.0  0.0  0:12.05 /usr/sbin/rpc.g932 root       20   0  313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g|70 0.0||7||2.0|746700340 D  6.66712634256  4744  3628 R  1.3  0.0  0:00.52 htop4636.3G 13.7G 73992 S  0.7 21.5  1:05.09 /vol/isy-rl/dtr490:00.85 /vol/isy-rl/dtr69947M  306M  98202 0| 1.3||1.3|1.3|7||2|7 0|7| 1.4 019.07 5.42 2.25769979M  308M  9756 D  2.0900001065M  304M  9756 D  2.0  0.5  0:01.47 python3 main.py6998065M  304M  9756 D  1.3  0.5  0:01.96 python3 main.py331:05.10 /vol/isy-rl/dtr2484649 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  0:00.86 /vol/isy-rl/dtr2486994 dtrofimov  20   0 1067M  306M  9820 D  0.7  0.5  0:01.63 python3 main.py2487002 dtrofimov  20   0 1065M  304M  9732 D  0.7  0.5  0:01.68 python3 main.py7009M  308M  96925 0.0  0.0 0 0.0 0  0 0 0 0.0946336.3G 13.7G 73992 S  0.7 21.5  1:05.11 /vol/isy-rl/dtr      1 root       164M  9544  4144 S  00  0:39.97 /lib/systemd/s|7501.33921 systemd-o  20   0 14828  1664   864 S  0.7  0.0 28:40.48 /lib/systemd/sy2478740 dtrofimov  20   0 44812  9412  6744 S  0.7  0.0  0:00.93 sshd: dtrofimov2484614 dtrofimov  20   0  260M 93196 21992 S  0.7  0.1  0:06.73 /usr/bin/python2484649 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  0:00.87 /vol/isy-rl/dtr2487126 dtrofimov  20   0 34256  4744  3628 R  0.7  0.0  0:00.53 htop 931 313M  5032  33560:12.0rpc.g 932313M  5032  335620 /usr/sbin/rpc.g 0|7|1.320.74464916.3G 13.7G 73992 S  0.7 21.588 /vol/isy-rl/dtr21 systemd-o14828  1664   86428:40.48 /lib/systemd/sy112.05 /usr/sbin/rpc.g932 root       20   0  313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g1145 root       20   0  2808    92     0 S  0.0  0.0  0:00.25 /usr/sbin/acpid1148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --1154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.55 /usr/sbin/irqba    931 root       313M  5032  3356 S  0.0  0.0  0:12.05 /usr/sbin/rpc.g    932 root       313M  5032  3356 S  0.02.20 /usr/sbin/rpc.g11452808    92     000.25 /usr/sbin/acpid1148 messagebu  20   0 37920  3992  1268 0  0:05.98 @dbus-daemon --115482808  1192   8121:18.55 /usr/sbin/irqba1158258M  8100  45442.83libexec/pom4057874136124  7672  4276 S  0.7  0.0  0:00.21 -bash                1 root       164M  9544  4144 S  0.0  0.0  0:39.97 /lib/systemd/s  657 root       19  -1  252M  181M  179M S  0.0  0.3  1:09.35 /lib/systemd/sy    695 root      32872  4400  21680  0.0  0:03.26 /lib/systemd/sy    889 root       4816  1232   9000  0.000 /usr/sbin/rpc.s    920 _rpc       8100  1308   876 S  0.0  0.0  0:02.59 /sbin/rpcbind -    921 systemd-o 14828  1664   864 S  0.0  0.0 28:40.48 /lib/systemd/sM 0||1.368463316.3G 13.7G 7399221.5  1:05.16 /vol/isy-rl/dtr2484649 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  0:00.90 /vol/isy-rl/dtr|7 0|7  0.0 0[210.59 5.87 2.43 8[7[11 0|1.3 029700065M  304M  9740 R  1.3  0.5  0:01.88 python3 main.py331:05.18 /vol/isy-rl/dtr|7|7 0.0|71[29:014636.3G 13.7G 73992 S  0.7 21.5  1:05.19 /vol/isy-rl/dtr490:00.92 /vol/isy-rl/dtr2487003 dtrofimov  20   0 1065M  304M  9740 D  0.7  0.5  0:01.89 python3 main.py2487126 dtrofimov  20   0 34256  4744  3628 R  0.7  0.0  0:00.55 htop||1.3|7 0391.27 6.09 2.522200011065M  304M  9756 D 5  0:01.66 python3 main.py1148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --1154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.55 /usr/sbin/irqba  0.0 0 0|1.34[146496.3G 13.7G 73992 S  0.7 210.93 /vol/isy-rl/dtr

2487002 dtrofimov 1101M  311M  97327  0.5  0:01.86 python3 main.p7 /lib/systemd/sy 1164M  9544  414439.97 /lib/systemd/sy 65719  -1  252M  181M  179M 3  1:09.35 /lib/systemd/sy 695 root     2872  4400  213.26 /lib/systemd/sy 889 4816  1232   9000:00.00rpc.s S  1.3 21.5  1:05.23 /vol/isy-rl/dtr2487126 dtrofimov  20   0 34256  4744  3628 R  0.7  0.0  0:00.57 htop 0 0|773 6.27 2.6080.74464916.3G 13.7G 73992 S  0.7 21.594 /vol/isy-rl/dtr||2.6|7 08106992065M  304M  9740 D  1.3  0.5  0:01.35 python3 main.py7001065M  304M  9756 D  1.3  01.68 python3 main.py2478960 dtrofimov 49180 13800  6816700.82 sshd: dtrofimov2484614 dtrofimov  20   0  260M 93196 21992 S  0.7  0.1  0:06.74 /usr/bin/python2484633 dtrofimov 16.3G 13.7G 739927 21.5  1:05.25 /vol/isy-rl/dtr2486972 dtrofimov 1321M  356M 631967  0.6  0:02.55 python3 main.py2486991 dtrofimov 1068M  307M  9736 D  0.7  0.5  0:01.39 python3 main.py2486997 dtrofimov 1069M  308M  9756 D  0.7  0.5  0:01.91 python3 main.p||4.6||     9.4|1.3|7||4.7|4.7|1.3||2.6||2.6||3.3|2.6|6.6|3.3||4.6||21356 S  566998M  307M  9736 S  4.045869961143M  306M  9756 S  4.0  0.5  0:01.70 python3 main.py70031065M  304M  9740 S  4.0  0.5  0:01.95 python3 main.py7004069M  308M  9692 D  4.0  0.5  0:01.73 python3 main.py90065M  304M  9752 S  3.3  0.5  0:01.9679M  308M  9756 S  3.39685M  304S  3.32.0293.32.16| 2.0       6.6 0.01.32 0.01.3  0.0  0.0 0 0.0|1.30.7| 3.3  00.87 6.18 2.5939D  2.72.207002101M  3042 S  2.7764099M  308M  9820 S  216996143M  307M  9756 S  27369985M  304M  9756 S  22.05700176 S  2.0757004692 S  2.0702 D  11.983S  11.67768M  9756 D  1.3946336.3G 13.7G 73992 S  0.7 21.5  1:05.26 /vol/isy-rl/dtr602573M  312M  9728 S  0531.3|4.7|2.0  0.03.3  0.0  0||4.6479M  308026999065562.2470066927800065M  30422.012100M  307M  97401.40699554746336.3G 13.7G 7391.3 21.5  1:05.28 /vol/isy-rl/dtr36 S 697002101M  305M  97327870035M  304M  97407490:00.97 /vol/isy-rl/dtr6994099M  309M  98207699865M  304M  9756 D 2.063.3|7 0.7|72.0|7|7|7 0.0|73.3262100M  310M  9740 S  4.01.467003400169985M  304M  975602.0936 D  1.31.79065M  304M  9756 D  1.32.267002101M  307M  9732 S  1.3807004069M  308M  96 0.5  0:01.82 python3 main.py02 S  0.72.026994099M  311M  9820 S  0.73699556 R  0.7486997069M  308M  9756 02.03 python3 main.py7000101M  310M  975653700573M  312M  9728 S 1.55 0.06.0 0 0 01.3 0| 0|1.3 0116 6.1185065M  304M  9756 S  3.353699956307002101M  309M  973271.8418M  307M  9736 S  2.0482100M  311M  9740 S 1.486993065M  304M  97567369977562.05700176 S  1.31.7746336.3G 13.7G 7399221.5  1:05.29 /vol/isy-rl/dtr72321M  356M 63196 S 6  0:02.567000101M  3111.544069M  308M  9692812634256  4744  3628 R 0  0:00.59 htop|7 1.3|7|2.02.02902 S  2.72.0618M  307M  9736 S  1.31.56993065M  304M  9756 R  1.37555M  304M  9756 S  1.355643M  312M  97567579M  308D 2.07700573M  312M  97281.5746336.3G 13.7G 73992 S  0.7 21.5  1:05.30 /vol/isy-rl/dtr490:00.98 /vol/isy-rl/dtr98065M  304M  9755101067M  304782101M  310M  9735 0|||1.3|7 3|7 0 0 0.791212100M  313M  9740 S  3.31.532.03S  2.088D  2.02.134099M  314M  9820 S 9365M  304M  97402.037005073M  312M  9728 S  1.3  0.5  0:01.59 python3 main.py331:05.31 /vol/isy-rl/dtr5D 1.566996143M  3161067M  304M  9756792486996 dtrofimov 1143M  327M  97567  0.5  0:01.99 python3 main.p/lib/systemd/s46336.3G 13.7G 739921.5  1:05.39 /vol/isy-rl/dtr2486972 dtrofimov 1321M  356M 631967  0.6  0:02.58 python3 main.pvol/isy-rl/dtr2486992 dtrofimov 1100M  318M  97407  0.5  0:01.56 python3 main.p36 D 565S 1.59865M  304M  9756 S  2.02.162100M  314M  97401.55699561.80699499M  315M  9820776997069M  308M  9756 D  1.3  0.5  0:02.11 python3 main.py7000101M  31S  1.346336.3G 13.7G 7399221.5  1:05.32 /vol/isy-rl/dtr46496.3G 13.7G 73992210.99 /vol/isy-rl/dtr697321M  356M 631966  0:02.57 0 0 0.0 0|1.3|7||3.3[29.74 6.09 2.60 469918M  307M  9736 D  2.71.606143M  3171.81499M  317M  9820 S 8079M  3081.32.13712634256  4744  3628 R  1.3  0.0  0:00.61 htop46336.3G 13.7G 73992 S  0.7 21.5  1:05.33 /vol/isy-rl/dtr02 D  0.72.08865M  304M  9756 D  0.72.170017M  304S  0.71.804069M  308M  9692 S  0.785|74|7|4.7|1.3|1.3 0.7|1.3| 2.7555M  304M  97539065M  304D 2.38065M  304M  9752 D 2.1170035M  304M  9740 D  2.0269941099M  319M  9820 S 5  0:01.82 python3 main.py6997069M  308M  9756 S  1.3  0.5  0:02.15 python3 main.py700573M  312M  9728 S  1.31.61||1.3|1.3||1.31.3|7 0.0 0.0|71.3 0.0||04178S2.226143M  320S  2.01.8570037140 S 569918M  307M  9736 D  1.31.6365M  304M  9756 D 34614 260M 93196 21992 S  0.7  0.1  0:06.75 /usr/bin/python46336.3G 13.7G 73992 S  0.7 21.5  1:05.35 /vol/isy-rl/dtr2484658 dtrofimov 16.3G 13.7G 7399221.5  0:00.18 /vol/isy-rl/dtr6992100M  320M  9740 0.5  0:01.57 python3 main.py699065M  304M  9756 D  0.7  02.39 python3 main.py7001067M  304M  975681700573M  312M  972862| 2.6 32.0|74.0 0||1.3|||71.33820 6.042802 D157005073M  312M  97287666996143M  322M  97561.88[14S 569971069M  308M  9756 S  1.3  0.5  0:02.17 python3 main.py6998065M  304M  9756 S  1.3  0.5  0:02.24 python3 main.py6999065M  304M  9756 S  1.3  02.41 python3 main.py70001M  321M  9756 S  1.3970037140 S  1.31746496.3G 13.7G 739922101 /vol/isy-rl/dtr6992100M  321M  9740 S 58 0.0|4.01.3 0|2|7  0.0 0  02.03018M  307M  9736 S1.686996143M  323M  9756928065M  30472.2995M  306M  9756 S  2.02.47007140 S  2.02.2046336.3G 13.7G 7399221.5  1:05.37 /vol/isy-rl/dtr02 D 1731.876994099M  322M  9820 S  0.78369956556 S  0.71.657001067M  304M  9756 083 python3 main.py700132870049M  308M  969287| 0.7  1.3 0|70.7| 699135M  304M  9756 S  3.3927003071M  304M  974002.23700573M  312M  972801.706143M  3241.31.92101M  322M  9732 S  1.31.90.7846496.3G 13.7G 73992 S  0.7 211.02 /vol/isy-rl/dtr2100M  323M  9740 S  0.759565M  304M  9756668D 2.29699995M  3082.4503M  97566017M  304M  97564|7||2.0|2.63|7||1.3 00|788.87 6.02 2.6236143M  3262.78699065520469M  308M  9692 D 917005073M  312M  9728 D 726994099M  327M  9820 S  0.7846995065M  304M  9756 0.5  0:01.67 python3 main.py6998065M  304M  9756 02.30 python3 main.py70001M  324M  97566170017857002101M  323M  9732 S 1.912.63.4|71.4|2| 0 0.7|1.32.0||3.3 0941068M  307M  9737236 D  2.71.9669905M  304M  9752.23699865M  304M  9756 S  2.02.3370069M  308M  9692 S  2.0970073M  312M  9728 S  2.07579M  3081.31925M  9732 S  1.393

    657 root       19  -1  252M  181M  179M S  0.0  0.3  1:09.35 /lib/systemd/sy[H6336.3G 13.7G 739921.5  1:05.42 /vol/isy-rl/dtr699168M  307M  9740827M  306M  975677003071M  304M  97402.24||3.4| 0.7 3.3|7 0|1.3|7||2 02.0769977562.248S  2.72.3770017M  3066 D  2.71.912.077004069M  308M  9692 D  1.3  0.5  0:02.00 python3 main.py46496.3G 13.7G 739922103 /vol/isy-rl/dtr065M  304M  9752 D 2.22100M  328M  974013065M  3046143M  329S 01582101M  327M  97329446734536  4996  3600  0:00.02 htop 01.3||1.3|1 0|0.7 0  03.94040 5.973918M  307M  9740 D1.816143M  3300546336.3G 13.7G 73992 S  0.7 21.5  1:05.41 /vol/isy-rl/dtr2100M  3300.76269935M  304M  9756 S  0.716994099M  331M  9820 087 python3 main.py56 S 1.698065M  304M  97562.387000101M  3291.63700201M  328M  97321.95700573M  312M  97281.764.0| 0.7|7|7 0|7|7||2.6394079M  308M  9756 S2.280065M  30420296996143M  332M  9756 S  2.0  0.5  0:02.08 python3 main.py7001067M  306M  9756 S  2.0942100M  332M  9740 S  1.31.6495M  318M  9756 S  1.32.5070037140 S  1.32.2670049M  308M  9692 S  1.302 1.3 0 0.7 0|7 0|7 004027002101M  332M  97321.9936047069M  30831699995M  3192.53643562.10700167M  306D 1.96469M  308M  96920446336.3G 13.7G 7390.7 21.5  1:05.43 /vol/isy-rl/dtr2484649 dtrofimov 16.3G 13.7G 7399221.5  0:01.04 /vol/isy-rl/dtr6990065M  304M  975 0.5  0:02.30 python3 main.py7000101M  332M  975664
    889 root       4816  1232   9000  0.0  0:00.00 /usr/sbin/rpc.s    920 _rpc       8100  1308   8760  0.059 /sbin/rpcbind -    921 systemd-o 14828  1664   864 S  0.028:40.49 /lib/systemd/sy;5H0051073M  312M  9728 S 5  0:01.77 python3 main.py8H065M  304446336.3G 13.7G 73992 S  0.7 21.5  1:05.44 /vol/isy-rl/dtr69955M  304M  9756 S  0.71.707000101M  334M  9756 065 python3 main.py70017M  3066 D 1.9712634256  4744  3628 R 0  0:00.65 htop695 root       20   0 32872  4400  2168 S  0.0  0.0  0:03.26 /lib/systemd/sy|3.3||1.3||3.3||1.3|7||1.30.7||3.95769M  3087376990065M  304M  9753362.0585M  304S 42995M  322587001067M  306M  9756 S  1.3  0.5  0:01.99 python3 main.py70049M  308M  9692 S  1.32.06 0.72.0| 0.7 0  0.0 0| 36.040605M  304270017M  306670785D 1.74614 260M 93196 21992 S  0.7  0.1  0:06.76 /usr/bin/python46336.3G 13.7G 73992 S  0.7 21.5  1:05.46 /vol/isy-rl/dtr46496.3G 13.7G 7390.7 211.06 /vol/isy-rl/dtr6991068M  307M  9740 D  0.7  0.5  0:01.83 python3 main.py6993065M  304M  9756 02.05 python3 main.py769M  308M  97562.386999095M  323M  9756590101M  337M  975666|2.6|5.4| |7 |7|7 0|1.3||1.3||2.65.9388148240 D1.686994820 D  2.01.925065M  304D 1.7579M  308S  2.02.4169901065M  304M  9752 D  1.3  0.5  0:02.39 python3 main.py699065M  304M  9756 S  1.3  0.5  0:02.07 python3 main.py7003071M  305M  9740 S  1.3  02.28 python3 main.py46336.3G 13.7G 73992 S  0.7 21.5  1:05.47 /vol/isy-rl/dtr46496.3G 13.7G 73992211.07 /vol/isy-rl/dtr18M  307M  97401.846143M  33816998065M  304D 2.436999095M  324M  975660 0.04.70.71.3|1.3 0||1.3|7|7|0.7 0.779979M  308M  9756 S  4.62.470005M  304M  9756 D  3.376143M  341S  2.72.2346336.3G 13.7G 73992 S  0.7 21.5  1:05.48 /vol/isy-rl/dtr18M  307M  9740 D  0.71.85240 D  0.71.6969965M  304M  9756 D  0.706995065M  304M  9756 D  0.7  0.5  0:01.76 python3 main.py6998065M  304M  9756 D  0.7  02.44 python3 main.py995M  32562.61700201M  340M  973206700371M  307M  9740 S 29712634256  4744  3628 R 0  0:00.67 htop||2.0 0.0||2.0  0.0 0|1.3 0 0| 1.4841517556996143M  345S 2.287002065M  304M  9732 D  3.311700071M  310M  9740 D  3.3  0.5  0:02.34 python3 main.py46336.3G 13.7G 73992 S  0.7 21.5  1:05.49 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 2108 /vol/isy-rl/dtr2401.70

2487001 dtrofimov  20   0 1067M  306M  9756 S  0.7  0.5  0:02.05 python3 main.py2487003 dtrofimov  20   0 1071M  310M  9740 D  0.7  0.5  0:02.35 python3 main.py2487004 dtrofimov  20   0 1069M  308M  9692 S  0.7  0.5  0:02.09 python3 main.py 0  0.0 0 0|| 0 0146336.3G 13.7G 73992 S  0.7 21.5  1:05.56 /vol/isy-rl/dtr490:01.12 /vol/isy-rl/dtr932 root       20   0  313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g1145 root       20   0  2808    92     0 S  0.0  0.0  0:00.25 /usr/sbin/acpid1148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --1154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.55 /usr/sbin/irqba;17H7 0.78397065M  304D  65517005073M  312M  9728 D  1.3  0.5  0:01.81 python3 main.py2484633 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  1:05.53 /vol/isy-rl/dtr2484649 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  0:01.10 /vol/isy-rl/dtr2487000 dtrofimov  20   0 1065M  304M  9756 D  0.7  0.5  0:01.73 python3 main.py2487126 dtrofimov  20   0 34256  4744  3628 R  0.7  0.0  0:00.69 htop  0.0|||7|0.7 0 09.01 6.24 2.78846336.3G 13.7G 73992 S  0.7 21.5  1:05.54 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 2111 /vol/isy-rl/dtr0001065M  304M  9756 D 5  0:01.74 python3 main.py932 root       20   0  313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g1145 root       20   0  2808    92     0 S  0.0  0.0  0:00.25 /usr/sbin/acpid1148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --|7||1.3|7|7| 0.7 0 0|7|7|7|7810:006999065M  304M  9756 D  1.3  0.5  0:02.66 python3 main.py331:05.55 /vol/isy-rl/dtr69982.46|1.3 0|7 0|1.3 057 6.40 2.8537002065M  304M  9732 D  1.3  0.5  0:02.13 python3 main.py14 260M 93196 21 0.1  0:06.77 /usr/bin/python2486992 dtrofimov  20   0 1065M  304M  9740 D  0.7  0.5  0:01.71 python3 main.py2487126 dtrofimov  20   0 34256  4744  3628 R  0.7  0.0  0:00.70 htop
    931 root       313M  5032  3356 S  0.0  0.0  0:12.05 /usr/sbin/rpc.g    932 root       313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g   1145 root       2808    92     0 S  0.025 /usr/sbin/acpid1148 messagebu37920  3992  126805.98 @dbus-daemon --115420   0 82808  1192   812 0  1:18.55 /usr/sbin/irqba3;35H0 0 0[166 0|7[210.08 6.56 2.92 7926256M  2840  18280:52.42libexec/ac601148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --1154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.55 /usr/sbin/irqba|7||2|7||3.3|7|7|7|7409 0 0  0.0 0 0 0|7 0 011046496.3G 13.7G 73992 S  0.7 211.16 /vol/isy-rl/dtr69935M  304D  0.79

2487001 dtrofimov 1067M  306M  9756 S  25  0:02.32 python3 main.py6996065M  304M  9756 D  2.0  0.5  0:02.73 python3 main.py699065M  304M  9756 D  2.0  02.86 python3 main.py85M  304M  9756 S  1.32.65700071M  310M  9740 D  1.35070049M  308M  9692 S  1.32846336.3G 13.7G 7399221.5  1:05.76 /vol/isy-rl/dtr2401.905196M  323M  97289Hm/vol/isy-rl/dtr[31mD  2.01.947M  306M  9820 D  2.007|76[6[18||4||8.8||1.3|1.3|2.7|3.3|1.3||2||4||3.3|7|1.35.3|2||5.3|7399.93 6.65 2.99 86992065M  304M  9740 S  4.0  0.5  0:01.78 python3 main.py6995065M  304M  9756 S  4.0  083 python3 main.py2486999 dtrofimov 1065M  304M  9756 D  45  0:02.72 python3 main.p64.0  0.0 0.0 0.01 0.0| 0.7  0 2.6 0|0.70.7 0.02.0 08947M  306M  9820 S  22.02622.61S  2570017M  3062.0670025M  304M  9732 S  2.0206992 S  12.466993102M  3051686 S  1.35270005M  304M  9756 S  1.3146336.3G 13.7G 73992 S  0.7 21.5  1:05.68 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 211.19 /vol/isy-rl/dtr18M  307M  9740 D  01.969940 D  01.792.0 1.3|7|7|3|7|1.3 0.0 0 0|7| 0.7921700175672070049M  308M  96927207002144M  306M  9732236994820 D  1.304699956 S  1.3770.7 2.7  0.0|4.0 0|7| 0.7 0.0 02.0382470017M  3066 D2705202.5699565M  304M  975601.9070049M  308M  9692 S 2.237005196M  315M  9728 S 1.911.371.9||7 02.61.3|2.0|7||1.39155196M  317M  9728 S  3.31.96[163102M  3112.2105M  304M  9756 D 1.886991068M  307M  9740 D  1.36[19 0.0 4.1|7|1.3 0.7 0 0 0.7| 876996065M  304M  9756 S  2.72.693469918M  307M  9740 S  1.3925M  304859827000S 1.9469M  308M  9692 S 23[125065M  304M  97561.9179M  308S 96998065M  304M  975660|2.0 0| 0 0||1.3 0|7||3.347 6.67 3.038020266 D 62065M  304M  9740 S  1.31.8755M  304M  97563700056 S 927002144M  313M  97322846336.3G 13.7G 73992 S  0.7 21.5  1:05.74 /vol/isy-rl/dtr6972321M  356M 63196 S  0.7  0.6606994161M  311M  9820 0.5  0:02.10 python3 main.py6997069M  308M  9756 02.70 python3 main.py8D 2.6700371M  310M  974048712634256  4744  3628 R 0  0:00.76 htop|71.3 0.0|[  0.0|7 01.49305671.9702 S 5D 982.6 0 4.1 5.4|7||1.32.781022.6918M  307M  9740703556 S  2.72.0170002.71.97|3.4|7|3.3|72.0 0||74.6|7903 6.62 3.04367395M  304M  97569024001.936995D  2.02.04371M  310M  974005370049M  308M  96923118M  307M  9740 S  1.3054161M  315M  982012699665M  304M  97567546336.3G 13.7G 7390.7 21.5  1:05.77 /vol/isy-rl/dtr490:01.24 /vol/isy-rl/dtr79M  308M  97562.726998065M  304M  97562.662.6|7 0  0.0|7| 0  0.0 0| 2.0 04143.3818M  307M  9740 D  1.3074161M  317M  9820 S  1.32.1461.377699965M  304M  9756 D  1.39246336.3G 13.7G 73992 S  0.7 21.5  1:05.78 /vol/isy-rl/dtr25M  3040.71.94302M  321M  9756 S  0.72679M  3080.737002144M  319M  973 0.5  0:02.29 python3 main.py7003071M  310M  9740 D  0.7  02.54 python3 main.py7004692 S 37005196M  325M  972800      1 root       164M  9544  4144 S  0.0  0.0  0:39.98 /lib/systemd/s36m071M  310M  9740 S  1.3  0.5  0:02.70 python3 main.py7004069M  308M  9692 S  1.3  0.54646336.3G 13.7G 7399221.5  1:05.89 /vol/isy-rl/dtr4646.3G 13.7G 73992 S  0.7 211.30 /vol/isy-rl/dtr6993065M  304M  9756 D 4669995M  304M  9756 S 3.091067M  306M  9756 D 45 S  0.7370049M  308M  9692 S  0.7437005196M  343M  9728 S  0.707712634256  4744  3628 R  0.7  0.0  0:00.81 htop 3628 R 0  0:00.78 htop|2.6|7|2.0||1.34||2|71.3 03.99408.87 6.63 3.067D  2.77700371M  310M  9740 S  2.7581068M  307M  9740 D 093102M  32428869961065M  304M  9756 D  1.3  0.5  0:02.79 python3 main.py6999065M  304M  9756 D  1.3  0.5  0:02.94 python3 main.py7004069M  308M  9692 D  1.3  02.35 python3 main.py4614 260M 93196 219921  0:06.79 /usr/bin/python46336.3G 13.7G 7399221.5  1:05.80 /vol/isy-rl/dtr699240 D 66994618201769955M  304M  9756 D 080001065M  304M  9756 S 5  0:01.99 python3 main.py 7 0| 1.3  0.02|7 0.7 0|7| 4.039918M  307M  9740 S  2.012699102M  326M  975603165M  304M  9756 S 819065M  30967000S 0170049M  308M  96923746336.3G 13.7G 73992 S  0.7 21.5  1:05.81 /vol/isy-rl/dtr4916.3G 13.7G 7321.5  0:01.26 /vol/isy-rl/dtr6990065M  304M  9756 D  0.7  0.5  0:02.88 python3 main.py77001067M  306M  975635700371M  310M  974059|0|0.7 0 0|7 0 0.0 0||1.48404161M  324M  982721742401.9970000346336.3G 13.7G 73992 S  0.7 21.5  1:05.82 /vol/isy-rl/dtr69905M  304M  9756 S  0.7896995065M  304M  9756 0.5  0:02.09 python3 main.py6998065M  304M  9756 02.68 python3 main.py70017M  306S 36700144M  326M  9732 S 2.325196M  332M  97280212634256  4744  3628 R 0  0:00.79 htop|2.6 |2.6|3.4 0|2.6|1.32.72700069M  308M  969240065M  304D 922.02.026995D  2.0126999065M  304M  9756 D  2.0  0.5  0:02.99 python3 main.py700371M  310M  9740 D  2.06279M  3081.37770001.30546336.3G 13.7G 7399221.5  1:05.83 /vol/isy-rl/dtr46496.3G 13.7G 7399211.27 /vol/isy-rl/dtr6991068M  307M  9740 D 1369931102M  329M  9756 S 5  0:02.35 python3 main.py2486994 dtrofimov 1161M  326M  98207  0.5  0:02.22 python3 main.p0|3.31.32.0|7|0|0.74056 6.60 3.07369965M  304M  9756 D869S 3.0700056 D 818M  307M  9740 D  1.35700371M  310M  9740 D  1.364 04.63 1.3 0 1.3|||1.36382593.00D 2.956993102M  333S  1.3355M  304M  97564699769M  308M  9756 S 7912.0|4.6|2|1.3|2.01.3  0.04401670017M  3064.02.44 2.0| 0.73.9|7 0 0.0  0||7| 3.338283 6.69 3.128||3.9|4||2.01.3 0|7|0.7 0||99192662.6||1.3|1.3 0| 2.78516136M  309S  4.0964161M  342M  9820 S 308104M  3052.079700596M  351M  9728 S  2.011699265M  304S 06  0.0 0.7|7| 0.7  0.0  0.0  0.0|7||3.3415 6.73 3.152461M  344M  9820 S  233700244M  347M  9732 S  1.341700596M  352M  9728 S  1.3  0.61346336.3G 13.7G 73992 S  0.7 21.5  1:05.90 /vol/isy-rl/dtr18M  307D  0.718699065M  304M  9740 S  0.70769965M  304M  9756 D  0.7476998104M  307M  9756 S  0.7806999065M  304M  9756 0.5  0:03.10 python3 main.py7000065M  304M  9756 02.12 python3 main.py70049M  308M  96927712634256  4744  3628 R 0  0:00.82 htop2487126 dtrofimov 34256  4744  3628 R  0.700.85 htop36M  320M  9756 0.5  0:03.02 python3 main.py7005196M  361M  9728 0.6  0:02.18 python3 main.pym 2036   928 0.0  0:07.13 /usr/bin/pipewi46336.3G 13.7G 7399221.5  1:05.93 /vol/isy-rl/dtr46496.3G 13.7G 73992211.32 /vol/isy-rl/dtr 304S  2.7516995065M  304M  9756 S  2.7226998104M  313M  9756 S  2.7  0.5  0:02.90 python3 main.py6990065M  304M  9756 S  2.0  02.99 python3 main.py7001067M  3061.3481.36;55H0  0:00.83 htop||2.6 5.4|7|7 0|4.7|7|70.7||2|75.2|7972065M  304M  9740 S  2.710065M  304M  9756 S  2.7  0.51670017M  306D 700371M  310M  9740747004069M  308M  9692 D 5118M  307M  9740216996136M  3192.03.016997069M  3056 S  2.0  0.588| 3.24.0|||1.3 3.3 0|||7 0.7 02.7 08222 6.63 3.1489563.16699502S  2.04R  2.07S  2.0479M  308M  9756 S  1.390700244M  356M  9732 S  1.3  0.6  0:02.5218M  307M  9740 S  0.7222065M  3040 S  0.7130.72.530.70.7 0|2.0 0||1.3 01.34.591:00700371M  310M  9740 D2.8170049M  308M  9692 D  2.75869935M  304D 6699565M  304M  9756 S 2946336.3G 13.7G 7390.7 21.5  1:05.94 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 211.33 /vol/isy-rl/dtr6990065M  304M  9756 S  0.7  0.5  0:03.0179M  308M  9756919563.177000177001067M  306M  9756555700244M  357M  97326  0:02.53|1.3| |7 1.3|7|7  0.0 0.02.7811699265M  3041.31446336.3G 13.7G 73992 S  0.7 21.5  1:05.95 /vol/isy-rl/dtr00.73.0218M  307M  9740 D  0.736996136M  324M  9756 0.5  0:03.03 python3 main.py6998104M  317M  9756 02.93 python3 main.py91870005M  304D 1870017M  3062.56371M  310M  97408249M  308M  9692 D 9596M  364M  972819 0 4.70.7 02.7 0 0|7|75.290 6.66 3.173356 S  2.0597000065M  304M  9756 S  2.0  0.5  0:02.21 python3 main.py240 S  1.32.166136M  326M  9756 S  1.33.057069M  3081.32.9700244M  362M  9732 S  1.3  0.65546336.3G 13.7G 7399221.5  1:05.96 /vol/isy-rl/dtr6994161M  358M  9820 S 643D 7S 3[60720|70||2.0|76.6 0|7|1.3 02.740D  2.73.0669918M  307M  974077356 S  2.7637001067M  302.72.617004692 S  2.066997069M  308M  9756596999065M  304M  9756 S  1.3  0.5  0:03.20 python3 main.py7000065M  304M  9756 S  1.3  0.523116M  310M  9740 S  1.3854636.3G 13.7G 7399221.5  1:05.97 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 211.34 /vol/isy-rl/dtr6992065M  304M  97405176991136M  327M  9756 S 5  0:03.06 python3 main.py3.2|2.6|  01.4|7|1.3 0||1.32.63.386S  2.097007M  306M  975606470049M  308M  9692066998M  307M  9740 D  1.32969935M  304M  9756 S  1.356136M  323.0872321M  356M 63196 S  0.7  0.6  0:02.626994161M  360M  9820 S  0.7  0.6446995065M  304M  9756 S  0.7306999065M  304M  9756 0.5  0:03.21 python3 main.py7000065M  304M  9756 02.24 python3 main.py700144M  365M  9732656700316M  311M  97402.80.71.3||1.3|2.7 0 0.0| 0.7|0926 6.70 3.2073.31469979M  308D  2.7996996136M  329M  9756 R 3.11[31D 75065M  304D 2.3299065M  304M  9756 D  1.3  0.5  0:03.23700069M  308M  9692 D  1.3  0.5684614 260M 93196 21992 D 1  0:06.81 /usr/bin/python46336.3G 13.7G 7399221.5  1:05.98 /vol/isy-rl/dtr46496.3G 13.7G 73992211.35 /vol/isy-rl/dtr699065M  304M  9740518699461M  361M  9826452486999 dtrofimov 1102M  314M  97567  0.5  0:03.30 python3 main.pyr/sbin/rpc.smd/sH6993065M  304M  9756 D  0.7  02.75 python3 main.py700409M  315M  96922.74[19;63H17699804M  338M  97563.08244M  382M  9732690031116M  324M  9740 S 5  0:02.91 python3 main.py2487005 dtrofimov 1196M  384M  97287  0.6  0:02.26 python3 main.ptr[m56 S  2.0  0.598y712634256  4744  3628 R 0  0:00.86 htop||4.56.7|7||2.6 0|3 0|2|2.6|7123S  4.01105673.242065M  304M  97407260065M  304M  97567  0.52969931065M  304M  9756 S  2.0  0.5  0:02.71 python3 main.py70049M  308M  9692 S  2.02.7118M  307M  9740 S 2.34699065M  304M  9756535  0.0|3.3 0  0.02.0|71.3 0.0 0| 0[27.60 6.58 3.1832065M  304M  9740 S  2.72.3018M  307M  974002.37700144M  373M  97320  0.66569931.3734161M  367M  9820 S  1.3  0.64805M  304M  9756 S  1.337007M  306M  97566846336.3G 13.7G 73992 S  0.7 21.5  1:06.03 /vol/isy-rl/dtr4646.3G 13.7G 73992 S  0.7 210.11 /vol/isy-rl/dtr4646.3G 13.7G 73992 S  0.7 211.38 /vol/isy-rl/dtr6997105M  3140.73.1269981104M  331M  97565  0:03.01 python3 main.py700116M  318M  9740 0.5  0:02.89 python3 main.py 1||3.3  0 0.0|7|715056 D  1.33.2655M  304M  9756 S  1.3699636M  337M  9756 S  1.3  0.5  0:03.147105M  3153.14804M  332M  97565  0:03.03[1346336.3G 13.7G 73992 S  0.7 21.5  1:06.04 /vol/isy-rl/dtr490:01.39 /vol/isy-rl/dtr6991068M  307M  9740 02.38 python3 main.py6992065M  304M  9740 02.31 python3 main.py7001067M  3062.69700244M  376M  97326  0:02.666321M  356M 631966  0:00.07 python3 main.py2.0 0.7|7|7 0 0 0||3.36240 S  2.02.347105M  3162.03.10065M  3042884M  333057000065M  3042.3546336.3G 13.7G 73992 S  0.7 21.5  1:06.05 /vol/isy-rl/dtr6994161M  369M  9820 0.6  0:02.49 python3 main.py699102M  307M  9756 03.28 python3 main.py7002144M  378M  97326677004109M  311M  969273| 0 0|7| 2.6[26.99 6.47 3.16870017M  306M  975672636M  3411.3646336.3G 13.7G 73992 S  0.7 21.5  1:06.06 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 211.40 /vol/isy-rl/dtr6990.73.2975M  31810065M  304M  9756 D 536244M  380M  973668889 root       20   0  4816  1232   900 S  0.0  0.0  0:00.00 /usr/sbin/rpc.s920 _rpc       20   0  8100  1308   876 S  0.0  0.0  0:02.59 /sbin/rpcbind -|7 1.3|7|7| 0|7||4.096998104M  331.33.077000065M  3042.387001067M  306M  9756 S  1.3  0.5  0:02.74 python3 main.py331:06.07 /vol/isy-rl/dtr18M  307M  9740 D 2.33065M  3042.746994161M  371M  9820 S 650699705M  319M  97565  0:03.19 0|2.0||2.6 0|7 0|7|1.31.4|72210065M  304R3169918M  307M  9740 D 4169925M  304M  9740 D 366995065M  304M  9756 S  1.3  0.5  0:02.39 python3 main.py7105M  320M  9756 S  1.33.217000D  1.3406| 1.3|2.6|7 0 0 0.0| 2.0 00717.07 6.50 3.192700232 D  6.02.787003116M  326S  3967105M  322M  9756 S  2.73.256136M  3462.03.205065M  3042.417M  306S 762.7 0.03.4 0||1.3||3.9154699056 S  23.34699122M  3072.0443087001067M  302.79700232 D  2.0869925M  304M  9740 D 387005196M  388M  9728 S  1.3  0.6  0:02.28 python3 main.py4614 260M 93188 21984 S 1  0:06.85 /usr/bin/python46336.3G 13.7G 73921.5  1:06.09 /vol/isy-rl/dtr2486994 dtrofimov 1161M  375M  98207  0.6  0:02.51 python3 main.p2487005 dtrofimov  20   0 1196M  397M  9728 S  1.3  0.6  0:02.36 python3 main.py2484633 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  1:06.15 /vol/isy-rl/dtr2484649 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  0:01.45 /vol/isy-rl/dtr6999102M  326S 3.3[m816  1232   9000:00.00rpc.s;27H1065M  304M  9756 D  0.7  0.5  0:02.45 python3 main.p04M  9756 0.5  0:02.43 python3 main.py636M  349M  97565  0:03.228104M  3433.09700316M  329M  97402.97 0 0|7 0|7  0.0 0|0.7| 115 6.52 3.2281122M  311M  9740 S  4.02.5383.38|1.3 0|7 0| 03.3830705M  330M  9756 S  1.33.4092M  32112| 2.02|2.6||2.051122M  315M  9740 S  2.02.577002065M  304M  9732 S  2.02.8446336.3G 13.7G 73921.5  1:06.14 /vol/isy-rl/dtr6992065M  304M  9740 S  1.3  0.5  0:02.40 python3 main.py6993065M  304M  9756 D  1.3  02.77 python3 main.py705M  331M  9756 S  1.33.427000065M  304M  9756 S  1.3  0.5446496.3G 13.7G 73992 S  0.7 211.44 /vol/isy-rl/dtr6972321M  356M 63196663|7|||71.3 0.0|0.7|7| 4206332065M  30474417M  306M  9756 D  2.73 0 0.7 0||||1.3|7|7| 01.4141122M  3190616996136M  359S  2.0  0.6  0:03.26
2484633 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  1:06.17 /vol/isy-rl/dtr2484649 dtrofimov 16.3G 13.7G 739927 21.5  0:01.46 /vol/isy-rl/dtr2487001 dtrofimov 1067M  306M  9756 D  0.7  0.5  0:02.84 python3 main.pym692 S  2.081122M  320M  97402.63699461M  388M  9826  0:02.5646336.3G 13.7G 7390.7 21.5  1:06.16 /vol/isy-rl/dtr699902M  328M  9756 S  0.7  0.5  0:03.357005196M  398M  9728 0.6  0:02.37 python3 main.py712634256  4744  3628 R 0  0:00.93 htop889 root       20   0  4816  1232   900 S  0.0  0.0  0:00.00 /usr/sbin/rpc.s| 0.7||4|1.3|1.3|7| 0.7|7 01.3|72.716.97 6.51 3.257636M  3632.7  0.633700409M  332M  96927  0.5  0:02.8569961M  390M  98206598065M  304M  9756 D  2.03.180065M  304M  9756 D 5  0:03.376991122M  321M  9740 S  1.3  0.5  0:02.65 python3 main.py3065M  3041.32.79699065M  304M  9756 D  1.3  0.54869971105M  339M  9756 S  1.3  0.5  0:03.52 python3 main.py2487002 dtrofimov 1072M  304M  9732 S  1.3  0.5  0:02.86 python3 main.p2 0.04 01.31.3| 0| 3.3|7943.3869975M  341M  9756 S  3.33.570065M  304M  9756 S  1.3  0.5  0:03.31122M  322M  9740 S  1.32.673S 2.817000065M  304M  9756467004109M  333M  96928746336.3G 13.7G 73992 S  0.7 21.5  1:06.18 /vol/isy-rl/dtr72321M  356M 63196 S  0.7  0.6  0:02.646996540 S  0.7476995065M  304M  9756 0.5  0:02.49 python3 main.py6998065M  304M  9756 03.19 python3 main.pyS 5|2.0|0.70.7 2.0|7|| 0240643700596M  403M  9728 S  2.7  0.6  0:02.427105M  3422.0607000065M  304M  9756 S  2.04970017M  306D  2.08699D 3.4169982M  305M  97563.21[1946496.3G 13.7G 7399221.5  0:01.47 /vol/isy-rl/dtrD 8[509102M  3333612634256  4744  3628 R 0  0:00.94 htop 0 4.7|7|73.3 0 01.3 0| 0.74022065M  304M  9740 S  2.7  0.5  0:02.52699065M  304M  9756 D 5547000065M  30472.536996136M  3676  0:03.46S 91S 375M  343626998102M  306M  9756 S  1.3  0.5  0:03.23 python3 main.py7008321M  356M 63196 S  1.3  0.6  0:00.04 python3 main.py   1230 root       138M  1780  1004 S 0  2:17.77 /usr/sbin/therm 261812 gdm       3876M  150M 358682  5:55.62 /usr/bin/gnome-4614 260M 93188 219841  0:06.86 /usr/bin/python463316.3G 13.7G 73992 S  0.7 21.5  1:06.20 /vol/isy-rl/dtr|1.3 0|1.32.7||2 0.0||3.313957 6.43 3.24379M  308M  9756 D  4.03.6870017M  306S  2.0969951.36802M  301.3  0.52546336.3G 13.7G 73992 S  0.7 21.5  1:06.21 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 211.48 /vol/isy-rl/dtr122M  325M  9740 S  0.72.693065M  3040.72.86994161M  396M  9820 S  0.72.60 python3 main.py   164M  9544  41400:39.98 /lib/systemd/sy   657 root19  -1  252M  181M  179M S  0.0  0.3  1:09.35 /lib/systemd/sy    695 root      32872  4400  21680  0.0  0:03.26 /lib/systemd/sy    889 root       4816  1232   9000  0.0  0:00.00 /usr/sbin/rpc.s

2486992 dtrofimov  20   0 1065M  304M  9740 D  0.7  0.5  0:02.63 python3 main.py69971517M  331M  97565  0:03.80 python3 main.py7004069M  308M  9692 D  0.7  0.5  0:02.99 python3 main.py21 systemd-o14828  1664   86428:40.54 /lib/systemd/sy3;60H02.20 /usr/sbin/rpc.g11;7H31M  310M  9740 D3.17002072M  304M  9732 S  3.39995M  304M  975673.4699802M  312M  9756 S  1.3  0.53070017M  3069746336.3G 13.7G 73992 S  0.7 21.5  1:06.24 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 211.50 /vol/isy-rl/dtr636M  3740.7  0.6835H0|7| 2.012647M  306M  9820 D  7.32.7146496.3G 13.7G 73992 S  0.7 211.49 /vol/isy-rl/dtr6990065M  304M  9756 D  0.7  0.5  0:03.48 python3 main.py240 S 39102M  339S 387001067M  3062.9527232 S 880031116M  351M  9740 S 5  0:03.05 python3 main.py|1.3| 2.6|7 0|||1.3||7||3.33945 6.41 3.258700272M  304M  9732 S  4.0946991122M  329M  9740 S  2.0  02.72 python3 main.py47M  306M  9820 D  2.02.747003116M  3532.0  0.6  0:03.085065M  3041.32.5969979M  308D  1.33.716998102M  310M  9756 S  1.33.2699902M  3456 S  1.340M 0.0 0.7||0|7 0|7|1.3||4.7||3.3421699665M  304M  975675569965405846336.3G 13.7G 73992 S  0.7 21.5  1:06.25 /vol/isy-rl/dtr40.71D  0.787002072M  304M  973 0.5  0:03.00 python3 main.py7004109M  342M  96 02.89 python3 main.py700596M  413M  97282.446|7 0 0.0  0.02.017.13 6.55 3.3137004109M  346M  9692 S  2.02.92160[1646496.3G 13.7G 73992211.51 /vol/isy-rl/dtr699122M  335M  9740 S 73699467M  306M  9820 D 2.75596M  416M  9728745920 _rpc       20   0  8100  1308   876 S  0.0  0.0  0:02.59 /sbin/rpcbind -921 systemd-o  20   0 14828  1664   864 S  0.0  0.0 28:40.53 /lib/systemd/syM|3.3| 1.3 0| 1.45.964069M  308D  3.37D 2  0.00.7 0|72.76.0646336.3G 13.7G 73992 S  0.7 21.5  1:06.28 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 211.52 /vol/isy-rl/dtr2486991 dtrofimov 1122M  341M  9745  0:02.75 python3 main.py6998102M  326M  9756 0.5  0:03.33 python3 main.py700596M  425M  9728746921 systemd-o  20   0 14828  1664   864 S  0.0  0.0 28:40.53 /lib/systemd/sy931 root       20   0  313M  5032  3356 S  0.0  0.0  0:12.05 /usr/sbin/rpc.g932 root       20   0  313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g|7||2.6||1.3||2|7|7||70477002072M  311M  9732 D  4.0  0.5  0:03.07 python3 main.py6998102M  330M  9756 S  2.7  03.37 python3 main.py700596M  432M  9728 S  2.0  0.7491.99.5  0.0  0 0||1.3|1.31.32.05.9060 6.66 3.37953M  312M  9728 D  9.32.637517M  31676990065M  304M  9756 D  1.3  0.5  0:03.508102M  333397000065M  304M  9756 D  1.3  0.5  0:02.56 python3 main.py46336.3G 13.7G 7399221.5  1:06.30 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 211.53 /vol/isy-rl/dtr2486991 dtrofimov 1122M  346M  97407  0.5  0:02.77 python3 main.p 0.0| 1.3  0.0|7 0.0 0.072:006998102M  337M  9756 S  6.73.491122M  351M  9740 S  1.32.797517M  32S 79M||4.0|7|7 0||2|012065M  304D  6.0583065M  304M  9756 D 8546336.3G 13.7G 73992 S  0.7 21.5  1:06.32 /vol/isy-rl/dtr2486991 dtrofimov 1122M  356M  97406  0:02.80 python3 main.p|2 2.7||2|1.3||7|73.4|7|2808.35 6.83 3.44318M  307M  9740 D  4.72.877517M  341S  2.03.831.340065M  304M  9756 S  1.3  0.5  0:03.5247M  306M  9820 D  1.3797000065M  304D  1.32.5846496.3G 13.7G 73992 S  0.7 211.54 /vol/isy-rl/dtr2486998 dtrofimov  20   0 1065M  304M  9756 D  0.7  0.5  0:03.59 python3 main.py2487002 dtrofimov  20   0 1072M  311M  9732 D  0.7  0.5  0:03.08 python3 main.py2487126 dtrofimov  20   0 34256  4744  3628 R  0.7  0.0  0:01.00 htop

2487005 dtrofimov  20   0 1073M  312M  9728 D  2.7  0.5  0:02.67 python3 main.py2486992 dtrofimov  20   0 1065M  304M  9740 D  1.3  0.5  0:02.65 python3 main.py2486993 dtrofimov  20   0 1065M  304M  9756 D  1.3  0.5  0:02.87 python3 main.py1921 root       20   0  183M 98208  4760 S  0.7  0.1 23:29.28 /usr/libexec/ss4464916.3G 13.7G 73992 S  0.7 21.560 /vol/isy-rl/dtr1H   1145 root       2808    92     0 S  0.00.25 /usr/sbin/acpid1148 messagebu37920  3992  126805.98 @dbus-daemon --115420   0 82808  1192   812 0  1:18.55 /usr/sbin/irqba1158 258M  8100  45442.84 /usr/libexec/po 0||1.3||2|7 0||2.0|79396712.793  0.0  01.3|7 081 6.95 3.5087000072M  3041.3  0.5  0:02.61490:01.56 /vol/isy-rl/dtr6997517M  382M  9756 S 694932 root       20   0  313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g1145 root       20   0  2808    92     0 S  0.0  0.0  0:00.25 /usr/sbin/acpid1148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --M|7||3.30.7 0|7| 1.396997517M  3912.7  0.6  0:03.987000072M  304M  9756 S  2.0  02.64 python3 main.py46336.3G 13.7G 7399221.5  1:06.36 /vol/isy-rl/dtr2487126 dtrofimov  20   0 34256  4744  3628 R  0.7  0.0  0:01.01 htopM|[1 0|||40114004.011.36[17 0||1.31|1.3||2 0| 2.7127000072M  31D  3.3  0.5  0:02.76997517M  4102.0  0.6  0:04.04[18699065M  304M  9756 D  0.7  03.46 python3 main.py712634256  4744  3628 R 0  0:01.02 htopM|1.3|1.3  0.0 0.7|7|2|7|7||1.40.7  0|70399.46 7.12 3.5746997517M  426S  4.0  0.7  0:04.106065M  304D 5  0:03.58 0.0|0.7|2.0 0||1.3 0 0  0.0 0 0 05433.35712634256  4744  3628 R 0  0:01.03 htop932 root       20   0  313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g1145 root       20   0  2808    92     0 S  0.0  0.0  0:00.25 /usr/sbin/acpid1148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --1154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.55 /usr/sbin/irqbaM|1.3  0.0|7|26.07594.021 03.9|7 01.391 7.25 3.6387571.3214 260M 93188 21984 0.1  0:06.88 /usr/bin/python1.3|7 0||2.7209128300.73712634256  4744  3628 R 0  0:01.04 htop|7|7|72.7|2.0|1.3|7| 1.4150746| 0 04.6  0 0.0 0 0.0[210.32 7.38 3.69 32342331:06.45 /vol/isy-rl/dtr931 root       20   0  313M  5032  3356 S  0.0  0.0  0:12.05 /usr/sbin/rpc.g932 root       20   0  313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g1145 root       20   0  2808    92     0 S  0.0  0.0  0:00.25 /usr/sbin/acpid1148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --1154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.55 /usr/sbin/irqbaM||1.31.4|7|74398490:01.61 /vol/isy-rl/dtr2487126 dtrofimov  20   0 34256  4388  3272 R  0.7  0.0  0:01.05 htop
    921 systemd-o 14828  1664   864 S  0.7  0.0 28:40.55 /lib/systemd/s3316.3G 13.7G 7399221.5  1:06.52 /vol/isy-rl/dtr12634256  4388  3272 R 0  0:01.08 htop31 root      313M  5032  3356 0:12.05 /usr/sbin/rpc.g932 root       20   0  313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g1145 root       20   0  2808    92     0 S  0.0  0.0  0:00.25 /usr/sbin/acpid1148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --[36m34256  4388  3272 R  0.7  0.006 htop 0  0 01.33060414490:01.63 /vol/isy-rl/dtr0051073M  312M  9728 D 5  0:02.68 python3 main.py|7|7||1.3|1.3|7||2| 2.02203.3  1.09|72 0||2552811145 root       20   0  2808    92     0 S  0.0  0.0  0:00.25 /usr/sbin/acpid1148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --1154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.55 /usr/sbin/irqba1158 root       20   0  258M  8100  4544 S  0.0  0.0  0:02.84 /usr/libexec/po|1.3|77|7|7|7|7  02406683.36 0.0||1.3 0| 1.4 0 0 0|743 7.77 3.88885191

    931 root       313M  5032  3356 S  0.0  0.0  0:12.05 /usr/sbin/rpc.g932313M  5032  335602.20 /usr/sbin/rpc.g114520   0  2808    92     0 0  0:00.25 /usr/sbin/acpid36m 1232   900 S  0.0  0.0  0:00.00 /usr/sbin/rpc.s    920 _rpc       8100  1308   870  0.0  0:02.59 /sbin/rpcbind -    921 systemd-o 14828  1664   864 S  0.0  0.0 28:40.55 /lib/systemd/s1.3  0.5  0:02.67 python3 main.py2486993 dtrofimov 1065M  304M  9756 S  1.3  0.5  0:02.89 python3 main.py 0 0 0.023345.05|5.7||6| 2.0|2.6||9.4|7|7|2|1.3||2.772 7.89 3.944493.3  1.210 0.03.4|0.7 0.0 2.7 0| 0|1.33.34054067M  306M  9820 S  2.7  0.5  0:02.87699168M  307M  9740094399M  305M  9756 S 926178M  3054700072M  3112.7869965M  3041.33.566997517M  7521.3  1.2  0:05.1D  1.321330.71:06.56 /vol/isy-rl/dtr80.7696M  304M  9756 S  0.73.5070072M  311M  9732 S  0.73.1270049M  308M  9692 D  0.73.04 5|1.30|7 0||1.30.7|0.72.0705M  304M  97563.606175673.68966M  30473.547004069M  308M  9692708699565M  3046670072M  3112.02.817003071M  310M  9740 S  2.0  0.5  0:03.24699168M  307S 2.967002072M  311M  9732 D  1.3  0.5  0:03.14 python3 main.py46336.3G 13.7G 7399221.5  1:06.57 /vol/isy-rl/dtr4646.3G 13.7G 73992211.69 /vol/isy-rl/dtr6997517M  754M  97561.2  0:05.1369985M  304M  975665|7|6.0 0.77 0 0.72 03.9|7339218 7.84870072M  3112.857001067M  306R 070506369918M  307M  974002.99[19699865M  304S 3.6822M  311M  973217700371M  3102.03.2746336.3G 13.7G 73992 S  0.7 21.5  1:06.58 /vol/isy-rl/dtr699099M  307M  9756 0.5  0:02.93 python3 main.py6994067M  306M  9820 02.88 python3 main.py6178M  3080.5  0:03.697517M  756S 1.2  0:05.14|5.1||||  33.6|7|1.3|4.0|7|71.3|0|74 05.8150699769M  308D 31.95.62072M  311D 2.8970049M  308M  96927105M  304M  9756 D 3.66700371M  310M  9740 D 3.3018M  307M  9740 S  1.301699399M  309M  9756 S  1.32.95699865M  304M  9756 S  1.3707002072M  311M  9732 S  1.3  0.5  0:03.19 python3 main.py700573M  312M  9728 D  1.37646336.3G 13.7G 7399221.5  1:06.59 /vol/isy-rl/dtr46496.3G 13.7G 73992211.70 /vol/isy-rl/dtr2065M  304M  97400.5  0:02.68| 1.3|      2.0 0|0.7|    10.7 0|0.7 1.3|2.03|740110.077699865M  304S  3.33.753.3818M  307M  974070569999M  311M  9756 S 2.98700272M  311M  9732 S  2.022467M  306M  9820 D 06178M  3111699966M  304M  975658[18[606972321M  356M 63196 0.6  0:02.66 python3 main.pyD 9 0.0  0|1.3|        0||1.30.7| 0.7| 1 0541 7.94 4.0037004692 D  4.73.25700272M  311M  9732 S  4.0286996178M  315M  9756 S  2.775399M  313M  9756 S  2.01565M  304D 744614 260M 93188 21984 S  0.7  0.1  0:06.90 /usr/bin/python46336.3G 13.7G 73992 S  0.7 21.5  1:06.61 /vol/isy-rl/dtr8065M  304D  0.760.7902M  311M  9756 D  0.7907001067M  306M  9756 D  0.7  0.5  0:03.08 python3 main.py      1 root       164M  9544  41440  0.0  0:39.98 /lib/systemd/s|1.4|7  0.0 0  0.0 0 0||4.624272M  311M  9732 R  7.339699399M  318M  9756 S  1.30346496.3G 13.7G 73992 S  0.7 211.71 /vol/isy-rl/dtr769M  308D  0.75.78

||2.0 0|7|73.3916S  6.74065M  304D 68331:06.62 /vol/isy-rl/dtr2486993 dtrofimov  20   0 1099M  324M  9756 S  0.7  0.5  0:03.04 python3 main.py2486996 dtrofimov  20   0 1178M  323M  9756 S  0.7  0.5  0:03.76 python3 main.py96M  304S 3.60||1.3| 1.3|7| 0| 7699399M  330M  9756 S  1.30646336.3G 13.7G 73992 S  0.7 21.5  1:06.63 /vol/isy-rl/dtr490:01.72 /vol/isy-rl/dtr6178M  326777002072M  311M  973250712634256  4388  3272 R 0  0:01.13 htop
  0.0||2.02.0|2.0|72.0794 8.11 4.079700272M  311M  9732 D  4.056999066M  305M  9756 D  2.7  0.5  0:03.64 python3 main.py6993099M  336M  9756 S  1.3  03.08 python3 main.py46336.3G 13.7G 7399221.5  1:06.64 /vol/isy-rl/dtr6996178M  332M  975678932 root       20   0  313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g7|0.76 083:00699365M  304M  9756 D  3.3136178M  346S  3.38346496.3G 13.7G 73992211.73 /vol/isy-rl/dtr1145 root       20   0  2808    92     0 S  0.0  0.0  0:00.25 /usr/sbin/acpid1148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --| 0 0| 0.7|726178M  362S  2.7  0.68746336.3G 13.7G 73992 S  1.3 21.5  1:06.66 /vol/isy-rl/dtr712634256  4388  3272 R  0.7  0.014 htop|7 0||1.3 0 0||2.90 8.37 4.183783.392490:01.75 /vol/isy-rl/dtr463316.3G 13.7G 73992 S  0.7 21.5  1:06.67 /vol/isy-rl/dtr
2484633 dtrofimov6.3G 13.7G 7399221.5  1:06.71 /vol/isy-rl/dtr1148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --1154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.55 /usr/sbin/irqba1158 root       20   0  258M  8100  4544 S  0.0  0.0  0:02.84 /usr/libexec/po[32m/vol/isy-rl/dtr2486997 dtrofimov  20   0 1069M  308M  9756 D  0.7  0.5  0:05.79 python3 main.py2487126 dtrofimov  20   0 34256  4388  3272 R  0.7  0.0  0:01.15 htop|82.0|7|7893.95 8.67 4.308065M  304D  9.3  0.518331:06.69 /vol/isy-rl/dtr1148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --1154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.55 /usr/sbin/irqba| 0|7  0|7 0 09|7 0 0 0|711 0 04.92 8.95 4.42214 260M 93188 21984 0.1  0:06.91 /usr/bin/python2484633 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  1:06.72 /vol/isy-rl/dtr2484649 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  0:01.78 /vol/isy-rl/dtr
2484633 dtrofimov6.3G 13.7G 7399221.5  1:06.73 /vol/isy-rl/dtr464916.3G 13.7G 73992 S  0.7 21.579 /vol/isy-rl/dtr921 systemd-o  20   0 14828  1664   864 S  0.0  0.0 28:40.56 /lib/systemd/sy1mroot       20   0  258M  8100  4544 S  0.0  0.0  0:02.84 /usr/libexec/poM|7 0|75
2484649 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  0:01.81 /vol/isy-rl/dtr2487126 dtrofimov  20   0 34256  4388  3272 R  0.7  0.0  0:01.19 htopm7|7|7|7|75.80 9.24 4.538[5 0|7 0 0| 0201.371154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.55 /usr/sbin/irqba1158 root       20   0  258M  8100  4544 S  0.0  0.0  0:02.84 /usr/libexec/po|7 0|7 0|710.78
|[1 0 06.62 9.52 4.653[969971069M  308M  9756 D 5  0:05.80 python3 main.py1154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.55 /usr/sbin/irqbaM|[2|748046496.3G 13.7G 73992 S  0.7 211.82 /vol/isy-rl/dtr2487126 dtrofimov  20   0 34256  4388  3272 R  0.7  0.0  0:01.20 htop
 0|7 067896049180 13800  6816 0.0  0:00.83 sshd: dtrofimov31154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.55 /usr/sbin/irqba
      1 root       164M  9544  4144 S  0.0  0.0  0:39.98 /lib/systemd/s 65719  -1  252M  181M  179M S  0.0  0.3  1:09.35 /lib/systemd/sy    695 root      32872  4400  21680  0.0  0:03.26 /lib/systemd/sy    889 root       4816  1232   9000  0.0  0:00.00 /usr/sbin/rpc.s    920 _rpc       8100  1308   876 S  0.0  0.0  0:02.59 /sbin/rpcbind -    921 systemd-o 14828  1664   864 S  0.0  0.0 28:40.56 /lib/systemd/s93313M  5032  335612.05 /usr/sbin/rpc.g93220   0  313M  5032  3356 0  0:02.20 /usr/sbin/rpc.g114 2808    92     00.25 /usr/sbin/acpid1148 messagebu37920  3992  12685.98 @dbus-daemon --m2|7326996065M  304M  9756 D  2.7  0.5  0:04.22 python3 main.py2486997 dtrofimov 1069M  308M  9756 D  25  0:05.83 python3 main.p 0.00.7|7||1.3  0.0 0.0 0 0 0 00.7 0||2.04110 9.86 4.81347M  306M  982002.95700573M  312M  9728 D  1.32.81 0  0.0 0  0546336.3G 13.7G 73992 S  0.7 21.5  1:06.85 /vol/isy-rl/dtr712634256  4388  3272 R 0  0:01.22 htop1148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --1154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.55 /usr/sbin/irqba|[3|76[6464916.3G 13.7G 73992 S  0.7 21.586 /vol/isy-rl/dtr 0|7 07 10.00 4.88 8M 0|79|7|7 0|7411.39 0 0 024 10.13 4.952|1.3|7|7|7394|0.7|7 0||7|75[146496.3G 13.7G 73992 S  0.7 211.88 /vol/isy-rl/dtr770049M  308M  96923.26932 root       20   0  313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g1145 root       20   0  2808    92     0 S  0.0  0.0  0:00.25 /usr/sbin/acpid|2.0|2.0|7|[1|7|7 0|7 0|417700071M  310M  9740 D  2.0  0.5  0:03.35 python3 main.py2486990 dtrofimov  20   0 1065M  304M  9756 D  1.3  0.5  0:03.70 python3 main.py2486992 dtrofimov  20   0 1065M  304M  9740 D  1.3  0.5  0:02.72 python3 main.py2486997 dtrofimov  20   0 1069M  308M  9756 D  1.3  0.5  0:05.85 python3 main.py1154 root       20   0 82808  1192   812 S  0.7  0.0  1:18.56 /usr/sbin/irqba2484633 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  1:06.92 /vol/isy-rl/dtr935M  304M  97563.14272M  311M  97358 0.7  0 0 0 0 0 0 030 10.26 5.0284636.3G 13.7G 73992 S  0.7 21.5  1:06.93 /vol/isy-rl/dtr96M  3050.766712634256  4388  3272 R  0.7  0.0  0:01.25 htop
 0|1.3|750[4464916.3G 13.7G 73992 S  0.7 21.590 /vol/isy-rl/dtr1154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.56 /usr/sbin/irqba

2487005 dtrofimov  20   0 1073M  312M  9728 S  0.7  0.5  0:02.93 python3 main.pib/systemd/srofimov 1069M  308M  9692 S  2.7  0.5  0:03.30 python3 main.py2487005 dtrofimov 1073M  312M  9728 S  2.7  0.5  0:02.86 python3 main.py2486991 dtrofimov 1068M  307M  9740 S  25  0:03.09 python3 main.py2486994 dtrofimov 1067M  306M  9820 S  25  0:03.00 python3 main.py2486995 dtrofimov 1182M  304M  9756 S  25  0:02.77 python3 main.py2486997 dtrofimov 1069M  308M  9756 S  25  0:05.88 python3 main.py2486998 dtrofimov 1065M  304M  9756 S  25  0:03.79 python3 main.pyH6.08 10.12 5.013  0.0  0.0  0.0 0.0| 0.7 0 0|0.7 0.0  0.0 0 2.0  02.7 043D  2.73.2396M  3062.7370018M  3062.76699665M  304D  2.04.32056 D  2.02.97042272M  311M  9732 S  1.3644614 260M 93188 21984 S  01  0:06.93 /usr/bin/python46336.3G 13.7G 73992 S  0.7 21.5  1:06.97 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 211.92 /vol/isy-rl/dtr50.780.790.780||2||1.3|7|2 0||1.3||1.31.3||1.3402670071M  310M  9740 S46700180196997M  9740 S  1.311.34699769M  308S  1.35.91699865M  304M  9756 D  1.38D 67001069M  308M  9692 S  1.3  0.5  0:03.33 python3 main.pyR 86992065M  304M  9740 02.75 python3 main.py3065M  304D 3.2447M  306M  9820 D 3.015182M  3062.79|  4.1||2.0 62.0 0.7| 0.73.33514.87 9.97 4.99 7699665M  304M  9756 S  3.34.3969985M  304786910656 S  2.777700573M  312M  9728 S  2.72.9218M  307M  9740 S  2.03.1447M  306M  9820 S  2.004168M  306M  9756 S  2.022272M  311M  9732 S  2.069699065M  304M  9756 S  1.3  0.5  0:03.26 python3 main.py79M  308M  9756 S  1.35.93700072M  311S  1.300700371M  310M  9740 S  1.3487004069M  308M  9692 S  1.33.350.7|0.7  0||2.7  0|1.30.7||1.32.66970018M  3062.73.2618M  307M  97400172065M  304M  9740 D  2.02.79699467M  306M  982003.07700072M  311M  975603700371M  310M  9740 D 5146336.3G 13.7G 73992 S  1.3 21.5  1:07.01 /vol/isy-rl/dtr699665M  304M  9756 S  1.34.4179M  3085.95700272M  311M  9732 D 3.71469M  308M  969237699065M  304M  9756 S  0.77669935M  304M  9756 S  0.727||2.6|7|7 0 1.3|7| 0.72.0  0.0| 5.254:003.33147M  306M  98271700072M  311M  9756 S 3.06700272M  311M  9732 D 74699168M  307M  9740 D  1.31969965M  304M  9756 S  1.3296997069M  308M  9756 0.5  0:05.97 python3 main.py700371M  310M  97403.5346336.3G 13.7G 73992 S  0.7 21.5  1:07.02 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 211.94 /vol/isy-rl/dtr69985M  304M  9756 S  0.7883.9||5.9 0||1.3|3 0||1.30.7|7||3.32269925M  304M  9740 D  2.72.83700371M  310M  97457699168M  307M  974022699467M  306M  9820 S 165M  304M  9756 D  2.04.4470018M  3062.03435M  304R 3.31699865M  304M  9756907000072M  311M  9756 S  1.3  0.5  0:03.08 python3 main.py7004069M  308M  961.3  03.39 python3 main.py46336.3G 13.7G 7399221.5  1:07.03 /vol/isy-rl/dtr2487002 dtrofimov 1072M  311M  97327  0.5  0:03.75 python3 main.p| 1.3 3.3| 0.7| 0.7  0.01.3|1.32.7|7713.92 9.85 4.98370018M  306M  9756 S  3.33.3969965M  304M  975635[1585M  304M  975693700072M  3113.1169925M  304M  9740 D  1.32.856D 4.4679M  308D 5.9931M  310M  97405946336.3G 13.7G 7390.7 21.5  1:07.04 /vol/isy-rl/dtr490:01.95 /vol/isy-rl/dtr699065M  304M  97567699467M  306M  98203.15

    657 root       19  -1  252M  181M  179M S  0.0  0.3  1:09.35 /lib/systemd/sy69532872  4400  216803.2688920   0  4816  1232   900 0  0:00.00 /usr/sbin/rpc.s;63H8024002.8879M  308M  97566.0270018M  3064231M  310M  9740 S 6218M  3073.2747M  306M  9820 S 3.1765M  3044.484636.3G 13.7G 73992 S  0.7 21.5  1:07.05 /vol/isy-rl/dtr699065M  304M  9756 0.5  0:03.36 python3 main.py6995182M  314M  9756 02.82 python3 main.py9106M  31580700072M  311M  9756 R 2 0.03.4 0|2 0.7|7|7 2.0|1.33.3647M  306M  9820 S  2.721700072M  311M  9756 D  2.73.1618M  307M  9740 D 3.3069965M  304R 4.51699265M  304D  1.32.9035M  304M  9756385182M  317M  97562.8470018M  306S 3.447002072M  311M  9732 D  1.3  0.5  0:03.78 python3 main.py70071M  310M  9740 D  1.364700073M  312M  9728 S  1.3974.7|0.7 0| 0  0.0| 2.0|752 9.84 5.008700573M  312M  9728069965M  304S  2.0847006M  9756 S 475182M  319S  1.32.86856 S 3.96700072M  311R 17004069M  308M  96923.4246496.3G 13.7G 73992 S  0.7 211.97 /vol/isy-rl/dtr699467M  306M  9820 S  0.722699665M  304M  9756 D  0.74.526999106M  320M  9756 S  0.73.822.0||4[11.3 0|2.7|43.3 01902M  311M  9756 S  3.323374269965M  30474.567069M  3082.76.072.74.0053M  312M  9728 S  2.70569925M  304M  9740 S  2.02.93699106M  323M  9756 S  2.0  03.85 python3 main.py700371M  310M  9740 D  2.06870018M  306S  1.33.497002072M  311M  9732 S  1.31469M  308M  9692 S  1.3444636.3G 13.7G 73992 S  0.7 21.5  1:07.07 /vol/isy-rl/dtr|7|7 0.7|7  0.0|7 0.0|3.3|2.6||911699168M  307M  9740 S  2.735604.599106M  32503.887003113M  311M  974003.71240 S  1.32.95699365M  304M  9756 S  1.34479M  308M  9756 S  1.36.098065M  3041.34.0202M  311M  9756 D  1.325272M  311M  9732 D 8346336.3G 13.7G 73992 S  0.7 21.5  1:07.08 /vol/isy-rl/dtr69905M  304M  9756 S  0.7866994067M  306M  9820 0.5  0:03.23 python3 main.py 0| 0 0 0||4 0|72.0  0.092269 4.98285M  304M  97564.06700072M  31173.20065M  3041.3699065M  304M  9756 S  1.3466564.619106M  32690700272M  311M  9732 R 3.854614 260M 93188 21984 S  0.7  0.1  0:06.94 /usr/bin/python46496.3G 13.7G 73992 S  0.7 211.99 /vol/isy-rl/dtr699168M  307M  9740 S  0.7366994067M  306M  9820 0.5  0:03.24 python3 main.py5182M  3232.897001875651| 0.7  0|||2|7| 2.014700272M  311M  973203.8846336.3G 13.7G 73992 S  1.3 21.5  1:07.10 /vol/isy-rl/dtr79047M  306M  982029106M  3273.927005073M  312M  972808699168M  307M  9740 S  0.73769921065M  304M  97405  0:02.96 python3 main.py7000072M  311M  9756 03.30 python3 main.py      1 root       164M  9544  41440  0.0  0:39.98 /lib/systemd/s||7||1.3 0 1.3|7 0.7||6657927005073M  312M  9728 D  2.7  0.5  0:03.12 python3 main.py79M  3086.11700072M  311M  97563246336.3G 13.7G 73992 S  0.7 21.5  1:07.11 /vol/isy-rl/dtr699067M  304M  9756 S  0.79135M  304M  975646564.626999106M  32893|1.3|3 0.0 0 0| 1.387168M  307M  9756 D  3.35722M  311M  9732 S  2.09570049M  9692 D  2.03.4846496.3G 13.7G 73992 S  0.7 212.00 /vol/isy-rl/dtr699065M  304M  9756 0.5  0:03.48 python3 main.py46M  98202764.63700072M  3113.33700313M  315M  97407

2484649 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  0:02.07 /vol/isy-rl/dtr2486990 dtrofimov  20   0 1067M  306M  9756 D  0.7  0.5  0:04.02 python3 main.py24869991066M  306M  9756 D 5  0:04.25 python3 main.py[m 20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --[m0  0:01.34 htopH4.036S 4.66700072M  311M  9756 S 3546336.3G 13.7G 73992 S  0.7 21.5  1:07.13 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 212.01 /vol/isy-rl/dtr6992065M  304M  9740 D  0.7  0.5  0:02.98 python3 main.py94067M  306M  9820 D 5  0:03.3079M  308D 6.185M  304M  97564.097003113M  318S 3.76|0.7  0.0 0|  0|||1.3|7||3.3627002072M  311M  973274.078065M  3044.126999106M  333M  975625182M  3302.97 0|7||1.3||1.3 0| 0.7|| 2.67214 9.70 5.0336995182M  335603.009106M  335057002072M  311M  9732 R 108065M  3044.14||1.3 0| 0.7  0.0|7|||7157002072M  3132 D  3.34.15582M  3333.036999106M  338M  9756 S 08D 6|7  0.0||1.3|7||1.3| 0  0.05266995182M  337M  9756 R  4.03.090067M  3047984011 0|1.32.6 0||3.36121 9.76 5.07841S  5.3179106M  3424.04.171068M  307M  9740 D 3.43||3.3|2.0  0.0| 0.7||2.60.7899066M  306D  4.74.24582M  34823.2007M  306M  9756 D  1.34.017003113M  340M  9740 S  1.3  03.82 python3 main.py46336.3G 13.7G 7399221.5  1:07.18 /vol/isy-rl/dtr12634256  4388  3272 R 0  0:01.35 htop||2  0.0| 0.7|7|2| 0.75315182M  35S  2.0  0.6  0:03.23700313408579M  3086.144614 260M 93188 21984 S  0.7  0.1  0:06.95 /usr/bin/python9  0||2.6||3.3 0 0 0 062683.38071M  310D  3.39046336.3G 13.7G 73992 S  0.7 21.5  1:07.20 /vol/isy-rl/dtr7009M  309M  969250921 systemd-o  20   0 14828  1664   864 S  0.0  0.0 28:40.58 /lib/systemd/sy931 root       20   0  313M  5032  3356 S  0.0  0.0  0:12.05 /usr/sbin/rpc.g932 root       20   0  313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g1145 root       20   0  2808    92     0 S  0.0  0.0  0:00.25 /usr/sbin/acpid  0.04.0|7||1.3|7|7|7 0|7|7[1543 9.85 5.134854.0344636.3G 13.7G 73992 S  0.7 21.5  1:07.21 /vol/isy-rl/dtr490:02.06 /vol/isy-rl/dtr072M  311M  975637|72.7 0  0.0 0 0||7 01.3|7554003.391.331.3|7|1.3|7 0 00.7 07174.7  0.7460.74
2484614 dtrofimov  20   0  260M 93188 21984 S  0.7  0.1  0:06.96 /usr/bin/python2484633 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  1:07.31 /vol/isy-rl/dtr490:02.12 /vol/isy-rl/dtr 0| 0.7  0.0 0|7  0.0504636.3G 13.7G 73992 S  0.7 21.5  1:07.32 /vol/isy-rl/dtr801145 root       20   0  2808    92     0 S  0.0  0.0  0:00.25 /usr/sbin/acpid1148 messagebu  20   0 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --1154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.56 /usr/sbin/irqba.98 @dbus-daemon --1154 root       20   0 82808  1192   812 S  0.0  0.0  1:18.56 /usr/sbin/irqba||1.3|7 |7|1.3|1.3|7||2516992065M  304M  9740 D  1.3  03.01 python3 main.py2486997 dtrofimov  20   0 1069M  308M  9756 S  1.3  0.5  0:06.16 python3 main.py2487001 dtrofimov  20   0 1068M  307M  9756 S  1.3  0.5  0:03.61 python3 main.py2487004 dtrofimov  20   0 1069M  309M  9692 S  1.3  0.5  0:03.52 python3 main.py2484633 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  1:07.26 /vol/isy-rl/dtr2486991 dtrofimov  20   0 1068M  307M  9740 D  0.7  0.5  0:03.44 python3 main.py2486993 dtrofimov  20   0 1065M  304M  9756 D  0.7  0.5  0:03.51 python3 main.py0051073M  312M  9728 S 5  0:03.15 python3 main.py|7||2.0|7||1.3| 0.7936 10.18 5.319D810D  2.070 0 0 02[3712634256  4388  3272 R  0.7  0.0  0:01.40 htop|790 10.34 5.393[4464916.3G 13.7G 73992 S  0.7 21.5  0:02.13 /vol/isy-rl/dtr|7|7 05[5712634256  4388  3272 R  0.7  0.0  0:01.41 htop
    889 root 4816  1232   9000  0.0  0:00.00 /usr/sbin/rpc.s    920 _rpc       8100  1308   8760  0.0  0:02.59 /sbin/rpcbind -    931 root       313M  5032  33560  0.0  0:12.05 /usr/sbin/rpc.g    932 root       313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g   1145 root       2808    92     0 S  0.0  0.0  0:00.25 /usr/sbin/acpidin.py2486993 dtrofimov 1065M  304M  9756 D  0.7  0.5  0:03.69 python3 main.py main.py2486998 dtrofimov 1065M  304M  9756 S  25  0:04.22 python3 main.p  0.0|7|7 0|0.7  0.0 0|0.7  0.0 0.0  0.04.69970072M  311S  1.33.44

      1 root       164M  9544  41440  0.0  0:39.98 /lib/systemd/sy7001071M  310M  9756 D  1.3  0.5  0:03.74 python3 main.py700371M  310M  9740 S  1.33.9646336.3G 13.7G 73992 S  0.7 21.5  1:07.41 /vol/isy-rl/dtr464916.3G 13.7G 73992 S  0.7 21.5  0:02.18 /vol/isy-rl/dtr2487000 dtrofimov 1072M  311M  9756 D  0.7  0.5  0:03.47 python3 main.pm69967M  3064.07 0|||2 0 0.0||2 0|7||3.3714 10.38 5.464700272M  311M  9732 D  2.022D 937247M  306M  98203.3|1.3|3.3 0  0|1.3|1.3 |7 02.0| 0.7| 0.7|755699769M  308M  9756 S  46.2555M  304M  9756 S  2.0702400565M  304M  97564.75|2.0|5|7|7 0.04.0|71.33.9|7|6 0||5.2 0718M  307M  9740 D  2.73.53874.2907M  306M  9756 D  2.04.105S  2.03.73700072M  3112.03.5053M  312M  9728 D  2.026699265M  304D 07699109M  306M  9756 S  1.3  0.5  0:03.74 python3 main.py6994067M  306M  9820 D  1.3  03.41 python3 main.py699966M  3061.34.3311M  310M  9756 D  1.33.76272M  311M  9732 D  1.34.2531M  310M  9740 D  1.39866.7||1.32 0|2.0|0.7 0 1.32.782.85 10.29 5.45879M  308M  97566.2918M  307M  974003.5655M  3043.768D 4.32699265M  304M  9740 D  1.309699467M  306M  9820 D  1.34367656 S 4.790664.35700171M  310M  975678700272M  311M  9732 S 273404.0046336.3G 13.7G 73992 S  0.7 21.5  1:07.43 /vol/isy-rl/dtr699067M  306M  9756 D  0.74.11| 4.0 0| 0.7|7|7 1.3||0.7| 1.35103109M  314S3.7676M  304M  975674.8170073M  312M  9728 S  2.73118M  307M  9740 D  1.33.5847M  306M  9820 S 4555M  304M  97567886534[17340 S 4.0246336.3G 13.7G 73992 S  0.7 21.5  1:07.44 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 212.19 /vol/isy-rl/dtr7001139M  310M  9756 0.5  0:03.79 python3 main.py700272M  311M  973228 0.0 2||2.00 00.7 0||2||7||2.017001323.3843109M  31703.82699067M  306M  9756 D  1.34.1325M  3041155M  304M  97568096M  306S 4.39700072M  3113.5370049M  309M  9692 D 3.624636.3G 13.7G 73992 S  0.7 21.5  1:07.45 /vol/isy-rl/dtr490:02.20 /vol/isy-rl/dtr6994067M  306M  9820 03.46 python3 main.py6998065M  304D 4.35[19|7|5.3 6.7|7|1.3|7  0|2|2.0738 10.24 5.463491068M  30407679M  308S  2.76.3856 S  2.04.3870073M  312M  9728 S  2.03407D 15699265M  304M  974016997M  306M  9820 S 486999066M  306M  9756 D  1.3  0.5  0:04.41 python3 main.py7000129M  312M  9756 S  1.3  03.55 python3 main.py700272M  311M  9732 S  1.34.3170049M  309M  9692 D  1.33.6446336.3G 13.7G 73992 S  0.7 21.5  1:07.46 /vol/isy-rl/dtr 0 3.4| 0.7|7|3.3|7 0  0.0|  0.03.346990067M  3062.04.183109M  320M  975608647M  306M  982003.5167685699966M  306M  9756 D 4.4700573M  312M  9728 S  2.03.3746336.3G 13.7G 7399221.5  1:07.48 /vol/isy-rl/dtr55M  304M  97568379M  308S 6.356998065M  304D 4.40[13[16490:02.21 /vol/isy-rl/dtr4.0|7| 0 1| 0|1.3  0| 2.0|796618M  307M  974073.664067M  306M  98207557009M  309M  9692770769M  3086.3885M  304S 36993109M  3256 S  1.3886996076M  304M  9756 0.5  0:04.87 python3 main.py96M  3064.4607M  306D  0.74.195S  0.73.840129M  314M  9756 S  0.73.5712634256  4388  3272 R  0.7  0.0  0:01.46 htop

   1866 root      24876  2024   908 S 0  6:24.85 /usr/sbin/cups-46496.3G 13.7G 73992212.26 /vol/isy-rl/dtr18M  307M  97403.786995065M  30D 4.017560916997M  306M  9820058[417001139M  318R 3.927004069M  309M  9692724614 260M 93188 21984 S  0.7  0.1  0:06.97 /usr/bin/python46336.3G 13.7G 73992 S  0.7 21.5  1:07.49 /vol/isy-rl/dtr25M  304M  9740 S 3.14[156999066M  3064.40001129M  315M  9756 S 5  0:03.58 python3 main.py2487003 dtrofimov 1071M  310M  97407  0.5  0:04.05 python3 main.p1||1.3 0|2.0|7||7| 1.311.39 10.07 5.43918M  307M  9740 D  2.73.700067M  306D  1.34.263109M  326M  9756 S  1.39347M  306M  9820 S  1.33.603071M  310M  9740 D  1.34.0746336.3G 13.7G 7390.7 21.5  1:07.50 /vol/isy-rl/dtr4916.3G 13.7G 7399221.5  0:02.22 /vol/isy-rl/dtr6995065M  304M  9756 0.5  0:03.86 python3 main.py676564.888D 4.447000129M  313.59139M  3219322M  311M  9732342.72.7 0|7 01.3322025M  304S  1.316700371M  310M  9740097004069M  309M  969274700573M  312M  9728394636.3G 13.7G 73992 S  0.7 21.5  1:07.51 /vol/isy-rl/dtr6990067M  306M  9756 0.5  0:04.27 python3 main.py6994067M  306M  9820 03.61 python3 main.py6764.89769M  3086.42S 56999066M  304.4834|7|4.00|70.7 0 0.0|71712556 D  2.089699467M  306M  9820 S 3.6369985M  304M  9756 D 4.4731M  310M  97404.117004069M  309M  961.3  0.5  0:03.76 python3 main.py   1872 root      45680  3976  18480 12:02.46 /usr/sbin/sssd 46496.3G 13.7G 73992212.23 /vol/isy-rl/dtr3109M  3313.9496M  3064.497000129M  3193.60712634256  4388  3272 R 0  0:01.48 htop 0 1.3 0|2.0|7|7|7|||4.65304 10.02 5.44370049M  309M  9692 S  2.7055M  304M  9756 S  2.09218M  307M  9740 R 3.72699467M  306M  9823.6546336.3G 13.7G 7390.7 21.5  1:07.52 /vol/isy-rl/dtr2486990 dtrofimov 1067M  306M  97565  0:04.28 python3 main.py6993109M  333M  9756 03.95 python3 main.py7069M  3086.43[502072M  311M  97324.350031071M  310M  9740 S 5  0:04.12 python3 main.py72.0|1.3 0.7 0 0|2.0 02.7|781569985M  304M  9756 D4.5170049M  309M  9692784700573M  312M  9728 D  2.74318M  307M  9740 S  2.071.344820 D  1.33.675065M  304D  1.34700371M  310M  9740 S  1.34.144646.3G 13.7G 73992212.24 /vol/isy-rl/dtr69965M  304M  97403.17699109M  334M  97563.961.31.3 0.0|2.0 1.3| 0|7679M  3086.48[1869965M  304M  9756 S  2.097D  1.376996076M  304M  9756 0.5  0:04.91 python3 main.py7000129M  323M  9756 S 346336.3G 13.7G 73992 S  0.7 21.5  1:07.55 /vol/isy-rl/dtr699109M  336M  9756 S  0.73.977001139M  330M  9756 03.96 python3 main.py700371M  3104.15712634256  4388  3272 R 0  0:01.49 htop||1.32.02.0|71.3|1.30.7|7||3.3 060.88 10.00 5.46855M  304S  2.04.00091240 D  1.31985M  304M  97564.5370053M  312M  9728 D 3.4546336.3G 13.7G 73992 S  0.7 21.5  1:07.56 /vol/isy-rl/dtr490:02.25 /vol/isy-rl/dtr0067M  30D 4.296993088699467M  306M  9820 D 3.686991076M  304M  9756 S 5  0:04.92 python3 main.py2486999 dtrofimov 1066M  306M  97567  0.5  0:04.52 python3 main.p4||1.31.31.3| 0.7|70.71.3 0| 59240 D3.2269978M  97566.57001139M  333M  9756 S  2.04.0070049M  309M  9692 S  2.03.94699467M  306M  9820 S 706996076M  305M  9756 S  1.3  0.5  0:04.94 python3 main.py6998065M  304M  9756 D  1.3  04.55 python3 main.py700573M  312M  9728 S  1.33.47

    889 root       4816  1232   900 S  0.0  0.0  0:00.00 /usr/sbin/rpc.s    920 _rpc       8100  1308   876 S  0.02.59 /sbin/rpcbind -921 systemd-o14828  1664   8628:40.6093120   0  313M  5032  3356 0  0:12.05 /usr/sbin/rpc.g932 313M  5032  33562.20 /usr/sbin/rpc.gH26992106M  306M  9740 R  2.025700272M  311M  9732 D  2.04246336.3G 13.7G 73992 S  1.3 21.5  1:07.59 /vol/isy-rl/dtr18M  307M  9740 S  1.33.823109M  342M  9756 S 4.047820 S 3.73699565M  304M  9756 D 066999066M  306M  9756 S  1.3  0.5  0:04.57 python3 main.py7003071M  310M  9740 S  1.3  0.5  0:04.207009M  309M  9692 D  1.34.046496.3G 13.7G 73992 S  0.7 212.27 /vol/isy-rl/dtr699067M  306D 4.34029M  3293.66 06 0| 0.7|7 0 0 02.06157 9.95 5.47 48S8699467M  306M  9820 S  1.33.756996076M  310M  9756 0.5  0:04.96 python3 main.py46336.3G 13.7G 73992 S  0.7 21.5  1:07.60 /vol/isy-rl/dtr40.7185M  304M  9756 D  0.74.597001139M  339S  0.72 0|71.3| 0|7||1.352510R  3.3337000129M  334M  9756687001139M  34204[1146496.3G 13.7G 73992212.28 /vol/isy-rl/dtr3109M  346S 026996076M  31397||1.3|6.03|1.3 0  0.0||3.97176075M  9756 D  4.05.06993065M  305D  34.07699206M  313M  9740 S  2.03.366991068M  307M  9740 S  1.3  0.5  0:03.84 python3 main.py6994067M  306M  9820 S  1.3  03.77 python3 main.py9066M  301.35970022M  311M  9732 D  1.344| 0.74.7  0.0||2.62.6|7|1.3||1.3|72.0|7529821040 S  23.3907M  3061365065M  304M  9756 D  1.34.0879M  308M  9756 D 6.57000129M  340M  975607001139M  34907S 67004069M  309M  9692 D  1.3  0.5  0:04.03 python3 main.py7005073M  312M  9728 D  1.3  0.5  0:03.5046496.3G 13.7G 73992212.29 /vol/isy-rl/dtr699467M  306M  9823.78 01.3||2  0.0| 0.7 0.0|73.3 08408648962.76418M  307M  97403.867001139M  354S 6  0:04.0946336.3G 13.7G 73992 S  0.7 21.5  1:07.63 /vol/isy-rl/dtr0250.73.71D  0.77M 0.7| 0.7 0|7 0 0| 0.7|  0.06.0521700139M  359M  9756 S  46  0:04.157000129M  352S  1.3  0.6  0:03.7346336.3G 13.7G 73992 S  0.7 21.5  1:07.64 /vol/isy-rl/dtr46496.3G 13.7G 73992 R  0.7 21.5  0:02.30 /vol/isy-rl/dtr6992106M  322M  9740 0.5  0:03.49 python3 main.py2486994 dtrofimov  20   0 1067M  306M  9820 D  0.7  0.5  0:03.79 python3 main.py6998065M  304D 4.6031M  310M  974024|2.0 0||2.7 0|||2.7172 10.00 5.54 302823.76139M  3652.04.186990067M  306M  9756 D  1.3  0.5  0:04.38 python3 main.py 261812 gdm       3876M  150M 35260 S  0.7  0.2  5:55.64 /usr/bin/gnome-4614 260M 93188 219841  0:06.98 /usr/bin/python46336.3G 13.7G 73992 S  0.7 21.5  1:07.65 /vol/isy-rl/dtr2106M  327M  9740 S 3.569965M  305M  975608  0  0.0 0 01.44699206M  332M  9740 S  1.3  0.55291.32046336.3G 13.7G 73992 S  0.7 21.5  1:07.66 /vol/isy-rl/dtr2484649 dtrofimov 16.3G 13.7G 7399221.5  0:02.31 /vol/isy-rl/dtr70001129M  364M  97566  0:03.77 python3 main.py      1 root       164M  9544  41440  0.0  0:39.98 /lib/systemd/sy    657 root       19  -1  252M  181M  179M S  0.0  0.3  1:09.35 /lib/systemd/s|7||6|7|7|1.3||2.75.967000072M  311M  9756 D  4.7841921 root       20   0  183M 98208  4760 S  2.0  0.1 23:29.32 /usr/libexec/ss2486992 dtrofimov  20   0 1106M  339M  9740 S  1.3  0.5  0:03.54 python3 main.py2486995 dtrofimov  20   0 1065M  304M  9756 D  1.3  0.5  0:04.10 python3 main.py2486997 dtrofimov  20   0 1069M  308M  9756 D  1.3  0.5  0:06.56 python3 main.py2484633 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  1:07.67 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 21.5  0:02.32 /vol/isy-rl/dtr6998065M  304M  9756 0.5  0:04.61 python3 main.py7001139M  374M  9756 0.6  0:04.21 python3 main.py5073M  312M  9728 D 551

    931 root       313M  5032  3356 S  0.0  0.0  0:12.05 /usr/sbin/rpc.g    932 root       313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g 4816  1232   9000  0.0  0:00.00 /usr/sbin/rpc.s    920 _rpc       8100  1308   8760  0.059 /sbin/rpcbind -    921 systemd-o 14828  1664   864 S  0.0  0.0 28:40.60 /lib/systemd/s24876  2024   9080  6:24.86 /usr/sbin/cups-46336.3G 13.7G 7399221.5  1:07.68 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 212.33 /vol/isy-rl/dtr2486993 dtrofimov 1065M  305M  9756 D  0.7  0.5  0:04.09 python3 main.p
2487126 dtrofimov  20   0 34256  4388  3272 R  0.7  0.0  0:01.56 htop   920 _rpc      8100  1308   8760  0.0  0:02.59 /sbin/rpcbind -    921 systemd-o 14828  1664   8640  0.0 28:40.60 /lib/systemd/sy    931 root       313M  5032  33560  0.0  0:12.05 /usr/sbin/rpc.g    932 root       313M  5032  3356 S  0.0  0.0  0:02.20 /usr/sbin/rpc.g   1145 root       2808    92     0 S  0.0  0.0  0:00.25 /usr/sbin/acpid   1148 messagebu 37920  3992  1268 S  0.0  0.0  0:05.98 @dbus-daemon --   1154 root      82808  1192   812 S  0.0  0.0  1:18.56 /usr/sbin/irqba1158258M  8100  4502.84 /usr/libexec/po30m2|7|1.3 0|7|2||2 0|7361.30 10.15 5.63396067001071M  310M  9756 D  2.0  0.5  0:04.32 python3 main.py69911068M  307M  9740 D  1.3  0.5  0:03.88 python3 main.py699265M  304M  9740 D  1.3610021072M  311M  9732 D  1.3  0.5  0:04.49 python3 main.py2484614 dtrofimov 260M 93088 21887  0.1  0:06.99 /usr/bin/python2484633 dtrofimov  20   0 16.3G 13.7G 73992 S  0.7 21.5  1:07.72 /vol/isy-rl/dtr2484649 dtrofimov 16.3G 13.7G 739927 21.5  0:02.35 /vol/isy-rl/dtr2486993 dtrofimov 1065M  305M  9756 D  0.7  0.5  0:04.11 python3 main.py2486996 dtrofimov 1076M  315M  9756 D  0.7  0.5  0:05.06 python3 main.py2486998 dtrofimov 1065M  304M  9756 D  0.7  0.5  0:04.63 python3 main.p  0.0|7 0  0 0 0.0 0|0.7  0 09546336.3G 13.7G 73992 S  0.7 21.5  1:07.73 /vol/isy-rl/dtr      1 root       164M  9544  4144 S  00  0:39.98 /lib/systemd/sM|7 0|7 086490:02.36
2486995 dtrofimov 1065M  304M  97567  0.5  0:04.21 python3 main.p /lib/systemd/sy    657 root       19  -1  252M  181M  179M S  0.0  0.3  1:09.35 /lib/systemd/sy    695 root      32872  4400  21680  0.0  0:03.26 /lib/systemd/sH1076M  315M  9756 S  1.3  0.510 python3 main.py@dbus-daemon --on3 main.py2487001 dtrofimov 1071M  310M  9756 D  0.7  0.5  0:04.33 python3 main.py   1 root      164M  9544  414439.98 /lib/systemd/sy 65719  -1  252M  181M  179M 3  1:09.35 /lib/systemd/sy[32m||2|1.3||2||1.3||1.3|1.3|7|7|1.3||2.692.10 10.36 5.754 00.7  0|0.7  0  0.0  0.0  0.0 0 0 0.0  0.0546336.3G 13.7G 73992 S  0.7 21.5  1:07.79 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 212.39 /vol/isy-rl/dtr712634256  4388  3272 R  0.7  0.0  0:01.58 htop||4.54.0|7||2|2.0|6.7||1.3|7|4||2.7|1.3|1.3|2.7|2||2.7676990067M  306M  9756 S  3.3  0.5  0:04.63 python3 main.py6998065M  304M  9756 D  3.3  04.68 python3 main.py69921065M  304M  9740 S  25  0:03.66 python3 main.py2486995 dtrofimov 1065M  304M  9756 S  2.7  0.5  0:04.15 python3 main.p1.3|2.6 0 0.7 0|5.4  0.0 0 0 1.3 0.0|0.7|1.3|1.33.351.37 10.24 5.738118M  3082.0635S  2.017856 D  2.04.71700072M  311D  2.03.9700272M  311M  9732 D  2.04.5569968M  307M  9740 D  1.33.94699467M  306M  9820 D  1.33.871101M  315M  9756 S  1.34.3931M  310M  9740 S  1.34.34614 260M 93088 21884 S  0.7  0.1  0:07.00 /usr/bin/python46336.3G 13.7G 73992 S  0.7 21.5  1:07.81 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 212.40 /vol/isy-rl/dtr265M  304M  9740 S  0.73.67  0.004.6|0.7 0  0.0  0.0192107003071M  310M  9740 S  3.33796M  3067747M  306M  98203.90699118M  309S  1.34.6869965M  304M  9740 R  1.33.6935M  305M  9756 S 4.19700072M  311M  9756 S 964153M  312M  97283.643316.3G 13.7G 7399221.5  1:07.82 /vol/isy-rl/dtr6991068M  307M  9740 D  0.7  0.5  0:03.95 python3 main.py6995065M  304M  9756 D  0.7  04.17 python3 main.py79M  308M  9756 D 6.62||2.6 6.1||1.3 2.0||1.3||1.3|2|2| 2.711699168M  3072.73.9925M  304M  97403.7335M  305M  9756 S  2.74.234067M  306M  9820 S  2.73.9479M  308M  9756 S  2.76.66542.020699865M  3042.04.750072M  3112.000699966M  306M  97564.797002072M  311M  9732 S  1.3  0.5  0:04.57 python3 main.py46336.3G 13.7G 73992 S  0.7 21.5  1:07.83 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 212.41 /vol/isy-rl/dtr7001101M  31S 4.4  0.0|2.7||1.3 0.04  0.0  0.00.7|0.7||4.50.70 10.12 5.72347M  306M  9820770072M  311M  9732 D  2.04.6018M  307M  9740 S  1.30125M  304M  9740 S  1.37585M  3041.34.777000119M  3131.3020118M  3130.76969966M  3150.75.120.78053M  312M  9728 S  0.73.666 0.71.3|7 0 0| 2.7|764700272M  311M  973274.646990118M  314M  9756 S 7247M  306M  9820 S  2.00700573M  312M  9728 S  2.06918M  307M  9740036992065M  304M  97403.777069M  3081.36.687000119M  3161.34.047001101M  3201.34446336.3G 13.7G 7399221.5  1:07.84 /vol/isy-rl/dtr2486972 dtrofimov 1321M  356M 632487  0.6  0:02.73 python3 main.p|77|2.0|7|7 0|7||1.3||6 056699966M  306M  9756857069M  3086.7185M  304M  9756 D 8[172D 5676M  315M  97565.14700371M  310M  9740 D 4.4046336.3G 13.7G 73992 S  0.7 21.5  1:07.85 /vol/isy-rl/dtr46496.3G 13.7G 73992 S  0.7 212.42 /vol/isy-rl/dtr699065M  305M  9756 D  0.7  0.5  0:04.25 python3 main.py94067M  306M  9820 D 5  0:04.017000119M  318057001101M  32245   1872 root      45680  3976  18480 12:02.47 /usr/sbin/sssd 4614 260M 93088 218841  0:07.01 /usr/bin/python46336.3G 13.7G 7399221.5  1:07.86 /vol/isy-rl/dtr46496.3G 13.7G 73992212.43 /vol/isy-rl/dtr6990118M  318M  97567369965M  304M  97564.22H3.78699467M  306M  9820 S  0.7026996076M  315M  9756 0.5  0:05.15 python3 main.py6998065M  304M  9756 04.81 python3 main.py7000119M  319S 067001101M  323M  9756 S 464074M  309M  9692125073M  31283.734.7 1||2|7|||2.6108 10.00 5.70918M  307M  9740 S  2.70947M  306M  9820 S  2.74.0635M  305S  2.030699966M  306M  9756 S  2.0902.0579M  308M  9756 S  1.36.7585M  304M  9756 D  1.383||220.7 0||2.03.32085M  304M  9756 D  3.38818M  307M  9741347M  306M  9820 S  1.30879M  3081.36.77D  1.37700474M  309M  96924.146336.3G 13.7G 73992 S  0.7 21.5  1:07.87 /vol/isy-rl/dtr2486972 dtrofimov 1321M  356M 6326  0:02.74 python3 main.py69901118M  320M  97565  0:04.74 python3 main.py6992065M  304M  9740 D  0.7  0.5  0:03.79 python3 main.py6996076M  315M  9756 05.16 python3 main.py700101M  32547700272M  311M  973269

In [133]:
objects_to_download

[{'sha256': '079c1fbedddddc5b9462a22ec9e043e808aac72c0b138b2173b4f191971135c6',
  'fileIdentifier': 'https://sketchfab.com/3d-models/bc0fd04422374b3987162a6c499280d8',
  'source': 'sketchfab'},
 {'sha256': '8a784c4a068239e24666b84acd05083ea7cb5092e3c0bc7550c2e13e5798786f',
  'fileIdentifier': 'https://sketchfab.com/3d-models/2c3379f8126743c0b6e564c70ff859bc',
  'source': 'sketchfab'},
 {'sha256': '4e41726df0b2eb46fa66be100b6c9389c2fb215fa87e17fc818cbea1d920c34d',
  'fileIdentifier': 'https://sketchfab.com/3d-models/007ab9e6f1c047b287bc0f09188de0c4',
  'source': 'sketchfab'},
 {'sha256': '39ccad9118884c8e416005646d85d1f668c91c944adbc6187262a829ab2d14e3',
  'fileIdentifier': 'https://sketchfab.com/3d-models/70583f5df06448c1bba076df3afcdbbb',
  'source': 'sketchfab'},
 {'sha256': 'f28847e18692b047fc15047749257a770b2f1b7e03124eaf4912d7cbdf796316',
  'fileIdentifier': 'https://sketchfab.com/3d-models/44be138ae8e2409bbbca44a96fc67d45',
  'source': 'sketchfab'},
 {'sha256': '396405650da99fd6e17a889de7b691df5984a567ae3e0f9f26726e9d8855f1aa',
  'fileIdentifier': 'https://sketchfab.com/3d-models/4d2b0f61b72e433492237d96d780f3f8',
  'source': 'sketchfab'},
 {'sha256': '0639c87f94d133e6c88abdbca3f9f984702c420866f1fd5d8dbe25b27001110a',
  'fileIdentifier': 'https://sketchfab.com/3d-models/d892ccd7e7404801885a9db3dfe8becd',
  'source': 'sketchfab'},
 {'sha256': '36492f183f0090a77849438f3de16003b3ffffa4436f90571d8df9a32095be2e',
  'fileIdentifier': 'https://sketchfab.com/3d-models/72d672aa4d434e47a82b8488092a8ee6',
  'source': 'sketchfab'},
 {'sha256': 'f919c7fd7c5a9ec81543e6a9ccfa9c7ef4ae07de62a1eef899fda37ba88e0b07',
  'fileIdentifier': 'https://sketchfab.com/3d-models/b4623f4127c143928b75ab839442f070',
  'source': 'sketchfab'},
 {'sha256': '74fdddef3dcce21c7dfb6f5bf4bfdcec470994646451652863b97ff1115cd2c9',
  'fileIdentifier': 'https://sketchfab.com/3d-models/d055777ad2e9460b8bc11cd62a454bdf',
  'source': 'sketchfab'},
 {'sha256': '02d365346e71ff6dd47c6bb02adca0d45b5b592659b02f27359ea21bc87834c4',
  'fileIdentifier': 'https://sketchfab.com/3d-models/f9b15ae605e047b498f7c0b2858a865d',
  'source': 'sketchfab'},
 {'sha256': 'ad7b42e4e597f1b713c5b876136369ca9053f742cbe360a87c790333a15580a2',
  'fileIdentifier': 'https://sketchfab.com/3d-models/cd0e50d2386849a8924f21dd16fc3280',
  'source': 'sketchfab'},
 {'sha256': '8df516a58790ee6458c8a077a8e5f348f45b9eee434076aac67bb267e07ce66c',
  'fileIdentifier': 'https://sketchfab.com/3d-models/07b07f7292ed41019a8b6aebd98a5c29',
  'source': 'sketchfab'},
 {'sha256': '81a8ca5899c7cfedab55bc6233c3e6a361a75471a520018c482f4a4dc160e74b',
  'fileIdentifier': 'https://sketchfab.com/3d-models/0abcc9938f94440cb8c0a7d29d4c52ee',
  'source': 'sketchfab'},
 {'sha256': '95b70604177995a7441deeb09c62e55d85e8564eca9cff91972960226dc5f104',
  'fileIdentifier': 'https://sketchfab.com/3d-models/dbf5eb754bed4d269047bc67f08d4701',
  'source': 'sketchfab'},
 {'sha256': '23e542470166f55d9b04e6a1964c56532cdae177e6ef1899018c89bb7c7c72a1',
  'fileIdentifier': 'https://sketchfab.com/3d-models/7eece8d7b74e41cf94c4d01cfeb2c968',
  'source': 'sketchfab'},
 {'sha256': 'b2f28c1703da9ce04b07245ed6944373afda518ebb18dfd77cdd90d5f6494764',
  'fileIdentifier': 'https://sketchfab.com/3d-models/65c234a5320644be9aabb6dbcf2e2dfc',
  'source': 'sketchfab'},
 {'sha256': 'd4c0087eef898b869101beb62f1636dc68329564251d91f48c16704da3f65c06',
  'fileIdentifier': 'https://sketchfab.com/3d-models/7d68c90551144cdb81d9223b8ead8cda',
  'source': 'sketchfab'},
 {'sha256': '31470d1c3dc6ccccc2bb6f8ead48ef5189e3d2173043283f93ce8a55ba1e98eb',
  'fileIdentifier': 'https://sketchfab.com/3d-models/01ac564cf0d24007a0a9965048124a04',
  'source': 'sketchfab'},
 {'sha256': 'e8b0159f9880fe27936f8043fd609b49a7af6264426ee5ae6d73b9e1c3954e4d',
  'fileIdentifier': 'https://sketchfab.com/3d-models/2672abb9518c4367abc46c7804ae44d2',
  'source': 'sketchfab'},
 {'sha256': 'cf26d741ac4c9cd8129a261b40ba6fc0c9941a70ba0525ca10902a441c16c6fe',
  'fileIdentifier': 'https://sketchfab.com/3d-models/2a02794be3c44a9c845159164e320d34',
  'source': 'sketchfab'},
 {'sha256': '88a1ff5cee5d00afbd071797b1195e65dd2c050b05a114e6731767f224381b4a',
  'fileIdentifier': 'https://sketchfab.com/3d-models/96b938e88ac942209fcf403b00a7297b',
  'source': 'sketchfab'},
 {'sha256': '44d1fe642d44d9023fc722f776a3da1283a80358d6b070267dad8c50133fbdf4',
  'fileIdentifier': 'https://sketchfab.com/3d-models/bae31e4c68b443468c1c6a3ced6eb289',
  'source': 'sketchfab'},
 {'sha256': '78968f324f5ccc758ca23fb78c08636fb76e74af0da056f25960df9c38ceda74',
  'fileIdentifier': 'https://sketchfab.com/3d-models/483ac8fb734b45e39bb03ddd58906a3c',
  'source': 'sketchfab'},
 {'sha256': '1cba99e2a53a64c81f4a20b0d53fe03a21784d6f2c950e65c1c0832b787e367a',
  'fileIdentifier': 'https://sketchfab.com/3d-models/5c11613bd0ef4e1cba02961b7552a37f',
  'source': 'sketchfab'},
 {'sha256': '08b5beae466625a4685166654341ca753543824209dc2baebff2384ada76710e',
  'fileIdentifier': 'https://sketchfab.com/3d-models/19da225fca2b4527ba03ba5d2f540200',
  'source': 'sketchfab'},
 {'sha256': 'f717ce41f123b1e13c19d80d8eaa3cb9d5e3cc651feec7675984562ac6b2cd4b',
  'fileIdentifier': 'https://sketchfab.com/3d-models/5cc2bb8c64cd401c8b7c0c0625ab6ae7',
  'source': 'sketchfab'},
 {'sha256': 'd61252fff641700da8030f55f53a5fc0fc4c134c92bae27373ce3c0fd1192dc7',
  'fileIdentifier': 'https://sketchfab.com/3d-models/7111485f9c4848079954df9c3feab365',
  'source': 'sketchfab'},
 {'sha256': '10cd1e865ba7e852d155fcad4017620549935ab02db9257ff0b930e444d60168',
  'fileIdentifier': 'https://sketchfab.com/3d-models/8b4cf46b346c4342bbc5ce574f7bd8f1',
  'source': 'sketchfab'},
 {'sha256': 'cb40d98eb56d21d0e6375f0e3b29fa2b2ea0586d38bea650e959660321f5462b',
  'fileIdentifier': 'https://sketchfab.com/3d-models/1c98dea5fe1d40079a7806a6f94067f9',
  'source': 'sketchfab'},
 {'sha256': 'd25dbd875457add4abc2e85a926582b6c6fa5b460be864f3159c5906dc5a27d8',
  'fileIdentifier': 'https://sketchfab.com/3d-models/6a7cc74278a8442bb9efca045d9d9234',
  'source': 'sketchfab'},
 {'sha256': 'ce329fd1f8092daa6065d42899b41dc19c27c522574ed12ef04269d20f0ab2a0',
  'fileIdentifier': 'https://sketchfab.com/3d-models/c434f22ec51846cc8142e95f7f2495eb',
  'source': 'sketchfab'},
 {'sha256': '2cb0543fe2b3be085d2e7ebc9d42cb9972b7d668027ad31ca6dc67c4b9764601',
  'fileIdentifier': 'https://sketchfab.com/3d-models/bf6970e526854fd8beb1201183de1bdf',
  'source': 'sketchfab'},
 {'sha256': '19d8e46c436a20ebcc1eb068c1a99c71036bf3fa09059dc26d6b61c29f8ecafa',
  'fileIdentifier': 'https://sketchfab.com/3d-models/25f130c40c8948c2be8f4d34fb7e903c',
  'source': 'sketchfab'},
 {'sha256': '9467dcdb121f752c70220878d9291be5eae133f35a41ece931e4143a841a8e8e',
  'fileIdentifier': 'https://sketchfab.com/3d-models/fb807fdf2bfa433192e434a5a04e017d',
  'source': 'sketchfab'},
 {'sha256': '576f3eb0151cf9c4f15a3627ccd76dced5cd4a2f0c2cbcfaa986697cc95e879e',
  'fileIdentifier': 'https://sketchfab.com/3d-models/6c1b44e0848347299aa3676d1de38a2d',
  'source': 'sketchfab'},
 {'sha256': '7819617c8198aa1fa197fda61ad0899ee1194a4fd9f4205711e19c4ee51563d5',
  'fileIdentifier': 'https://sketchfab.com/3d-models/9869ead903f84a37a9aa61b6c60c3a93',
  'source': 'sketchfab'},
 {'sha256': '5082735dbc259ad991d5db0a09127782bbb4d776393b2b3d0da74172045efedd',
  'fileIdentifier': 'https://sketchfab.com/3d-models/4491c046bbe849c58fc52408c57f3549',
  'source': 'sketchfab'},
 {'sha256': 'e55fc359787976ab8b3c995666764a3120f43c93480feccf086e8524414a64b5',
  'fileIdentifier': 'https://sketchfab.com/3d-models/4d8d446e4d0149feb2b84127cc106df7',
  'source': 'sketchfab'},
 {'sha256': 'a31bce03891218441ec396a8f8a6ea80faa719a12da5e6dda9ab2c91970da892',
  'fileIdentifier': 'https://sketchfab.com/3d-models/22929fd1943945118562ff2e6fd2f35d',
  'source': 'sketchfab'},
 {'sha256': 'edd8de5485160a19bc5e0de55278e055089cb96209bd9517801410a83326bd4b',
  'fileIdentifier': 'https://sketchfab.com/3d-models/0859bd17564f4747b87ecec7d6c57b22',
  'source': 'sketchfab'},
 {'sha256': '536db46e67d566cc5228a79b2d8c1d7ca76aabf83e6cac9ad29d7b529fa7bece',
  'fileIdentifier': 'https://sketchfab.com/3d-models/fe96368b814e4a54b41cedfcbe8b970a',
  'source': 'sketchfab'},
 {'sha256': '191f5a7557fff13ca2067115b91771b73202688dac64ef7ccf905ead139607ab',
  'fileIdentifier': 'https://sketchfab.com/3d-models/ab3e5682eeeb4dc2b176d47160242839',
  'source': 'sketchfab'},
 {'sha256': '1d6734b6cf9695c90bd9e078f3ca0c29125b2711e69b5c6b5d8dbeb925ad4413',
  'fileIdentifier': 'https://sketchfab.com/3d-models/bb571a973e494c899dd9b153489aae0a',
  'source': 'sketchfab'},
 {'sha256': '955225ae96bcae623de678c19c74bdfa792057d1cd434ce56e1c4e738ef3ce68',
  'fileIdentifier': 'https://sketchfab.com/3d-models/d65a36094248427aacd138fde3a7cb9f',
  'source': 'sketchfab'},
 {'sha256': 'fd939e60ab67edc335c0019e5699fd564fa425e8846238587d90ca6b8ce36d52',
  'fileIdentifier': 'https://sketchfab.com/3d-models/92e9c5d41cf6422e84bc2e81d8a6a4d1',
  'source': 'sketchfab'},
 {'sha256': '22204b62acc0a30b05b5475d18699fd0139ff9456ef16330efdb0b3db88d0cd2',
  'fileIdentifier': 'https://sketchfab.com/3d-models/ac71a0a0c5154f95845f16cfefdb6e18',
  'source': 'sketchfab'},
 {'sha256': '4606b94036a0dfdb64144db929eb0f3d21e9328076c9b2f77c82d0bf67a9f480',
  'fileIdentifier': 'https://sketchfab.com/3d-models/92dd6344744e4ddd89dd554cefec9057',
  'source': 'sketchfab'},
 {'sha256': 'f74df73c53e7f2c5b86373e668e41ca0152434cb51bda9ace5b14c7463bbff92',
  'fileIdentifier': 'https://sketchfab.com/3d-models/a2efbf1d6be848b984fd9bedffc549a5',
  'source': 'sketchfab'},
 {'sha256': '5e991a5b840a8b418e1b6f659641429803f50538cae546fb5ef53f659b5db048',
  'fileIdentifier': 'https://sketchfab.com/3d-models/18797382d5d048df9babfb57809cefd6',
  'source': 'sketchfab'},
 {'sha256': 'd261a3ebe1597682293fafcabdbbeb7c7df4f9a94716eb7b1c15f86e52934a65',
  'fileIdentifier': 'https://sketchfab.com/3d-models/4f63ec1d217845b994a627d4053bc7a2',
  'source': 'sketchfab'},
 {'sha256': 'a3e867e3fdf04fe7634ad76a69a040a6866410b6e2492a8e52faad23776e5b1f',
  'fileIdentifier': 'https://sketchfab.com/3d-models/8668a2b3e5e743248b3fd64fb6246a0a',
  'source': 'sketchfab'},
 {'sha256': '4277b6ef3aa1f0c10b0c6d892e40fe314b6aa06a1c5950397896e3bf53e97e64',
  'fileIdentifier': 'https://sketchfab.com/3d-models/c665d3c997e64828b24e5dddeabced8e',
  'source': 'sketchfab'},
 {'sha256': '86a841c02e65bfd114a6a7e62c5d8c84b58e1a7913ff9f28c5b2fa101c67c1da',
  'fileIdentifier': 'https://sketchfab.com/3d-models/6ffd7a7a5da647ed8508fae3b6f4d812',
  'source': 'sketchfab'},
 {'sha256': '14e5e1f8eaa96ed9dcd5d2aed3216871d909706f8000b62524e30343f5344b9e',
  'fileIdentifier': 'https://sketchfab.com/3d-models/2645585305c24a30bfaa63a63450b084',
  'source': 'sketchfab'},
 {'sha256': '0696cf73cc248196d53cd69a7d6c01c3fc196ee576f49eabacd6508339f33514',
  'fileIdentifier': 'https://sketchfab.com/3d-models/f7799baf56fb46918fde5553da579a81',
  'source': 'sketchfab'},
 {'sha256': '13998a6fde83d6442f59474ea7f5f8d15ebc644e6a729bf8b0271ef59b886101',
  'fileIdentifier': 'https://sketchfab.com/3d-models/33ba9101817a4ed5827ea906766c02b7',
  'source': 'sketchfab'},
 {'sha256': '0a77ecabaed83a091c3510d59d29c6ba74c3fe637b6c45dd235e8f6ba6cb7b53',
  'fileIdentifier': 'https://sketchfab.com/3d-models/edad0f3225364ea896dbe2d8519e6981',
  'source': 'sketchfab'},
 {'sha256': '412f9ec5d45d5e9ca3df35e52a4fd233f55c013ee0a3ba59ccb649a5dcd706c6',
  'fileIdentifier': 'https://sketchfab.com/3d-models/9ad672c7b3ae4723a465873ce8a7b79f',
  'source': 'sketchfab'},
 {'sha256': '426ba20cbfbf8f2056320ade48619ca89f4821c2c1f1eb134682d7d6d1e4b184',
  'fileIdentifier': 'https://sketchfab.com/3d-models/fc97aebb2342487dbc3b1c4445f54155',
  'source': 'sketchfab'},
 {'sha256': '7ee4b3dc0504a7fa9c1c24266a602f76100903c0b0c64ff003a6278bc0978a7a',
  'fileIdentifier': 'https://sketchfab.com/3d-models/7755623b72f3455886912ef1f31f1ca4',
  'source': 'sketchfab'},
 {'sha256': 'f4041e326051ec4f227b47317bf3d19c1c92f825dbf4c0f147b5fa64b6e3f794',
  'fileIdentifier': 'https://sketchfab.com/3d-models/8c0be01b915a4bf7975404094c41ef1d',
  'source': 'sketchfab'},
 {'sha256': '8616d5163d53cd5315ae6eaf4b8c8b3240f6561fbb7d999586222b2bc4677b5a',
  'fileIdentifier': 'https://sketchfab.com/3d-models/284abe54a4464b6ab99c93d4be3c2c6b',
  'source': 'sketchfab'},
 {'sha256': '21bfd79d2d560b80d468255ae2133aff433002af2a088fa796d7ed74a2fbcc09',
  'fileIdentifier': 'https://sketchfab.com/3d-models/a6c5247ee6cf46e7b6f32a4df9d3ca24',
  'source': 'sketchfab'},
 {'sha256': '09e8bc9d26d1e6e5bcc3544b10474cf627692d5a11c6d2c59c9f2df994dcd62e',
  'fileIdentifier': 'https://sketchfab.com/3d-models/eea22935209d4a9f8fb61092f91b36d0',
  'source': 'sketchfab'},
 {'sha256': '27e4e4103ab8628dc894898420dd2e28b1c90ee7769bd27a44947691c0678e65',
  'fileIdentifier': 'https://sketchfab.com/3d-models/f4f04b082af5442f914fd4a72640a76e',
  'source': 'sketchfab'},
 {'sha256': 'c1c0aec8386758b0204d4d61904295376a85640018a6c5e8d953a0d83d11010d',
  'fileIdentifier': 'https://sketchfab.com/3d-models/7515263af5474063b0b538a6f1b55dc9',
  'source': 'sketchfab'},
 {'sha256': '4b03f2ff19d3790dbbc93c2bd9982df3ded572facd94c80af8992fd5c134e570',
  'fileIdentifier': 'https://sketchfab.com/3d-models/ecdb7e9060ca45a3921c7c43b4084153',
  'source': 'sketchfab'},
 {'sha256': '36b2eedc120b333c83de5c52d7b2547cacf4ebd53d0bfaf2b002c464364bced4',
  'fileIdentifier': 'https://sketchfab.com/3d-models/cc1f88455e2e44ce882cfb88886c0db7',
  'source': 'sketchfab'},
 {'sha256': 'cc368a8f5d95da248d1506c0b2f890f6617c9d2a33f56cc5c15494d64e11274b',
  'fileIdentifier': 'https://sketchfab.com/3d-models/9e8eac6922ee4b02bc8446fb41d3e8f4',
  'source': 'sketchfab'},
 {'sha256': 'd79e428e440b914ea004220f165e9377fa7d9be7a6a3978012ebceb278cea5a0',
  'fileIdentifier': 'https://sketchfab.com/3d-models/ab75b36b814540edafbe636c6fd3f3ae',
  'source': 'sketchfab'},
 {'sha256': '1805e3e155bdc0b163f783b7ff4b7138dfe64191b8c213b943681669cceebf31',
  'fileIdentifier': 'https://sketchfab.com/3d-models/a153134ea8cd4a2fb01da79595a892e4',
  'source': 'sketchfab'},
 {'sha256': '3838707203a821a9bf90403b23d8f448391ebe6fc8bfa4f398689ae071e6970f',
  'fileIdentifier': 'https://sketchfab.com/3d-models/65dcebe837d34f13ae6c7dc2fa3b79fc',
  'source': 'sketchfab'},
 {'sha256': 'e163b0132b208b3fbf250d70e32d411b69f0370443c298f0ac8f1d61af8d9869',
  'fileIdentifier': 'https://sketchfab.com/3d-models/75bdec09d9ce4651b2773ee48fe13a08',
  'source': 'sketchfab'},
 {'sha256': '90e0f661a4a49b8a3e086c24296ca74bfcb80decd6de8ebe9670ccbd08fd1ed7',
  'fileIdentifier': 'https://sketchfab.com/3d-models/46066ddab8db4729921a5260a0f84ecf',
  'source': 'sketchfab'},
 {'sha256': 'ff444740f6c92e969377c43e48e0875f94526b75b1d46514a7a3ccb82477c4bd',
  'fileIdentifier': 'https://sketchfab.com/3d-models/69cf9bd15acf44f590b65b21e07a2d63',
  'source': 'sketchfab'},
 {'sha256': 'f0081bd5d029336fd5bc9fe6e6b17873e8c928d14cf0079545752ffe4c2b518f',
  'fileIdentifier': 'https://sketchfab.com/3d-models/a4d838e8fa224fdba861b07de0127e97',
  'source': 'sketchfab'},
 {'sha256': '6f8fedd739ab178fe1d01525cfe10b58f594f580255ce34b577fb1152716e01a',
  'fileIdentifier': 'https://sketchfab.com/3d-models/dafcc83828814524b88751266f353b24',
  'source': 'sketchfab'},
 {'sha256': '57c71a396b27d9e9cee5ddf59e9c088de64c925405f33e42cb7151fa1f90f0a0',
  'fileIdentifier': 'https://sketchfab.com/3d-models/4ecbb77898d1437ca54d99bb74572686',
  'source': 'sketchfab'},
 {'sha256': '1dba1fa3319c45220b8cde2b84b8b9eb7135c2470bfb3d3209a578b79e43addf',
  'fileIdentifier': 'https://sketchfab.com/3d-models/f30d8ab84cb948709710fa7d0e1495f8',
  'source': 'sketchfab'},
 {'sha256': 'a7c38293f02c6884df5f8f59d3e312e024dd094c9bbd0a46aaa29a11ac571220',
  'fileIdentifier': 'https://sketchfab.com/3d-models/cc9d3e0368124bf8a339d4f1fc85743f',
  'source': 'sketchfab'},
 {'sha256': '73c7186e6f33687cad0385e00bf39fc922a3ae1bfd802fa4ce1e7447d43a2822',
  'fileIdentifier': 'https://sketchfab.com/3d-models/da3765e522a44c7a963078d904454056',
  'source': 'sketchfab'},
 {'sha256': 'b5699e8baadcf6a9b85025ec751da20edf7e5fd84afcae2b3d2606c08ed65251',
  'fileIdentifier': 'https://sketchfab.com/3d-models/baed2b671fc64bc3a74d9fcc4033e2e9',
  'source': 'sketchfab'},
 {'sha256': '974eed3743d38235064f81df9d1ef2fa4ea60c17122782d2a36e3c369eb582a4',
  'fileIdentifier': 'https://sketchfab.com/3d-models/f6a3560135cb4c31bc3bfb1476d86ed8',
  'source': 'sketchfab'},
 {'sha256': '9d17066cafc2a9743d58de8d52a2fabb96d4d8919cf9a8c2f2b006eb0a1289be',
  'fileIdentifier': 'https://sketchfab.com/3d-models/2e0c23f32db249bdab3be206b75df0bc',
  'source': 'sketchfab'},
 {'sha256': 'aaae333fd5426fd366007c4172bdb7e85422e11d1f28fd8160b0d1e36ec26724',
  'fileIdentifier': 'https://sketchfab.com/3d-models/e1748cef902849909bbacbe3dae266ae',
  'source': 'sketchfab'},
 {'sha256': 'dafaa8bacc7f908bef0fe9733d3321ec2018df0bbef67da92a38e00348493a10',
  'fileIdentifier': 'https://sketchfab.com/3d-models/b9b62de756a447f8b11353e368920091',
  'source': 'sketchfab'},
 {'sha256': '07fcbd000c2aa4cb92c0df29eb9438a90b123627bad0a8b5634f7bb407c4c582',
  'fileIdentifier': 'https://sketchfab.com/3d-models/8611d3ff27054e33b4a34e434448447c',
  'source': 'sketchfab'},
 {'sha256': '81bebf09f9efb8e0becb0692ace5d1a62f5a41d94901b87ce74aecc318ba749a',
  'fileIdentifier': 'https://sketchfab.com/3d-models/a582b56dfa2c4fdca77ca493ad38620d',
  'source': 'sketchfab'},
 {'sha256': 'df5dac701a10873af08b23eb1f1f7dbfa098a9c3ccc62015b1b885a7ae28c936',
  'fileIdentifier': 'https://sketchfab.com/3d-models/c313236be20b4cdcb707badbbbe2c910',
  'source': 'sketchfab'},
 {'sha256': 'a68a0238fdd650ce161e50f261b22057461f4a3091ce1ef90560cad167e06aa3',
  'fileIdentifier': 'https://sketchfab.com/3d-models/b8f10b3e408245acaf035c529dfe39f2',
  'source': 'sketchfab'},
 {'sha256': 'c074baf45fdcf75d3dcc7cb57460b4fa8740e1c3d23008e2a7a6b106e1a92098',
  'fileIdentifier': 'https://sketchfab.com/3d-models/4bb7c6bf189a499783f3c769a3508823',
  'source': 'sketchfab'},
 {'sha256': '253bfa383067e6de1c8b1c37df28b3f521f4c9322f20b9ce59a5fc309a7d5ed1',
  'fileIdentifier': 'https://sketchfab.com/3d-models/62d716606a6d4220886b91664b67abff',
  'source': 'sketchfab'},
 {'sha256': 'db4167c67db3ba0e623d11ea381bd7e92b568449276d9c818114d07c481bb796',
  'fileIdentifier': 'https://sketchfab.com/3d-models/805e1351548b47f090529d1192bd1f8e',
  'source': 'sketchfab'},
 {'sha256': '676b66c1ec2c2280a85109ca56f1c74d5dbd6a0d8a302c5b15ecf1ddcf32af80',
  'fileIdentifier': 'https://sketchfab.com/3d-models/4bc23ae1953c48e3b56cdcc60d6be110',
  'source': 'sketchfab'},
 {'sha256': '347b7615aab1079b7230d27e98153f1c9649d0a7c4cde6d14d27bab64b4d61ba',
  'fileIdentifier': 'https://sketchfab.com/3d-models/2c890c6acd754ca1b0abf11b7f7ffa3e',
  'source': 'sketchfab'},
 {'sha256': '2624783fa5caa5c3c3dbf2062b519de43648fab10946e62e8d21e8aca86c81cd',
  'fileIdentifier': 'https://sketchfab.com/3d-models/2bf17251cd6b4635a83445dc79186322',
  'source': 'sketchfab'},
 {'sha256': '44a1dfb860ff098bbdc3af4145b8a19e7d6fd6db7ebdfcc7c18a13304aa67bd8',
  'fileIdentifier': 'https://sketchfab.com/3d-models/7dad1ab4c66949578f436543bd2419c8',
  'source': 'sketchfab'},
 {'sha256': 'd8d5947d8f14ba758bcb1c0ac7dcba093eda0a904dca1e2153e245ad87df2e82',
  'fileIdentifier': 'https://sketchfab.com/3d-models/a745fdd7c808472a8f70342cc6d5a4d7',
  'source': 'sketchfab'},
 {'sha256': '775de5e9f9187e283ba54bc428164d1633153a401e91d2726e20c1dc969c62dc',
  'fileIdentifier': 'https://sketchfab.com/3d-models/a98372bdac824a91aaf6dbd4984640e1',
  'source': 'sketchfab'},
 {'sha256': 'ea61d61d6f7797d6e1d5a9bd7bcada92f0ddcaeb8acd4e5c8f2c5fb064940bae',
  'fileIdentifier': 'https://sketchfab.com/3d-models/4b1269cba4d04486acebe11bf052180a',
  'source': 'sketchfab'},
 {'sha256': 'fd3ea6beda844f508bd6fdd7c9a7d6c232a50a6f84cf9d915c528620863feb1d',
  'fileIdentifier': 'https://sketchfab.com/3d-models/4dbe0be014d14c27a262e81a5e0046fb',
  'source': 'sketchfab'},
 {'sha256': '338ece50b36e8bcc249bb1cfd250f1ade5126698c23c7c5c60d92945c8e0d728',
  'fileIdentifier': 'https://sketchfab.com/3d-models/ce286225d5fd436d927099bcbca8ac40',
  'source': 'sketchfab'},

In [136]:
sampled_json

{'3a8400337ce34c728a23fe65660e76a1': {'uri': 'https://api.sketchfab.com/v3/models/3a8400337ce34c728a23fe65660e76a1',
  'uid': '3a8400337ce34c728a23fe65660e76a1',
  'name': 'Chair',
  'staffpickedAt': None,
  'viewCount': 9,
  'likeCount': 0,
  'animationCount': 0,
  'viewerUrl': 'https://sketchfab.com/3d-models/3a8400337ce34c728a23fe65660e76a1',
  'embedUrl': 'https://sketchfab.com/models/3a8400337ce34c728a23fe65660e76a1/embed',
  'commentCount': 0,
  'isDownloadable': True,
  'publishedAt': '2019-05-03T19:46:02.400841',
  'tags': [{'name': 'c',
    'slug': 'c',
    'uri': 'https://api.sketchfab.com/v3/tags/c'},
   {'name': 'furniture',
    'slug': 'furniture',
    'uri': 'https://api.sketchfab.com/v3/tags/furniture'},
   {'name': 'chair',
    'slug': 'chair',
    'uri': 'https://api.sketchfab.com/v3/tags/chair'},
   {'name': 'model',
    'slug': 'model',
    'uri': 'https://api.sketchfab.com/v3/tags/model'}],
  'categories': [],
  'thumbnails': {'images': [{'uid': 'f813a03e220f47f39ff2fbca580402ac',
     'size': 46117,
     'width': 1920,
     'url': 'https://media.sketchfab.com/models/3a8400337ce34c728a23fe65660e76a1/thumbnails/2b700a194f174b0a904d39419b80a245/1e4bcb85fd1745adb5027f75f8be6aff.jpeg',
     'height': 1080},
    {'uid': '45b7c4b0e2734432bec738b82db607c5',
     'size': 16597,
     'width': 1024,
     'url': 'https://media.sketchfab.com/models/3a8400337ce34c728a23fe65660e76a1/thumbnails/2b700a194f174b0a904d39419b80a245/ddf3a816d0c240caaa0987713945aea1.jpeg',
     'height': 576},
    {'uid': '020a0fb33bf7487db0152a318f89e1ee',
     'size': 10348,
     'width': 720,
     'url': 'https://media.sketchfab.com/models/3a8400337ce34c728a23fe65660e76a1/thumbnails/2b700a194f174b0a904d39419b80a245/50e3305b6ac54f879b255c9e0d2ae255.jpeg',
     'height': 405},
    {'uid': '27dfa31da85a4216abdc28b5bd54603e',
     'size': 2582,
     'width': 256,
     'url': 'https://media.sketchfab.com/models/3a8400337ce34c728a23fe65660e76a1/thumbnails/2b700a194f174b0a904d39419b80a245/b4224e74768d46d08759478c9be354b7.jpeg',
     'height': 144},
    {'uid': 'f39f1a3ecf5c47cf97a45b16ffcaed15',
     'size': 632,
     'width': 64,
     'url': 'https://media.sketchfab.com/models/3a8400337ce34c728a23fe65660e76a1/thumbnails/2b700a194f174b0a904d39419b80a245/3885165d2015471da9714a2c3d41c0a7.jpeg',
     'height': 36}]},
  'user': {'uid': '50d950fd00a74ac692d1e9d3dc6f0aad',
   'username': 'samjhay98',
   'displayName': 'samjhay98',
   'profileUrl': 'https://sketchfab.com/samjhay98',
   'account': 'basic',
   'avatar': {'uri': 'https://api.sketchfab.com/v3/avatars/bb34cd7ff22b4d22936884243d9e94c0',
    'images': [{'size': 2354,
      'width': 32,
      'url': 'https://media.sketchfab.com/avatars/bb34cd7ff22b4d22936884243d9e94c0/cb1a172a5b6f442c8a89f3f44ad7a138.png',
      'height': 32},
     {'size': 4688,
      'width': 48,
      'url': 'https://media.sketchfab.com/avatars/bb34cd7ff22b4d22936884243d9e94c0/f430554e5bc04a949fc439a05b544466.png',
      'height': 48},
     {'size': 13736,
      'width': 90,
      'url': 'https://media.sketchfab.com/avatars/bb34cd7ff22b4d22936884243d9e94c0/1ced6d0fb41e455997fdad316bdaebb4.png',
      'height': 90},
     {'size': 16709,
      'width': 100,
      'url': 'https://media.sketchfab.com/avatars/bb34cd7ff22b4d22936884243d9e94c0/78ce445b898242ddbd4056a3470bab73.png',
      'height': 100}]},
   'uri': 'https://api.sketchfab.com/v3/users/50d950fd00a74ac692d1e9d3dc6f0aad'},
  'description': '',
  'faceCount': 26104,
  'createdAt': '2019-05-03T18:25:18.763069',
  'vertexCount': 13139,
  'isAgeRestricted': False,
  'archives': {'glb': {'textureCount': 0,
    'size': 922584,
    'type': 'glb',
    'textureMaxResolution': 0,
    'faceCount': 26104,
    'vertexCount': 18980},
   'gltf': {'textureCount': 0,
    'size': 359199,
    'type': 'gltf',
    'textureMaxResolution': 0,
    'faceCount': 26104,
    'vertexCount': 18980},
   'source': {'textureCount': None,
    'size': 769826,
    'type': 'source',
    'textureMaxResolution': None,
    'faceCount': None,
    'vertexCount': None},
   'usdz': {'textureCount': None,
    'size': 501977,
    'type': 'usdz',
    'textureMaxResolution': None,
    'faceCount': None,
    'vertexCount': None}},
  'license': 'by'},
 'beccd2f9e8724ca6844a458376ebd2d8': {'uri': 'https://api.sketchfab.com/v3/models/beccd2f9e8724ca6844a458376ebd2d8',
  'uid': 'beccd2f9e8724ca6844a458376ebd2d8',
  'name': 'Beanbag chair',
  'staffpickedAt': None,
  'viewCount': 601,
  'likeCount': 7,
  'animationCount': 0,
  'viewerUrl': 'https://sketchfab.com/3d-models/beccd2f9e8724ca6844a458376ebd2d8',
  'embedUrl': 'https://sketchfab.com/models/beccd2f9e8724ca6844a458376ebd2d8/embed',
  'commentCount': 0,
  'isDownloadable': True,
  'publishedAt': '2022-01-20T16:01:34.703211',
  'tags': [{'name': 'furniture',
    'slug': 'furniture',
    'uri': 'https://api.sketchfab.com/v3/tags/furniture'},
   {'name': 'uvmapped',
    'slug': 'uvmapped',
    'uri': 'https://api.sketchfab.com/v3/tags/uvmapped'},
   {'name': 'beanbag',
    'slug': 'beanbag',
    'uri': 'https://api.sketchfab.com/v3/tags/beanbag'},
   {'name': 'low-poly',
    'slug': 'low-poly',
    'uri': 'https://api.sketchfab.com/v3/tags/low-poly'},
   {'name': 'chair',
    'slug': 'chair',
    'uri': 'https://api.sketchfab.com/v3/tags/chair'}],
  'categories': [{'name': 'furniture-home'}],
  'thumbnails': {'images': [{'uid': 'df09022d2a554ffe8b8b44252116299e',
     'size': 342175,
     'width': 1920,
     'url': 'https://media.sketchfab.com/models/beccd2f9e8724ca6844a458376ebd2d8/thumbnails/3a72b1b85dc4404badb071a6f384fbe1/e22ebca1f3484da29ef30f2b389ac749.jpeg',
     'height': 1080},
    {'uid': 'c94bb5ba2c2f497f91f0044f48596062',
     'size': 30437,
     'width': 1024,
     'url': 'https://media.sketchfab.com/models/beccd2f9e8724ca6844a458376ebd2d8/thumbnails/3a72b1b85dc4404badb071a6f384fbe1/e25df6292b7d403ba59af54cd128a36d.jpeg',
     'height': 576},
    {'uid': '7125b9d6a4374b9fb6f72a92396832aa',
     'size': 15616,
     'width': 720,
     'url': 'https://media.sketchfab.com/models/beccd2f9e8724ca6844a458376ebd2d8/thumbnails/3a72b1b85dc4404badb071a6f384fbe1/8b7c4f65342a48fe902becfc92bcc127.jpeg',
     'height': 405},
    {'uid': '9760c6a5c2284d398f095439203f7926',
     'size': 3607,
     'width': 256,
     'url': 'https://media.sketchfab.com/models/beccd2f9e8724ca6844a458376ebd2d8/thumbnails/3a72b1b85dc4404badb071a6f384fbe1/9c21a41174864952854172d05b7c0273.jpeg',
     'height': 144},
    {'uid': 'd75999c24a7145c5895a66d3e31c219c',
     'size': 1106,
     'width': 64,
     'url': 'https://media.sketchfab.com/models/beccd2f9e8724ca6844a458376ebd2d8/thumbnails/3a72b1b85dc4404badb071a6f384fbe1/787299c8989d4a76b8a7834b86c4c8f2.jpeg',
     'height': 36}]},
  'user': {'uid': '3d3744ef12574f2dbe12a85df7784405',
   'username': 'JasperRamune',
   'displayName': 'Jasper',
   'profileUrl': 'https://sketchfab.com/JasperRamune',
   'account': 'basic',
   'avatar': {'uri': 'https://api.sketchfab.com/v3/avatars/d18e5333b5254415ba9e90e45b482676',
    'images': [{'size': 2035,
      'width': 32,
      'url': 'https://media.sketchfab.com/avatars/d18e5333b5254415ba9e90e45b482676/41d02b4da9dd435f8a39a2f41eb0881f.png',
      'height': 32},
     {'size': 3995,
      'width': 48,
      'url': 'https://media.sketchfab.com/avatars/d18e5333b5254415ba9e90e45b482676/f4c0031e389445a4b6297debfa06ad3f.png',
      'height': 48},
     {'size': 11552,
      'width': 90,
      'url': 'https://media.sketchfab.com/avatars/d18e5333b5254415ba9e90e45b482676/474a30c1d22c46848d4ca94bf7442b28.png',
      'height': 90},
     {'size': 13838,
      'width': 100,
      'url': 'https://media.sketchfab.com/avatars/d18e5333b5254415ba9e90e45b482676/ea4b1350f9674fd4b877dad909eb5987.png',
      'height': 100}]},
   'uri': 'https://api.sketchfab.com/v3/users/3d3744ef12574f2dbe12a85df7784405'},
  'description': 'Beanbag chair modeled in Marvelous Design and edited in Blender, model has 6,418 Tris and 3,422 Verts.',
  'faceCount': 6418,
  'createdAt': '2022-01-20T15:48:06.415702',
  'vertexCount': 3262,
  'isAgeRestricted': False,
  'archives': {'glb': {'textureCount': 3,
    'size': 40828224,
    'type': 'glb',
    'textureMaxResolution': 4096,
    'faceCount': 6418,
    'vertexCount': 3438},
   'gltf': {'textureCount': 3,
    'size': 40578397,
    'type': 'gltf',
    'textureMaxResolution': 4096,
    'faceCount': 6418,
    'vertexCount': 3438},
   'source': {'textureCount': None,
    'size': 86409276,
    'type': 'source',
    'textureMaxResolution': None,
    'faceCount': None,
    'vertexCount': None},
   'usdz': {'textureCount': None,
    'size': 5586304,
    'type': 'usdz',
    'textureMaxResolution': None,
    'faceCount': None,
    'vertexCount': None}},
  'license': 'by'},
 '71138f7413944641a93ef744c43ae18a': {'uri': 'https://api.sketchfab.com/v3/models/71138f7413944641a93ef744c43ae18a',
  'uid': '71138f7413944641a93ef744c43ae18a',
  'name': 'Chair',
  'staffpickedAt': None,
  'viewCount': 26,
  'likeCount': 0,
  'animationCount': 0,
  'viewerUrl': 'https://sketchfab.com/3d-models/71138f7413944641a93ef744c43ae18a',
  'embedUrl': 'https://sketchfab.com/models/71138f7413944641a93ef744c43ae18a/embed',
  'commentCount': 0,
  'isDownloadable': True,
  'publishedAt': '2019-12-18T10:27:26.918775',
  'tags': [],
  'categories': [],
  'thumbnails': {'images': [{'uid': '005481e0656e4286b44a2b89b884f8f9',
     'size': 30338,
     'width': 1920,
     'url': 'https://media.sketchfab.com/models/71138f7413944641a93ef744c43ae18a/thumbnails/c7d813c054b649ecb7a1641b6e781104/fd932105bcf54403a53a86b2d54f3aa5.jpeg',
     'height': 1080},
    {'uid': 'e10784970d1b4c5caf6e7127bd91ed90',
     'size': 11279,
     'width': 1024,
     'url': 'https://media.sketchfab.com/models/71138f7413944641a93ef744c43ae18a/thumbnails/c7d813c054b649ecb7a1641b6e781104/6a67e2be3cd945db87e15a69e7529f43.jpeg',
     'height': 576},
    {'uid': '3858cb5fed314f409d665ea53b773006',
     'size': 7119,
     'width': 720,
     'url': 'https://media.sketchfab.com/models/71138f7413944641a93ef744c43ae18a/thumbnails/c7d813c054b649ecb7a1641b6e781104/a8095139aeb34448bcbfa6635254e8d2.jpeg',
     'height': 405},
    {'uid': 'ab483c71baa94ca6b29f996a3a2e68e7',
     'size': 1898,
     'width': 256,
     'url': 'https://media.sketchfab.com/models/71138f7413944641a93ef744c43ae18a/thumbnails/c7d813c054b649ecb7a1641b6e781104/c31e7a2a271d403cb058d7c15e779bae.jpeg',
     'height': 144},
    {'uid': '5facfcefa1d44ea29fed6b24d90bc439',
     'size': 559,
     'width': 64,
     'url': 'https://media.sketchfab.com/models/71138f7413944641a93ef744c43ae18a/thumbnails/c7d813c054b649ecb7a1641b6e781104/a4d5256f268c49868ef59e8876c10e31.jpeg',
     'height': 36}]},
  'user': {'uid': '2dc8746ca5e14a198497f2433460ac0d',
   'username': 'darrendao',
   'displayName': 'darrendao',
   'profileUrl': 'https://sketchfab.com/darrendao',
   'account': 'basic',
   'avatar': {'uri': 'https://api.sketchfab.com/v3/avatars/e5f5a5d5dcee4ccd8befb81217ca2628',
    'images': [{'size': 722,
      'width': 32,
      'url': 'https://media.sketchfab.com/avatars/e5f5a5d5dcee4ccd8befb81217ca2628/2291c19ac6384fee9f55c036b37acdb0.jpeg',
      'height': 32},
     {'size': 1155,
      'width': 48,
      'url': 'https://media.sketchfab.com/avatars/e5f5a5d5dcee4ccd8befb81217ca2628/601cc3297c064503ac1912ea2049ab20.jpeg',
      'height': 48},
     {'size': 2567,
      'width': 90,
      'url': 'https://media.sketchfab.com/avatars/e5f5a5d5dcee4ccd8befb81217ca2628/f5b1296edcad47e98512418c0d779573.jpeg',
      'height': 90},
     {'size': 2806,
      'width': 100,
      'url': 'https://media.sketchfab.com/avatars/e5f5a5d5dcee4ccd8befb81217ca2628/c8d1fb8a2ca14e40a6e5cc64f0f20c17.jpeg',
      'height': 100}]},
   'uri': 'https://api.sketchfab.com/v3/users/2dc8746ca5e14a198497f2433460ac0d'},
  'description': '',
  'faceCount': 17471,
  'createdAt': '2019-12-18T10:20:19.310158',
  'vertexCount': 8798,
  'isAgeRestricted': False,
  'archives': {'glb': {'textureCount': 0,
    'size': 774276,
    'type': 'glb',
    'textureMaxResolution': 0,
    'faceCount': 17471,
    'vertexCount': 17545},
   'gltf': {'textureCount': 0,
    'size': 349947,
    'type': 'gltf',
    'textureMaxResolution': 0,
    'faceCount': 17471,
    'vertexCount': 17545},
   'source': {'textureCount': None,
    'size': 1887054,
    'type': 'source',
    'textureMaxResolution': None,
    'faceCount': None,
    'vertexCount': None},
   'usdz': {'textureCount': None,
    'size': 504249,
    'type': 'usdz',
    'textureMaxResolution': None,
    'faceCount': None,
    'vertexCount': None}},
  'license': 'by'},
 '5c8cd1a462ce44f9af810b544b592b1a': {'uri': 'https://api.sketchfab.com/v3/models/5c8cd1a462ce44f9af810b544b592b1a',
  'uid': '5c8cd1a462ce44f9af810b544b592b1a',
  'name': 'Chair Flip for Methylcyclohexane',
  'staffpickedAt': None,
  'viewCount': 114,
  'likeCount': 1,
  'animationCount': 1,
  'viewerUrl': 'https://sketchfab.com/3d-models/5c8cd1a462ce44f9af810b544b592b1a',
  'embedUrl': 'https://sketchfab.com/models/5c8cd1a462ce44f9af810b544b592b1a/embed',
  'commentCount': 0,
  'isDownloadable': True,
  'publishedAt': '2021-09-16T00:47:58.337258',
  'tags': [{'name': 'education',
    'slug': 'education',
    'uri': 'https://api.sketchfab.com/v3/tags/education'},
   {'name': 'chemistry',
    'slug': 'chemistry',
    'uri': 'https://api.sketchfab.com/v3/tags/chemistry'},
   {'name': 'molecular_motion',
    'slug': 'molecular_motion',
    'uri': 'https://api.sketchfab.com/v3/tags/molecular_motion'}],
  'categories': [{'name': 'science-technology'}],
  'thumbnails': {'images': [{'uid': 'fda10d75166b4d2a838e150c2f4e9662',
     'size': 59210,
     'width': 1920,
     'url': 'https://media.sketchfab.com/models/5c8cd1a462ce44f9af810b544b592b1a/thumbnails/3b55acccd7b4454e843cb1c8341878ff/6897a469430a462a8a7a75e73333ad1b.jpeg',
     'height': 1080},
    {'uid': '7d916b93b4cb4db3b0b5271698c3038e',
     'size': 21227,
     'width': 1024,
     'url': 'https://media.sketchfab.com/models/5c8cd1a462ce44f9af810b544b592b1a/thumbnails/3b55acccd7b4454e843cb1c8341878ff/8894fb3829274066b8832a383be2973f.jpeg',
     'height': 576},
    {'uid': '738c44945ac441c893ea1470eef4788f',
     'size': 13010,
     'width': 720,
     'url': 'https://media.sketchfab.com/models/5c8cd1a462ce44f9af810b544b592b1a/thumbnails/3b55acccd7b4454e843cb1c8341878ff/e5d23f15745f4c1cad34661b5428d50e.jpeg',
     'height': 405},
    {'uid': '3337047d6dd54ad0811905060233ab99',
     'size': 3326,
     'width': 256,
     'url': 'https://media.sketchfab.com/models/5c8cd1a462ce44f9af810b544b592b1a/thumbnails/3b55acccd7b4454e843cb1c8341878ff/9afc6aafd5fa46ed950d001e223cead8.jpeg',
     'height': 144},
    {'uid': 'ca3da7ced586491d8ed26320060e29c1',
     'size': 966,
     'width': 64,
     'url': 'https://media.sketchfab.com/models/5c8cd1a462ce44f9af810b544b592b1a/thumbnails/3b55acccd7b4454e843cb1c8341878ff/8bc1ce680e2648b1b5592f8eb683d2e2.jpeg',
     'height': 36}]},
  'user': {'uid': '7c59850017a847cb80452f0f942d0839',
   'username': 'Michael.Aristov',
   'displayName': 'Michael Aristov',
   'profileUrl': 'https://sketchfab.com/Michael.Aristov',
   'account': 'basic',
   'avatar': {'uri': 'https://api.sketchfab.com/v3/avatars/a52a569eb88646aa8d86b838da005060',
    'images': [{'size': 704,
      'width': 32,
      'url': 'https://media.sketchfab.com/avatars/a52a569eb88646aa8d86b838da005060/5ea2db42f659476598316250c4be4e23.jpeg',
      'height': 32},
     {'size': 1083,
      'width': 48,
      'url': 'https://media.sketchfab.com/avatars/a52a569eb88646aa8d86b838da005060/f4563c4f5daa44d2a3e1d751df147448.jpeg',
      'height': 48},
     {'size': 2861,
      'width': 90,
      'url': 'https://media.sketchfab.com/avatars/a52a569eb88646aa8d86b838da005060/57df569d94064b5e8e8908b94931a677.jpeg',
      'height': 90},
     {'size': 3420,
      'width': 100,
      'url': 'https://media.sketchfab.com/avatars/a52a569eb88646aa8d86b838da005060/3424d5fe17274041980f9eed2c783532.jpeg',
      'height': 100}]},
   'uri': 'https://api.sketchfab.com/v3/users/7c59850017a847cb80452f0f942d0839'},
  'description': 'A chair flip animation showing how a methly group on Methcyclohexane can transition from axial to equitorial.',
  'faceCount': 9016,
  'createdAt': '2021-09-16T00:45:36.516384',
  'vertexCount': 4620,
  'isAgeRestricted': False,
  'archives': {'glb': {'textureCount': 0,
    'size': 460324,
    'type': 'glb',
    'textureMaxResolution': 0,
    'faceCount': 9016,
    'vertexCount': 7140},
   'gltf': {'textureCount': 0,
    'size': 134716,
    'type': 'gltf',
    'textureMaxResolution': 0,
    'faceCount': 9016,
    'vertexCount': 7140},
   'source': {'textureCount': None,
    'size': 2347488,
    'type': 'source',
    'textureMaxResolution': None,
    'faceCount': None,
    'vertexCount': None},
   'usdz': {'textureCount': None,
    'size': 222223,
    'type': 'usdz',
    'textureMaxResolution': None,
    'faceCount': None,
    'vertexCount': None}},
  'license': 'by-nc-sa'},
 'd00ee56cac44494a89bad5b6776077a1': {'uri': 'https://api.sketchfab.com/v3/models/d00ee56cac44494a89bad5b6776077a1',
  'uid': 'd00ee56cac44494a89bad5b6776077a1',
  'name': 'Mackintosh chair',
  'staffpickedAt': None,
  'viewCount': 40,
  'likeCount': 0,
  'animationCount': 0,
  'viewerUrl': 'https://sketchfab.com/3d-models/d00ee56cac44494a89bad5b6776077a1',
  'embedUrl': 'https://sketchfab.com/models/d00ee56cac44494a89bad5b6776077a1/embed',
  'commentCount': 0,
  'isDownloadable': True,
  'publishedAt': '2019-11-30T17:54:47.871706',
  'tags': [{'name': 'augmentedreality',
    'slug': 'augmentedreality',
    'uri': 'https://api.sketchfab.com/v3/tags/augmentedreality'},
   {'name': 'industrialrevolution',
    'slug': 'industrialrevolution',
    'uri': 'https://api.sketchfab.com/v3/tags/industrialrevolution'},
   {'name': 'tiltbrush',
    'slug': 'tiltbrush',
    'uri': 'https://api.sketchfab.com/v3/tags/tiltbrush'},
   {'name': 'design',
    'slug': 'design',
    'uri': 'https://api.sketchfab.com/v3/tags/design'}],
  'categories': [{'name': 'architecture'}, {'name': 'furniture-home'}],
  'thumbnails': {'images': [{'uid': '5864fbef592f47fe9cf7838543d014ea',
     'size': 48997,
     'width': 1920,
     'url': 'https://media.sketchfab.com/models/d00ee56cac44494a89bad5b6776077a1/thumbnails/fe5a6ba61227403d9f9f42b55497a1cd/bc1e3ba03a8f4a7dbe6345157520b440.jpeg',
     'height': 1080},
    {'uid': 'e3b39486bbc343308793209243f006b9',
     'size': 17148,
     'width': 1024,
     'url': 'https://media.sketchfab.com/models/d00ee56cac44494a89bad5b6776077a1/thumbnails/fe5a6ba61227403d9f9f42b55497a1cd/dea59c8cec834ed38d3c4515d7dab70d.jpeg',
     'height': 576},
    {'uid': 'ca5572f312fc4e9cb1a6aa9e796f4ef9',
     'size': 9891,
     'width': 720,
     'url': 'https://media.sketchfab.com/models/d00ee56cac44494a89bad5b6776077a1/thumbnails/fe5a6ba61227403d9f9f42b55497a1cd/d00ef1ccd03948d8844af74f5d154d43.jpeg',
     'height': 405},
    {'uid': 'e2e592926dea4a5eb0666dd43dd330e1',
     'size': 2190,
     'width': 256,
     'url': 'https://media.sketchfab.com/models/d00ee56cac44494a89bad5b6776077a1/thumbnails/fe5a6ba61227403d9f9f42b55497a1cd/440cd4ebceb84d4fb1aba5c8358f3471.jpeg',
     'height': 144},
    {'uid': '23823285cc0449e19a2e87a623a24d2b',
     'size': 518,
     'width': 64,
     'url': 'https://media.sketchfab.com/models/d00ee56cac44494a89bad5b6776077a1/thumbnails/fe5a6ba61227403d9f9f42b55497a1cd/56e9c08d75aa44a1881c515903970ac6.jpeg',
     'height': 36}]},
  'user': {'uid': '325b329a6b4d4cd5b955fa9927ea3f1a',
   'username': 'davidmingorance',
   'displayName': 'davidmingorance',
   'profileUrl': 'https://sketchfab.com/davidmingorance',
   'account': 'basic',
   'avatar': {'uri': 'https://api.sketchfab.com/v3/avatars/eca1754166e74512880e3d1c638b3495',
    'images': [{'size': 822,
      'width': 32,
      'url': 'https://media.sketchfab.com/avatars/eca1754166e74512880e3d1c638b3495/3c06faf0146449d19873b10b088f342c.jpeg',
      'height': 32},
     {'size': 1439,

In [54]:
classes = list(chain(*list(objects_to_filter.values())))
items = sampled_json.items()

for name, properties in items:
    for class_name in classes:
        if class_name in properties["name"].lower():
            sampled_json[name]["class"] = class_name
            break

In [ ]:
with open("sampled_classes_january.json", "w") as f:
    json.dump(sampled_json, f)

In [53]:
sampled_json

44478

In [ ]:
sampled_json.popitem()[1][]